### ISSUE TITLE
Add GetServices Extension method to IServiceProvider

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/DependencyInjection#119]
See MVC 5.0 IDependencyResolver signature:

```c#
public interface IDependencyResolver
{
    object GetService(Type serviceType);
    IEnumerable<object> GetServices(Type serviceType);
}
```

**Comment by wwwlicious** [comment]
+1 I was looking for this recently, instead has to register a collection which just seemed...not very DI

**Comment by yishaigalatzer** [comment]
@wwwlicious you don't register a collection instead register multiple services and resolve an 'ienumerable<servicetype>'

**Comment by Eilon** [comment]
@yishaigalatzer close this bug then?

**Comment by wwwlicious** [comment]
ah, like this?
 ```csharp
var sc = new ServiceCollection();
sc.Add<TInterface, TConcrete>();
sc.Add<TInterface, TConcrete2>();
var sp = sc.BuildServiceProvider();
var instances = sp.GetService<IEnumerable<TInterface>>();

```

**Comment by yishaigalatzer** [comment]
@eilon I plan to modify it a bit and submit a pr. Just a simple sugar on top API
@wwwlicious yup, that's it

**Comment by wwwlicious** [comment]
FYI, this didn't work when using constructor injection for IEnumerable<TInterface>

**Comment by yishaigalatzer** [comment]
@wwwlicious we are using this pattern regularly in the framework.
I don't know if we support resolving a generic interface though.

This works:
```C#

// define
public interface Base { }

public class Impl1 : Base { }

public class Impl2 : Base { }

// register
...

// resolve

public class TestingController
{
    public void TestingController(IEnumerable<Base> implementations) { }
}

```

If you find that it doesn't can you provide a full sample so we can investigate (in a separate issue please :))
