### ISSUE TITLE
Add component that deals with the abstraction between callcontext/asynclocal

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/DependencyInjection#158]
As a developer, in cases where I need to access request scoped data from within singleton instances, I would like a component that deals with the abstraction between callcontext/asynclocal - `IScopedData<T>`. I could do this manually myself, but this seems like something that should be commonly handled.

This came out of a discussion I had with @davidfowl on Jabbr.

**Comment by Eilon** [comment]
Moving this to Backlog as we are not planning to make any changes for this at this time.

**Comment by davidfowl** [comment]
Doesn't need to be built in.
