### ISSUE TITLE
Add Debugger attributes to IServiceDescriptor

### ISSUE THREAD

**Issue by ilmax** [aspnet/DependencyInjection#161]
Since IService Collection is used in some part, it can be useful to simplify inspection of it's elements.

**Comment by yishaigalatzer** [comment]
ServiceDescriptor is already covered with [DebuggerDisplay]

https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Framework.DependencyInjection/ServiceDescriptor.cs#L9

DebuggerAttribute cannot be defined on an interface.

 [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Delegate, AllowMultiple = true)]
    [ComVisible(true)]
    public sealed class DebuggerDisplayAttribute : Attribute
    {

CC @muratg
