### ISSUE TITLE
IServiceCollection not found in Microsoft.Framework.DependencyInjection

### ISSUE THREAD

**Issue by Ph47** [aspnet/DependencyInjection#162]
Today after last update DependencyInjection broke.

Broken code here: https://gist.github.com/Ph47/fb78936df0786e5c0f2a

"kpm build" says: 
> error CS0012: The type 'IServiceCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Framework.DependencyInjection.IServiceCollection, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

kre is 1.0.0-beta3-10921

I tried different version of Microsoft.Framework.DependencyInjection and last is 1.0.0-rc1-10711

At DependencyInjection version 1.0.0-beta3-10754 other symptoms. Compilation goes fine, but on "k web" i have exception: 
> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.DependencyInjection.IServiceCollection, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by Eilon** [comment]
Clear out  `%UserProfile%\.kpm` because there might be some other bogus `rc1` packages there. The latest is all supposed to be `beta3` but we inadvertently published some `rc1` packages.

**Comment by Ph47** [comment]
Eilon Thanks! Clearing packages solve my problem.

**Comment by IonRobu** [comment]
Hi Eilon, I have a 'clean' beta4 installation (only .dnx, not .k), and I try to refer a third party package built on beta3 version, and got exactly the same error.

**Comment by Eilon** [comment]
@IonRobu you'll need to get a version of that package that is built against beta4 then. All the packages used in the project have to be compiled against the same version. Please note that this is just painful right now because we're shuffling things around a lot while the project is in preview. Once it hits 1.0-rtm this won't happen anymore.
