### ISSUE TITLE
Should we remove support for remapping service types through configuration

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/DependencyInjection#174]
https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Framework.DependencyInjection/ServiceDescriber.cs#L130

We keep telling customers that we don't want them to swap out services, but the mechanism above provides a very straightforward first class support to do just that. It is also very basic as it has no subkey required.

I'm suggesting we remove this completely, or make it a more clearly defined (like looking for `services.Key`  instead of `Key`

**Comment by davidfowl** [comment]
We need this for services that come from hosting, (things that happen before the application entry point is invoked).

**Comment by yishaigalatzer** [comment]
Is it possible to limit it by default to this scenario? And if not should we put it under a ServiceReplacement node?

**Comment by HaoK** [comment]
@davidfowl Config Service replacement is going away via removal of ServiceDescriber, do you want me to keep the functionality in some form but moved into Hosting as part of the removal, or can I just file a work item (are we relying on this behavior today in hosting?)
