### ISSUE TITLE
API review: IServiceCollection changes

### ISSUE THREAD

**Issue by muratg** [aspnet/DependencyInjection#185]
- [ ] Make the interface implement IList instead of ICollection. IList matches ordered 
- [ ] Remove ```IServiceCollection Add(IServiceDescriptor descriptor)``` method to avoid conflict with IList.add

**Comment by BrennanConroy** [comment]
The Add(IServiceDescriptor descriptor) method doesn't conflict with anything, and a lot of code uses that method. Can we keep it?

**Comment by GrabYourPitchforks** [comment]
The downside to having `Add(ServiceDescriptor) : IServiceCollection` as a proper interface method is that you can't simply new up a `List<ServiceDescriptor>` and cast it to the `IServiceCollection` interface. If this were instead an extension method then this scenario would just work.

**Comment by BrennanConroy** [comment]
Ok, I'll make it an extension method if people are ok with that.
