### ISSUE TITLE
API review: IScopedInstance needs design discussion

### ISSUE THREAD

**Issue by muratg** [aspnet/DependencyInjection#186]
- What do we do with this interface?
-  ScopedInstance<T> also needs to be discussed

**Comment by davidfowl** [comment]
@HaoK @rynowak @dougbu @divega 

Is it just MVC that uses this? We'd like to get rid or it.

/cc @lodejard

**Comment by dougbu** [comment]
@davidfowl a quick search of Universe shows `IScopedInstance` use in MVC and Entropy (but that's probably MVC-related).  MVC uses the interface / default implementation to make some per-request contexts (`ActionContext`, `ActionBindingContext`, and `AntiForgeryContext`) available to MVC services without sticking the contexts directly into DI.  are you suggesting we move `IScopedInstance` and `ScopedInstance` into MVC?

**Comment by HaoK** [comment]
Yeah when I did the rename i think it was only MVC/Entropy as well.  +1 to just move these to MVC

**Comment by HaoK** [comment]
Some more context in Issue #49, it made more sense in DI when HttpContext was using this as part of the RequestContainer/Hosting code.  But now that hosting is using its own HttpContextAccessor, there doesn't seem to be a reason to keep this shared anymore

**Comment by davidfowl** [comment]
Yea, I think step 1 is to remove the it from DI and step 2 is to figure out if MVC should be using this pattern at all. Last we discussed it it was an anti pattern like ITypeActivator.

**Comment by muratg** [comment]
Who would be doing the first step (i.e. remove it from DI and move it to MVC temporarily)? @rynowak

**Comment by HaoK** [comment]
I can do step 1 if needed, it shouldn't be hard

**Comment by muratg** [comment]
:+1:
