### ISSUE TITLE
Add generics suport in AddScoped

### ISSUE THREAD

**Issue by kiide** [aspnet/DependencyInjection#203]
Hi guys, If I have a generic repository, i have write all injection code on Startup.cs

![image](https://cloud.githubusercontent.com/assets/5432753/6580903/3fea67b6-c732-11e4-9ba7-cdb584e800f7.png)

Exists support or any mode for generic injection?

![image](https://cloud.githubusercontent.com/assets/5432753/6580912/58c00926-c732-11e4-94d1-6b5d14e3b4b3.png)

**Comment by HaoK** [comment]
Can't you just do services.AddScoped(typeof(Repo<>), typeof(Repo<>))?

**Comment by davidfowl** [comment]
Yep

**Comment by kiide** [comment]
Oh sorry guys, I has tried it yesterday before open this issue :c but i try again now and works perfectly! You are awesome!
