### ISSUE TITLE
Review if a package description is needed for these packages

### ISSUE THREAD

**Issue by Praburaj** [aspnet/DependencyInjection#208]
```
DependencyInjection\src\Microsoft.Framework.DependencyInjection.Autofac
DependencyInjection\src\Microsoft.Framework.DependencyInjection.Ninject
```

**Comment by Eilon** [comment]
You mean "is *needed*"? Otherwise not sure what the issue is here.

**Comment by Praburaj** [comment]
Some of the packages are missing description while doing a scan of universe. Some of the packages need not have description. So I filed bugs with a generic title in all repos to review if a package description is needed :smile:

**Comment by Eilon** [comment]
Ah ok it's just the title of the bug that was wrong (it was missing the word "needed" :smile: ).

**Comment by davidfowl** [comment]
Feels like we can remove all of the 3rd party providers now.

**Comment by Eilon** [comment]
Not needed - we are removing these projects.
