### ISSUE TITLE
Add utility method to Populate StructureMap

### ISSUE THREAD

**Issue by halter73** [aspnet/DependencyInjection#22]
- this populates and duck-punches the adjustments for required behaviors. 
- `void static StructureMapFooStatic.Configure(IEnumerable<IServiceDescriptor> services, IRegistry registry)`

**Comment by henkmollema** [comment]
I figured Microsoft is not going to provide DI framework adapters but rather work together with the framework authors to publish their own adapters. Perhaps this along with #23 and #24 can be closed to keep the backlog a bit tidier.

**Comment by davidfowl** [comment]
Yep! We already removed the other providers.
