### ISSUE TITLE
Add an ability to bind same interface to several implementations

### ISSUE THREAD

**Issue by vadimwind** [aspnet/DependencyInjection#228]
It can be similar to the Ninject Named binding:

`serviceCollection.AddScoped<IRepository, DefaultRepository>("Default");`
`serviceCollection.AddScoped<IRepository, AnotherRepository>("Another");`
...
`var repository = provider.GetService<IRepository>("Default");`

**Comment by wholroyd** [comment]
+1

**Comment by brockallen** [comment]
+1

**Comment by MikhailNazarov** [comment]
+1

**Comment by HaoK** [comment]
Note this would also give us named options back for free :)

**Comment by brockallen** [comment]
Nothing's free -- just prepaid. :)

**Comment by Eilon** [comment]
The DI system in DNX is designed around supporting the most common set of features so that other DI systems can be adapted to it. If you have a need for named bindings we recommend using a DI system that supports it and integrating it with DNX.
