### ISSUE TITLE
How can I get an injected instance outside a controller?

### ISSUE THREAD

**Issue by ninety7** [aspnet/DependencyInjection#229]
I have a multi-project solution where the ASP.NET 5 project references a class library project (vnext). The class library project has a few classes where I'd like to inject a the options model configured on the Startup.cs class of the web project.
```csharp
services.Configure<Data>(Configuration.GetSubKey("Data"));
```
I have googled for a way to do this with no success, can anybody shed me some light on the matter?

**Comment by Eilon** [comment]
@ninety7 can you show a bit more about what your code looks like? Not enough information here to give much of an explanation.

The DI feature is certainly not restricted to MVC - you should be able to use it anywhere.

**Comment by lovemory** [comment]
I have the same question about this title.
It is two way get an injected instance  on a Controller
1)use [FromServices] attribute,for example:
      [FromServices]
        public IConfiguration Configuration { get; set; }
2)user paramer,for example:
       public XXXController(IConfiguration config)
        {
        }

but ,how can i  get the injected instance  in a common class as 
MessageServices.cs
   public class AuthMessageSender : IEmailSender, ISmsSender
{
}

**Comment by Boglen** [comment]
I think you can get it only if you add AuthMessageSender into service collection

**Comment by Eilon** [comment]
@lovemory it depends on who creates the `AuthMessageSender` class. If that type is created by DI, just add some constructor parameters to it and those parameters will also be resolved by the DI container. The idea is to create a chain of dependencies via constructors, and as long as the "root" is created by DI, everything else will also be created by DI.

**Comment by Eilon** [comment]
Closing this for now because it's not clear what the exact scenario is. If folks have specific code that doesn't work, please post a new issue with as much info as possible about the scenario and what doesn't work. Thanks!
