### ISSUE TITLE
Suggestion: Rename ServiceDescriptor

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/DependencyInjection#235]
I think for most people, "descriptor" - while an okay term - is a bit heavy.   Digging into things, it was easy enough to figure out what was being done.  But the generic name did make me second guess my own understanding.

For something that will be pretty commonly used, maybe it would be nicer to have an idiomatic name like "BindAs" or "BindingType".  I noticed in #184 and #194 that there's a convention for names starting with "Service", but maybe that's not necessary if there's any impetus to offer a more verb-y API?

**Comment by davidfowl** [comment]
I don't this it warrants the amount of pain that will be caused by another major rename. I think the names are fine, but that's my personal opinion. We have already done API reviews for DI and this API is pretty much "stable".

**Comment by atrauzzi** [comment]
Is it sound to forego an opportunity because decisions have been made in the past over what's in question?  I appreciate my suggestion is subjective, but this is a highly visible chunk of the API that reads heavy like Java.

Is this more complicated than a find+replace across all ASP.NET properties?

**Comment by davidfowl** [comment]
It's not that I don't think there's anything wrong with the name and this adds no value, it's all subjective.

**Comment by Eilon** [comment]
This matches the common naming conventions used throughout a lot of ASP.NET.
