### ISSUE TITLE
Consider adding the OWIN environment dictionary to the signature of IServiceScopeFactory.CreateScope();

### ISSUE THREAD

**Issue by jeremydmiller** [aspnet/DependencyInjection#237]
We're seeing folks on the StructureMap list and on Twitter that are trying to use the same logical nested container between global OWIN middleware and MVC6 at the back. If you were to pass the OWIN environment dictionary for the request (or your abstraction for the same), you would be able to reuse a per-request nested container between OWIN middleware and MVC6. I think it would also be useful to inject things from the OWIN environment dictionary into a per-request container so you can use plain constructor injection to pass the request centric services into concrete handlers created during the request.

We did something similar in FubuMVC and I think it worked out well for us.

**Comment by davidfowl** [comment]
If the goal is about sharing per request services, it sounds like we'd want to expose the delegate used to resolve a service not the one to create a scope. We create the scope in the hosting pipeline already and in order for pure owin middleware to get those services it would need to call resolve. Does that sound like what you're going for?
If we see going to expose our abstraction via the OWIN environment it would be a non standard key, something like aspnet.resolver. I'd recommend discussing this with the OWIN committee as well so they can determine if it is something they want to make first class or not. We had the same discussion about the add middleware func (we just implemented what they came up with).

**Comment by jeremydmiller** [comment]
You guys might be missing an opportunity here. Doing this would have enabled some more effective ways of doing multi-tenancy through IoC support and also allowing you to inject the raw OWIN dictionary or OwinContext into objects resolved during a request. Wanna reconsider this? We're definitely taking this approach for Jasper.

**Comment by davidfowl** [comment]
I'm not sure what you mean, we're not pushing back on the feature itself. If you prose something to the OWIN committee and they agree, we will support it. It's up to them to decide what the delegate structure should look like. We have a similar pattern for building up the applications https://github.com/aspnet/HttpAbstractions/pull/379

I'd recommend talking to them in https://gitter.im/owin/owin or https://github.com/owin/owin/ and proposing something.
