### ISSUE TITLE
Question: Adding Services from Types in Class Libraries

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/DependencyInjection#242]
I am moving a Unity based MVC web application to ASP.NET 5. This web app invoked Plugins/Modules in class libraries which registered services with the Unity container.
I am struggling a bit with the built in DI of ASP.NET 5. The startup.cs ConfigureServices() offers IServiceCollection which I can use to add services, but to invoke the Plugin ( using createInstance from ActivatorUtilities ), I need to have an instance of IServiceProvider which is provided in startup.cs Configure().
I can always write my own CreateInstance() which doesn't require an instance of IServiceProvider, but before I do that, I am hoping I can get some guidance from the DI team.
What is the recommended way to load services from class libraries?

**Comment by davidfowl** [comment]
What exactly does loading services from class libraries mean? MVC is a class library and it enables this by having the user call `services.AddMvc()` in their `Startup.cs`. What exactly are you looking for? Assembly scanning?

**Comment by ToddThomson** [comment]
@davidfowl With MVC 5 I used ServiceLocator and Unity to dynamically invoke an IModule based class ( contained in a class library dll ) by providing a Type definition that came from a property in web.config. I then called into the module to register a number of services with the Unity container.
I want to do the same thing with ASP.NET 5 DI. However, to use the built in DI to instantiate a Type, the ActivatorUtilities.CreateInstance API call requires an Instance of IServiceProvider.
The problem I have is that in startup.cs DI services are setup in ConfigureServices, but the IServiceProvider is provided in startup.cs Configure. I could setup all my dynamically discovered services in startup.cs Configure(), but there is no way ( at least that I can see ) to add additional services at that time.
I appreciate any guidance you can give ( or I will likely just roll my own activator utility for invoking the IModule ).

**Comment by ToddThomson** [comment]
@davidfowl I used System.Activator.CreateInstance( fullyQualifiedType ) to obtain the module. I can call into the module class with Initialize( IServiceCollection ) to register services.
I still feel that it is a bit odd that in startup.cs Configure() I cannot add additional services to the DI container - is there a reason for this restriction or am I missing something?

**Comment by davidfowl** [comment]
the IServiceProvider is readonly, you can't add services at runtime in ASP.NET. We don't support that. It's something you'd have to build into your system.

**Comment by ToddThomson** [comment]
Thanks @davidfowl . I have a better understanding of the DI used in ASP.NET 5 now. It meets my needs.
