### ISSUE TITLE
Overriding the lifetime of a dependency from a previous registration should cause some kind of warning or error

### ISSUE THREAD

**Issue by divega** [aspnet/DependencyInjection#243]
Things are often designed so that only a specific service life time is correct for a given shared dependency in a given application. Attempting to re-register a dependency using a different life time is a likely indication of user error and can have unexpected consequences. See aspnet/EntityFramework#2052 as an example that brought this problem to our attention.  

More details of how this should work are needed. I am intentionally not trying to design it here :smile:

cc @lodejard, @davidfowl and @anpete.

**Comment by muratg** [comment]
Yup, this seems broken to me too.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/DependencyInjection/issues/66, which we decided is Won't Fix.
