### ISSUE TITLE
Registration by convention

### ISSUE THREAD

**Issue by kspearrin** [aspnet/DependencyInjection#250]
Is there a way to do dependency registration by convention? For example, for a given namespace register all non-abstract classes with their default interface implementations.

Something like Ninject allows with their convention extensions: https://github.com/ninject/ninject.extensions.conventions

**Comment by davidfowl** [comment]
Nope. We don't support anything like this but it should be trivial to implement as an extension. You could also just use ninject.

**Comment by kspearrin** [comment]
Thanks. I just wanted to check if there was an easy way by default before trying to roll my own extensions or bringing in Ninject.
