### ISSUE TITLE
GetRequiredServices performance

### ISSUE THREAD

**Issue by henkmollema** [aspnet/DependencyInjection#251]
`GetRequiredServices<T>` and `GetRequiredServices` check if there are any services using `Any()`. This causes the service provider to enumerate the `IEnumerable`, which may have negative performance impact. Also the collection is returned as `IEnumerable` so the consumer has to enumerate again.

See: https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Framework.DependencyInjection.Abstractions/ServiceProviderExtensions.cs#L67

Possible solution: 
Enumerate the collection by calling `ToArray()`/`ToList()` and use the `Length`/`Count` property to determine if there are any services and return the enumerated collection to the consumer.

Related: #236 
/cc @Eilon

**Comment by davidfowl** [comment]
@henkmollema Can you produce some benchmarks to see how big of a difference there is?

**Comment by henkmollema** [comment]
@davidfowl I created a basic perf test project here: https://github.com/henkmollema/DnxServiceProviderPerf

Results:
```
Current: 525,6272ms
Optimized: 596,2369ms

Current: 463,6519ms
Optimized: 576,8419ms

Current: 458,4022ms
Optimized: 558,779ms
```

As shown, using the 'optimized' version (which uses `ToArray()`) is actually slower than the current version. This is most likely caused by the fact that the current service provider implementation already returns an array: https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Framework.DependencyInjection/ServiceLookup/ClosedIEnumerableService.cs#L50.

**Comment by davidfowl** [comment]
I think the current implementation will be fine in the majority of cases. The only optimization that would fly would be an opportunistic cast to ICollection<T>.

**Comment by Eilon** [comment]
Yeah, given the rather small difference in performance (or sometimes *worse* performance), closing this out for now. Thanks for the investigation!
