### ISSUE TITLE
Put IServiceCollection extension methods used primarily by frameworks in a separate namespace

### ISSUE THREAD

**Issue by halter73** [aspnet/DependencyInjection#254]
IServiceCollection extension methods used primarily by frameworks (e.g. TryAdd  and TryAddEnumerable) should probably be moved to another namespace (maybe Microsoft.Framework.DependencyInjection.FrameworkExtensions?) since there are currently 45 public methods in ServiceCollectionExtensions and some of the names are confusing.

By putting only the methods commonly used by application developers in the Microsoft.Framework.DependencyInjection namespace, we should be able to reduce a lot of the noise in intellisense. Anyone who needs to call a less commonly used extension method simply needs to add another using statement.

**Comment by muratg** [comment]
Sounds fine to me. Simplifying IntelliSense for rarely used cases makes sense. @davidfowl?

**Comment by davidfowl** [comment]
Yep

**Comment by pranavkm** [comment]
@Eilon does this warrant an announcement?
