### ISSUE TITLE
NeutralResourcesLanguage Warnings on UWP

### ISSUE THREAD

**Issue by bricelam** [aspnet/DependencyInjection#256]
I'm getting the following warnings on a Universal Windows App.

> warning MSB3817: The assembly "Microsoft.Framework.DependencyInjection.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).

> warning MSB3817: The assembly "Microsoft.Framework.DependencyInjection.Abstractions.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).

**Comment by Eilon** [comment]
See https://github.com/aspnet/Options/issues/73

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/DependencyInjection/commit/25f57b5ec0f52c9ad2b4308455df506878c2950e

**Comment by Eilon** [comment]
@bricelam BTW can you also confirm that this does what you need for UWP apps? I want to make sure we didn't miss anything anywhere.
