### ISSUE TITLE
Question: How do I inject services created for each request?

### ISSUE THREAD

**Issue by mbharodia** [aspnet/DependencyInjection#258]
I would like to inject services (say data context) created and maintained for a life time of a web request. How do I do that? 

In this case each web request would be creating a new instance of the service; within a request the same instance that service is returned whenever requested (so kind of singleton within a request but not across various requests - similar to perRequestLifetimeManager in Unity)

Is services.AddScoped() in StartUp.cs suitable for this?

I am wondering about any documentation on configuring, adding and maintaining life time of services in Startup.cs (docs.asp.net does not have this information either)

Thanks in advance for your help.

**Comment by mbharodia** [comment]
Finally I found answer here.
http://blogs.msdn.com/b/webdev/archive/2014/06/17/dependency-injection-in-asp-net-vnext.aspx

**Comment by brockallen** [comment]
This article seems old. Is there a updated version of this somewhere?

**Comment by Eilon** [comment]
Use the `AddScoped()` APIs on the service collection, e.g.:

```c#
services.AddScoped<IRepository, MyRepository>();
```

**Comment by brockallen** [comment]
Actually, that's not quite what I was looking for. Dan pointed me at the version of AddScoped that accepted a `Func<IServiceProvider, object>` as a param. That gets me a step closer to what I was looking for (but still not exactly what I need).

**Comment by Eilon** [comment]
There are indeed many overloads of `AddScoped` depending on how the service is to be constructed.
