### ISSUE TITLE
'System.MissingMethodException' ServiceCollectionExtensions.TryAdd

### ISSUE THREAD

**Issue by MarcWils** [aspnet/DependencyInjection#259]
I get a MissingMethodException when I try to start my ASP.NET 5 application. It's an application that I created based on beta4 and now try to upgrade to beta5.

StackTrace:
System.MissingMethodException: Method not found: 'Boolean Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd(Microso
ft.Framework.DependencyInjection.IServiceCollection, Microsoft.Framework.DependencyInjection.ServiceDescriptor)'.
   at Microsoft.Framework.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services)
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

References:
Microsoft .NET Development Utility CLR-x86-1.0.0-beta5-12103

Listing dependencies for Host (<escapes>)

[Target framework DNX,Version=v4.5.1 (dnx451)]

Framework references:
  framework/fx/Microsoft.CSharp 4.0.0.0
  framework/fx/mscorlib 4.0.0.0
  framework/fx/System 4.0.0.0
  framework/fx/System.Collections 4.0.0.0
  framework/fx/System.Collections.Concurrent 4.0.0.0
  framework/fx/System.ComponentModel.DataAnnotations 4.0.0.0
  framework/fx/System.Configuration 4.0.0.0
  framework/fx/System.Core 4.0.0.0
  framework/fx/System.Data 4.0.0.0
  framework/fx/System.Diagnostics.Debug 4.0.0.0
  framework/fx/System.Diagnostics.Tools 4.0.0.0
  framework/fx/System.Globalization 4.0.0.0
  framework/fx/System.IO 4.0.0.0
  framework/fx/System.Linq 4.0.0.0
  framework/fx/System.Linq.Expressions 4.0.0.0
  framework/fx/System.Linq.Queryable 4.0.0.0
  framework/fx/System.ObjectModel 4.0.0.0
  framework/fx/System.Reflection 4.0.0.0
  framework/fx/System.Reflection.Extensions 4.0.0.0
  framework/fx/System.Resources.ResourceManager 4.0.0.0
  framework/fx/System.Runtime 4.0.10.0
  framework/fx/System.Runtime.Extensions 4.0.0.0
  framework/fx/System.Security 4.0.0.0
  framework/fx/System.Text.Encoding 4.0.0.0
  framework/fx/System.Threading 4.0.0.0
  framework/fx/System.Threading.Tasks 4.0.0.0
  framework/fx/System.Transactions 4.0.0.0
  framework/fx/System.Xml 4.0.0.0
  framework/fx/System.Xml.Linq 4.0.0.0

Package references:
* EntityFramework.Commands 7.0.0-beta5
  EntityFramework.Core 7.0.0-beta5
  EntityFramework.Relational 7.0.0-beta5
  EntityFramework.Relational.Design 7.0.0-beta5
  EntityFramework.SqlServer 7.0.0-beta5
  Ix-Async 1.2.3
  Microsoft.AspNet.Antiforgery 1.0.0-beta6-10162
  Microsoft.AspNet.Authentication 1.0.0-beta5
* Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
  Microsoft.AspNet.Authorization 1.0.0-beta6-12704
  Microsoft.AspNet.Cors.Core 1.0.0-beta6-10687
  Microsoft.AspNet.Cryptography.Internal 1.0.0-beta6-11631
  Microsoft.AspNet.Cryptography.KeyDerivation 1.0.0-beta5
  Microsoft.AspNet.DataProtection 1.0.0-beta6-11631
  Microsoft.AspNet.DataProtection.Abstractions 1.0.0-beta6-11631
* Microsoft.AspNet.Diagnostics 1.0.0-beta5
  Microsoft.AspNet.Diagnostics.Abstractions 1.0.0-beta6-13404
* Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
  Microsoft.AspNet.FeatureModel 1.0.0-beta6-11737
  Microsoft.AspNet.FileProviders.Abstractions 1.0.0-beta6-11633
  Microsoft.AspNet.FileProviders.Physical 1.0.0-beta6-11633
  Microsoft.AspNet.Hosting 1.0.0-beta5
  Microsoft.AspNet.Hosting.Abstractions 1.0.0-beta6-12141
  Microsoft.AspNet.Hosting.Server.Abstractions 1.0.0-beta5
  Microsoft.AspNet.Html.Abstractions 1.0.0-beta6-11737
  Microsoft.AspNet.Http 1.0.0-beta6-11737
  Microsoft.AspNet.Http.Abstractions 1.0.0-beta6-11737
  Microsoft.AspNet.Http.Extensions 1.0.0-beta6-11737
  Microsoft.AspNet.Http.Features 1.0.0-beta6-11737
  Microsoft.AspNet.Identity 3.0.0-beta5
* Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
  Microsoft.AspNet.JsonPatch 1.0.0-beta6-14308
  Microsoft.AspNet.Loader.IIS 1.0.0-beta5
  Microsoft.AspNet.Loader.IIS.Interop 1.0.0-beta5
* Microsoft.AspNet.Mvc 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.Abstractions 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.ApiExplorer 6.0.0-beta6-14308
* Microsoft.AspNet.Mvc.Core 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.Cors 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.DataAnnotations 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.Formatters.Json 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.Razor 6.0.0-beta6-14308
  Microsoft.AspNet.Mvc.Razor.Host 6.0.0-beta6-14308
* Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
  Microsoft.AspNet.Mvc.ViewFeatures 6.0.0-beta6-14308
  Microsoft.AspNet.PageExecutionInstrumentation.Interfaces 1.0.0-beta6-14308
  Microsoft.AspNet.Razor 4.0.0-beta6-11694
  Microsoft.AspNet.Razor.Runtime 4.0.0-beta6-11694
* Microsoft.AspNet.Routing 1.0.0-beta6-12008
* Microsoft.AspNet.Server.IIS 1.0.0-beta5
* Microsoft.AspNet.Server.WebListener 1.0.0-beta5
* Microsoft.AspNet.StaticFiles 1.0.0-beta5
  Microsoft.AspNet.WebUtilities 1.0.0-beta6-11737
  Microsoft.CodeAnalysis.Analyzers 1.0.0
  Microsoft.CodeAnalysis.Common 1.0.0
  Microsoft.CodeAnalysis.CSharp 1.0.0
  Microsoft.Framework.Caching.Abstractions 1.0.0-beta6-11623
  Microsoft.Framework.Caching.Memory 1.0.0-beta6-11623
  Microsoft.Framework.Configuration 1.0.0-beta6-11595
  Microsoft.Framework.Configuration.Abstractions 1.0.0-beta6-11595
  Microsoft.Framework.Configuration.Binder 1.0.0-beta6-11595
  Microsoft.Framework.Configuration.CommandLine 1.0.0-beta5
  Microsoft.Framework.Configuration.EnvironmentVariables 1.0.0-beta5
  Microsoft.Framework.Configuration.Ini 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel 1.0.0-beta4
  Microsoft.Framework.ConfigurationModel.Interfaces 1.0.0-beta4
* Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta4
* Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta4
  Microsoft.Framework.DependencyInjection 1.0.0-beta6-11594
  Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta6-11594
  Microsoft.Framework.FileSystemGlobbing 1.0.0-beta5
  Microsoft.Framework.Logging 1.0.0-beta5
* Microsoft.Framework.Logging.Abstractions 1.0.0-beta6-11599
* Microsoft.Framework.Logging.Console 1.0.0-beta6-11599
  Microsoft.Framework.Notification 1.0.0-beta6-10232
  Microsoft.Framework.OptionsModel 1.0.0-beta6-11563
  Microsoft.Framework.Runtime.Abstractions 1.0.0-beta6-12231
  Microsoft.Framework.Runtime.Caching 1.0.0-beta5
  Microsoft.Framework.Runtime.Interfaces 1.0.0-beta4
  Microsoft.Framework.Runtime.Roslyn 1.0.0-beta5
  Microsoft.Framework.Runtime.Roslyn.Abstractions 1.0.0-beta6-12231
  Microsoft.Framework.Runtime.Roslyn.Common 1.0.0-beta6-12231
  Microsoft.Framework.WebEncoders 1.0.0-beta6-11737
  Microsoft.Framework.WebEncoders.Core 1.0.0-beta6-11737
  Microsoft.Net.Http.Headers 1.0.0-beta6-11737
  Microsoft.Net.Http.Server 1.0.0-beta5
  Microsoft.Net.WebSockets 1.0.0-beta5
* Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta5
  Newtonsoft.Json 6.0.6
  Remotion.Linq 2.0.0-alpha-002
  System.Collections.Immutable 1.1.36
  System.Reflection.Metadata 1.0.21

Project references:
* Implementation 1.0.0

**Comment by davidfowl** [comment]
Don't mix beta5 and beta6 packages
