### ISSUE TITLE
Refactor the unit tests to remove the smells and make intent more clear

### ISSUE THREAD

**Issue by ceilidhboy** [aspnet/DependencyInjection#260]
The intent of many of the unit tests could be a lot clearer. Given that the DI container is an extensibility point, I think it'd make sense to refactor the tests so that the specification and intent are more explicit.

There are several test smells which contribute to this. Many test methods are not clearly named or are named in a very general way that gives no information as to their true intent. This is often the result of having many asserts in a single test which results in making it difficult to give a meaningful name as it's doing several things. So we end up with names like `NestedScopedServiceCanBeResolved` or `FactoryServicesAreCreatedAsPartOfCreatingObjectGraph` which assert a lot more than their names suggest.

I propose refactoring the tests into far finer-grained methods which are given names that clearly and explicitly describe what they are testing for. This would make it much easier to understand how the DI implementations are supposed to work and thus make it easier to implement new adapters for DI containers. I'd like to provide a working implementation of a StructureMap 3.0 adapter, for example, but the tests are such a mess that it makes it difficult to know exactly what's intended.

I'd be happy to have a crack at refactoring the tests and submit a PR. However, as it'd involve quite a bit of work I'd rather discuss before I start.

Comments?

**Comment by Eilon** [comment]
This sounds great! Can you send an initial PR that demonstrates a few of the changes you're looking at?

**Comment by ceilidhboy** [comment]
He Eilon, just saw this after being on holiday. I'll get on to it and send you a PR.

**Comment by Eilon** [comment]
Sounds god!

**Comment by Eilon** [comment]
We've made some improvements as part of the Specification tests: https://github.com/aspnet/DependencyInjection/tree/dev/src/Microsoft.Extensions.DependencyInjection.Specification.Tests
