### ISSUE TITLE
Create a Microsoft.Extensions.DependencyInjection.Specification.Tests package

### ISSUE THREAD

**Issue by Eilon** [aspnet/DependencyInjection#270]
Create a `Microsoft.Framework.DependencyInjection.Specification.Tests` package that has xUnit.net tests that would be used to verify implementations that are compatible with `Microsoft.Framework.DependencyInjection`. This would test things like when exceptions are thrown, how multi-registration items are returned, lifetimes, etc.

Both the Microsoft-provided and community-provided DI implementations would use this suite of tests to verify compatibility.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/DependencyInjection/commit/f1c0dbb44ae3242a713328bec649b352221b17f6
