### ISSUE TITLE
.NET Native support

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DependencyInjection#272]
To enable reflection on UWP that use .NET Native, this library should include a [runtime directive file](https://msdn.microsoft.com/en-us/library/dn600639(v=vs.110).aspx)

**Comment by Eilon** [comment]
What is there to do in DI? Isn't this more an issue for app developers? Or do we need to also pre-register a bunch of our own types?

**Comment by natemcmaster** [comment]
Whenever we use reflection (dynamic dispatch, activation, serialization, etc.), .NET Native needs metadata to make this work. For instance, [ServiceProvider.cs](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Framework.DependencyInjection/ServiceProvider.cs#L50) may lead to this directive like this.

```xml
<Type Name="Microsoft.Framework.DependencyInjection.ServiceProvider">
     <Method Name="GetService>
         <TypeParameter Name="serviceType" Browse="Required All" />
     </Method>
</Type>
```

[This blog post](http://blogs.msdn.com/b/dotnet/archive/2014/05/23/net-native-deep-dive-making-your-library-great.aspx) covers how to make libraries more compatible with .NET Native and optimizing the runtime directive file.

Unfortunately, tooling for .NET Native is not very helpful at the moment in debugging what metadata is missing, so making an optimal runtime directive may be tough. We can always just use the less-than-optimal solution and enable reflection on all types in the assembly.

**Comment by pranavkm** [comment]
Wouldn't you be using the `IServiceProvider` interface to invoke `GetService` and consequently rely on `System.Runtime` to provide the directive?

**Comment by natemcmaster** [comment]
I suspect the .NET Native compiler still needs to know to include metadata for this implementation of `IServiceProvider`, but I haven't tested this to be sure. I included the note above as an example. Optimal directive files may include [a lot](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Resources/Microsoft.CSharp.rd.xml) of directives

**Comment by davidfowl** [comment]
This actually looks pretty crazy. Are libraries developers actually expected to author these files and put them in their nuget packages? What does the end to end workflow look like for regular humans? What about all the libraries on NuGet that exist and do reflectiony things? Do they have to add this file?

**Comment by natemcmaster** [comment]
Yes, runtime directive (rd) files are ugly. Yes, they are necessary for .NET Native. 

End-users can add new rd to their own projects that will make this and other NuGet libraries work, so we don't *have* to add this to our projects. But if we don't, then the burden of making .NET Native work is shifted to library consumers.

**Comment by danroth27** [comment]
@Eilon We should probably handle this in a cross-cutting way instead of one off issues.

**Comment by Eilon** [comment]
@natemcmaster @divega ok this bug has been getting a bit stale for a while. Are there any more recent thoughts on this issue? Any non-ugly ways we can resolve this?

**Comment by Eilon** [comment]
Per a discussion with @natemcmaster this isn't needed anymore due to other changes in .NET Native.
