### ISSUE TITLE
How to DI  IHttpContextAccessor

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/DependencyInjection#277]
Hello,

I have a normal class and it need to access HttpContext. How can I DI IHttpContextAccessor httpContextAccessor in its constructor? Or is there a best practice for accessing HttpContext in a normal class.

I did  services.AddInstance<IConfiguration>(Configuration); in public void ConfigureServices(IServiceCollection services) for DI Configuration.

Thank for the help!
Gary

**Comment by henkmollema** [comment]
What kind of classes do you need dependency injection in? Within MVC pretty much every application flow starts in the application startup or a controller, where dependency injection is available.

**Comment by PrimeObjects** [comment]
Sorry it is not a normal class, it is a Controller class.   
public class KnowledgeSearchController :Controller
    {
       
        public  KnowledgeSearchController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor):base(configuration)
        {
         
        }


The configuration works fine after I added 

 public void ConfigureServices(IServiceCollection services)
        {
            services.AddInstance<IConfiguration>(Configuration);


How can I do the same to  IHttpContextAccessor? 

Cheers
Gary

**Comment by henkmollema** [comment]
`IHttpContextAccessor` is registered by the runtime and should be available in a controller.

**Comment by PrimeObjects** [comment]
In Controller class, there is a Context property, I guess I can use it to get HttpContext in my controllers.

I have many old classes that were called by HTTPHandler in ASP.NET 4 to help render web content. I'm moving them over to ASP.NET 5. They were replying on HttpContext as a parameter to get session and cache variables. So in ASP.NET 5, do I have to either use controller or middleware to handle web requests if I don't want to make big change to do MVC? And I know I can pass Context to my old class in controller. There must be a similar way to get Context in middleware code, I guess? 

Thank you
Gary

**Comment by henkmollema** [comment]
Yes, the `Context` property of the `Controller` class is the current `HttpContext`.

Regarding your second question, it depends. If your not using any features of MVC (model binding, view engines, output formatting) than middleware might suit you better. Though it's a bit more low-level.

The current `HttpContext` is injected in the `Invoke` method of middleware:
```csharp
public class MyMiddleware
{
    private readonly RequestDelegate _next;

    public MyMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        // do stuff here...

        // call the next middleware in the pipeline
        await _next(context);
    }
}
```

**Comment by PrimeObjects** [comment]
It is what I'm guessing. So I will assume all my classes that contain business logic and content render code will be called either from controller or middlewares in ASP.NET 5. So I will give two common parameters in their Constructor, something like the one below, it should work right?

 public class Base
    {
        protected IConfiguration _configuration = null;
        protected HttpContext _httpContext = null;
     
        public Base(IConfiguration configuration, HttpContext httpContext)
        {
               _context = httpContext;
               _configuration = configuration;
        }
}

**Comment by henkmollema** [comment]
Yes, that should work.

**Comment by PrimeObjects** [comment]
Thank you very much for the help! you can close this issue.

**Comment by henkmollema** [comment]
I can't do that, you can do it yourself using the buttons below.

**Comment by PrimeObjects** [comment]
I did not notice the button ;-)
