### ISSUE TITLE
Unable to resolve service within Startup.

### ISSUE THREAD

**Issue by Fosol** [aspnet/DependencyInjection#278]
I have implemented common code into a base Startup class.  I want to be able to resolve in a child class some of the 'scoped' objects configured in the base class.

public override void ConfigureServices(IServiceCollection services)
{
  base.ConfigureServices(services);

// How do I do resolve the type implementation I've registered in the base class?
//var value = services.GetService(typeof(mytype));
}

**Comment by pranavkm** [comment]
> I want to be able to resolve in a child class some of the 'scoped' objects configured in the base class.

Could you explain what you're trying to do? My guess is there's a better way to solve your issue than trying to resolve services at startup.

**Comment by Fosol** [comment]
I've come up with a solution for my particular requirement.  It still would be nice to immediately resolve a type within the ConfigureServices(IServiceCollection services) method though.  

I've added a property to my base Startup class to capture the IServiceProvider.
I initialize that property in the Configure(IApplicationBuilder app, IHostingEnvironment env) method.
Now I have access to the GetService() method.

You're probably right about a better way.  I may be forcing DI to be used everywhere instead of just in certain spots.

**Comment by Fosol** [comment]
To explain what I'm doing better here's my requirement.

I need to dynamically initialize a bunch of policies.  These policies are initialized within the ConfigureServices(IServiceCollection services) method.  The policies are generated after accessing information from a database.

Since I have already configured DI to know how to create a new instance of my database I wanted to use DI to give me a scoped instance.  However within the ConfigureServices method you don't actually have direct access to the IServiceProvider.

Hopefully that explains it all.

**Comment by danroth27** [comment]
>  These policies are initialized within the ConfigureServices(IServiceCollection services) method

During configure services the services are still being configured and haven't been created yet, so you can't resolve services at this point. Instead you could use the options pattern to setup your policies and make them available through DI. See http://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects for more details.

**Comment by Fosol** [comment]
Thanks!

The options pattern works well.
