### ISSUE TITLE
Dependency chain broken with Controller - it is not resolved (new'd up)

### ISSUE THREAD

**Issue by BillKrat** [aspnet/DependencyInjection#281]
My IServiceProvider is using a UnityContainer, however I'm finding that the controller is never resolved using IServiceProvider - only its parameters are.   The BuildFactoryExpression is new'ing up the controller (buried inside of an expression) which doesn't provide any hooks for me to "BuildUp" an instance.   The best I can do to achieve setter injection is to use constructor injection to get an instance of my container and have it buildup the controller - a wee bit hacky but good enough as a work around.

IMHO, for consistency it would be expected that the controller instance be created via the IServiceProvider taking advantage of all of its business rules and logic.

    public class HomeController : Controller
    {
        private string _data;

        [Dependency]
        public IFoo Foo { get; set; }

        public HomeController(IUnityContainer container)
        {
            container.BuildUp(this);
        }

        public IActionResult Index()
        {
            _data = Foo.GetData();
            return View();
        }

![controller](https://cloud.githubusercontent.com/assets/10552946/9429800/9fb9f380-49a2-11e5-9833-c5968e26602e.png)

**Comment by davidfowl** [comment]
Add the controller type to the container. Also this is an mvc issue please open the issue there

**Comment by BillKrat** [comment]
Hi David,
Can you please elaborate so that I can intelligiently address this is an MVC issue?  I hesitate because the issue appears to reside within the DependencyInjection.Abstractions ActivatorUtilities class - more specifically the BuildFactoryExpression process.

Note: I added the HomeController to the container, per your suggestion, as a transient and in my ServiceProvider expected it to be handled by the default provider - with this expectation I threw in line 31 where I use the Unity container Buildup to process setter injection (real world I'd check for null first ;)...  It never made it to my provider, still being new'd up.  Disclaimer: this is a poor man's Unity provider until the new team releases one - will permit me to move forward using Unity.

![issue](https://cloud.githubusercontent.com/assets/10552946/9430279/513cd256-49b4-11e5-81cf-d983029eabdc.png)

**Comment by rynowak** [comment]
/cc @pranavkm 

@BillKrat - MVC doesn't do this by default because that would require everyone do register all controllers with DI.

You can opt into getting controllers from DI with options on the builder.

**Beta-6 or older**
```
services.AddMvc();
services.WithControllersAsServices(...);
```

**Beta-7 or newer**
```
services.AddMvc().AddControllersAsServices(...);
```

You can either pass in a list of types here or a list of assemblies. Give this a try and if it doesn't do what you want or hit issues, please open a bug on MVC.

**Comment by BillKrat** [comment]
That did it, I'm no longer blocked :+1:
