### ISSUE TITLE
DbContext no more accessible

### ISSUE THREAD

**Issue by ducalai** [aspnet/DependencyInjection#285]
Hi

I am playing around with MVC Music Store and I try to access Entities from DbContext once it has been initialized with very last line SampleData.InitializeMusicStoreDatabaseAsync(app.ApplicationServices).Wait() in Startup.cs file.

If right after that static call, I reach DbContext using var db = `app.ApplicationServices.GetService<MusicStoreContext>()`, then every access to db.[Entity].ToListAsync() generates an "Object reference not set to an instance of an object" exception.

This exception is not thrown if I remove the using block when accessing the DbContext in SampleData.InitializeMusicStoreDatabaseAsync. 

This exception was not thrown in beta6. Is that a bug or am I doing anything wrong?

Thanks for your help
Alain

**Comment by davidfowl** [comment]
Can you file this issue on EntityFramework?
