### ISSUE TITLE
[Investigation] DI performance

### ISSUE THREAD

**Issue by muratg** [aspnet/DependencyInjection#286]
We should look at the performance of DI and see if we need to improve.

**Comment by pranavkm** [comment]
Is there anything in specific we know is problematic? Or is this simply doing some perf work here?

**Comment by davidfowl** [comment]
Related https://github.com/aspnet/DependencyInjection/issues/124

We also have another bug that I cannot find that shows GetService adding things to a ConcurrentBag have a significant performance impact. There were also memory concerns about using expression tree compilation (@rynowak has some profiles for that).

/cc @DamianEdwards @lodejard @rynowak

**Comment by benaadams** [comment]
Related: #288

**Comment by danroth27** [comment]
Let's just use the specific issues to track the current perf investigations.

**Comment by muratg** [comment]
@danroth27 sounds good. You should file @davidfowl's concern mentioned above in that case.
