### ISSUE TITLE
Reduce calls to GetRequiredService<> across the board

### ISSUE THREAD

**Issue by muratg** [aspnet/DependencyInjection#287]
It's a bad pattern, and breaks the dependency graph.  We probably won't be able to remove all usages, but we should try to minimize the calls.

**Comment by Eilon** [comment]
@davidfowl @lodejard how strongly do we care about this at this point?

**Comment by davidfowl** [comment]
I care about this a lot, mvc and ef are the worst offenders and we should take a look at why we need to do it so much

**Comment by lodejard** [comment]
It's kind of an evergreen issue, something to watch out for in new code in general, and good to make a pass and see if there's more hanging fruit? Maybe it's part of a best practices kind of thing - calling GetService should be a last resort, something people should question if they see it in a PR, and should also be accompanied with a comment "why this spot in the code can't use DI"

**Comment by davidfowl** [comment]
It needs to be in the our coding guidelines. We can close this issue and formiulate guidance like @lodejard said.
