### ISSUE TITLE
Reduce DI Allocations

### ISSUE THREAD

**Issue by benaadams** [aspnet/DependencyInjection#288]
For 2000 plantext requests DI allocates 16,009 objects:

![image](http://aoa.blob.core.windows.net/aspnet/DI_alloc_objects.png)

Clocking in at 788,304 bytes:

![image](http://aoa.blob.core.windows.net/aspnet/DI_alloc_bytes.png)

Which would mean if you were performing 1M rps the GC would have to flush 8,004,500 objects and 394 Mbytes per second, 788 Mbytes per second for 2M rps and 2.76GBytes (56M objects) per second for 7M rps (~10GbE saturation)

**Comment by benaadams** [comment]
This change cuts the object allocations for 2400 plantext requests from 16,009 to 58:

![image](https://cloud.githubusercontent.com/assets/1142958/9850649/eef4ee6e-5aeb-11e5-8f76-e8eff9046700.png)

The bytes allocated from 788,304 to 4,664, also it should not grow per request:

![image](https://cloud.githubusercontent.com/assets/1142958/9850687/2169c41e-5aec-11e5-843b-7093fa003b25.png)

So the GC should have limited work to do related to DI.

**Comment by benaadams** [comment]
Question should ```_createServiceAccessor``` be reset each time?

**Comment by benaadams** [comment]
> Question should _createServiceAccessor be reset each time?

No, has no state, is pointer to current object's function

**Comment by benaadams** [comment]
Updated images @rynowak  are they displaying?

**Comment by benaadams** [comment]
See https://github.com/aspnet/HttpAbstractions/issues/402#issuecomment-140336990 for details on server run improvements (61.5k rps -> 1.49M rps)

**Comment by benaadams** [comment]
Tests were actually done for 2000 plaintext responses, so results are worse than reported at top. @davidfowl wanted some more details so breakdown for bytes as follows:

![d0](http://aoa.blob.core.windows.net/aspnet/di-0.png)

![d1](http://aoa.blob.core.windows.net/aspnet/di-1.png)

![d2](http://aoa.blob.core.windows.net/aspnet/di-2.png)
...
![d3](http://aoa.blob.core.windows.net/aspnet/di-3.png)

**Comment by benaadams** [comment]
Updated top numbers for actual requests performed

**Comment by benaadams** [comment]
All change... will update the figures from both sides

**Comment by rynowak** [comment]
Closing this due to 49520a2a73251a9f718743df4a43d26514021767

Reopen if you find more actionable work here.

**Comment by benaadams** [comment]
49520a2a73251a9f718743df4a43d26514021767 is an inscrutable reason... I assume you mean [bbb9acf101d4f9b3b818834c60572f67ec16ac63](https://github.com/aspnet/DependencyInjection/commit/bbb9acf101d4f9b3b818834c60572f67ec16ac63) :grinning:
