### ISSUE TITLE
Accessing IServiceProvider in static context

### ISSUE THREAD

**Issue by sergeyzwezdin** [aspnet/DependencyInjection#294]
In earlier versions of ASP.NET MVC, when everyone integrated IoC-container by himself, there was ability to store link to container in static field to access it from somewhere else.

It could be useful for some 3rd party objects which isn't integrated with ASP.NET pipeline and didn't store at container. I know it isn't the best situation, but it's quite possible.

Is it possible to do with `IServiceProvider`?

And another one related question. At `startup.cs`we have `ConfigureServices()` and `Configure()` methods - whether it possible to get reference to `IServiceProvider` to store it in 3rd party component, which can use it later?

**Comment by henkmollema** [comment]
You _could_ create a simple class with a static property with a reference to the service provider and set it in your `Configure()` method:
```csharp
// This needs better naming..
public class ServiceProviderProvider
{
    public static IServiceProvider ServiceProvider { get; set; }
}

// ...

public void Configure(IApplicationBuilder app)
{
    ServiceProviderProvider.ServiceProvider = app.ApplicationServices;
}
```

This is pretty ugly though and should be avoided as much as possible - it's not too hard to implement proper constructor injection DI across your application. @davidfowl is probably gonna slap me for this. :grimacing:

**Comment by khellang** [comment]
In `Configure` you ge `IApplicationBuilder` passed in, which has an `ApplicationServices` property (`IServiceProvider`).

You can easily do something like

```csharp
public void Configure(IApplicationBuilder app)
{
    GetMeSomeServiceLocator.Instance = app.ApplicationServices;
}

public static class GetMeSomeServiceLocator
{
    public static IServiceProvider Instance { get; set; }
}
```

and then later, somewhere totally unrelated, do

```csharp
public void SomeRandomMethod()
{
    var service = GetMeSomeServiceLocator.Instance.GetService<IMyAwesomeService>();

    // Do something with service
}
```

It's a horrible anti-pattern, though.

**Comment by henkmollema** [comment]
Nice timing @khellang :smile:

**Comment by khellang** [comment]
LOL :+1:

**Comment by davidfowl** [comment]
bad @henkmollema ! :smile: 

It won't even work for MVC services because they are scoped. You really need to get a handle on per request scope itself (probably backed by an async local). 

Why exactly do you need this?

**Comment by sergeyzwezdin** [comment]
I thought on static field as well but it pretty looks awful for me :-)

For example, there is [Hangfire library](https://github.com/HangfireIO) where we can queue some task. It stores job in database and later dequeue it and run. Hangfire have concept of [job activator](https://github.com/HangfireIO/Hangfire/blob/5a770aab402b820f262f0872b18c2d3304bb7128/src/Hangfire.Core/JobActivator.cs), but to implement this the access to container is required.

I guess there will be another scenarios where will need to access container from external component, so it's just for example.

**Comment by khellang** [comment]
I'm not sure what more you want, @sergeyzwezdin.

I doubt there will ever be a static way to access an `IServiceProvider` in the box. It's already bad enough that it's exposed through `HttpContext`.

It's pretty easy to implement something yourself, though :smile:

```csharp
public class ServiceProviderJobActivator : JobActivator
{
    public ServiceProviderJobActivator(IServiceProvider serviceProvider)
    {
        ServiceProvider = serviceProvider;
    }

    private IServiceProvider ServiceProvider { get; }

    public override object ActivateJob(Type jobType) => ServiceProvider.GetService(jobType);
}

// ...

public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        JobActivator.Current = new ServiceProviderJobActivator(app.ApplicationServices);
    }
}
```

**Comment by sergeyzwezdin** [comment]
@khellang Well, I already did this at `Configure()` method as well:

```csharp
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        GlobalConfiguration.Configuration
             .UseActivator(new ServiceProviderJobActivator(app.ApplicationServices));
    }
}
```

`GlobalConfiguration` is Hangfire's object here. But this way won't work with another cases where 3rd party code want to access container. Just thought there will be some place in framework to store reference to container.

**Comment by pranavkm** [comment]
There's a `CallContextServiceLocator` in DNX. Sample usage: https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/MvcTestFixture.cs#L70

**Comment by davidfowl** [comment]
That wont work because today it only represents runtime dependencies.

**Comment by Eilon** [comment]
Moving this to Backlog as we are not planning to make any changes for this at this time.
