### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/DependencyInjection#297]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by pranavkm** [comment]
15bda756314f70cce0f6025f6ef8defab3617cfa

**Comment by tillig** [comment]
For [the October 5 targeted release of beta 8](https://github.com/aspnet/Home/wiki/Roadmap) - is the beta 8 package going to include this change or will it first be available for RC1?

**Comment by pranavkm** [comment]
This is a RC1 change.
