### ISSUE TITLE
Dependency Injection with Multiple Constructors

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/DependencyInjection#301]
I have a tag helper with multiple constructors in my ASP.NET 5 application. This causes the following error at runtime when ASP.NET 5 tries to resolve the type:

    InvalidOperationException: Multiple constructors accepting all given argument types 
                               have been found in type 'MyNameSpace.MyTagHelper'. There should 
                               only be one applicable constructor.

One of the constructors is parameterless and the other has some arguments whose parameters are not registered types. I would like it to use the parameterless constructor.

Is there some way to get the ASP.NET 5 dependency injection framework to select a particular constructor? Usually this is done through the use of an attribute but I can't find anything.

My use case is that I'm trying to create a single class that is both a TagHelper, as well as a HTML helper which is totally possible if this problem is solved.

**Comment by pranavkm** [comment]
For services, you can register factory services that let you pick the appropriate constructor. 

TagHelpers aren't registered as services and are type activated as part of page execution: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L202. The only way to make your scenario work would be to have a custom base type where you override the behavior of this method to pick the right constructor. 

I'd suggest looking at the pattern used by Mvc's Html tag helpers (for instance https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.TagHelpers/LabelTagHelper.cs).
