### ISSUE TITLE
async/await in service registration or service resolution.

### ISSUE THREAD

**Issue by Antaris** [aspnet/DependencyInjection#303]
Is it possible to support `async`/`await` and `Task` based service resolution? I'll walk you through an example:

```
public class WorkContext : IWorkContext
{
  public WorkContext(ISecurityContext securityContext)
  {
    SecurityContext = securityContext;
  }

  public ISecurityContext SecurityContext { get; private set; }
}

public class WorkContextFactory : IWorkContextFactory
{
  private readonly ISecurityContextFactory _securityContextFactory;

  public WorkContextFactory(ISecurityContextFactory securityContextFactory)
  {
    _securityContextFactory = securityContextFactory;
  }

  public async Task<IWorkContext> CreateWorkContext(CancellationToken cancellationToken = default(CancellationToken))
  {
    // Get the security context for the current user
    var securityContext = await _securityContextFactory.GetForCurrentUser(cancellationToken);

    return new WorkContext(securityContext);
  }
}
```

 In my example above, I'm defining some implementations of abstractions provided by my framework. In a dependency, the `ISecurityContextFactory` I implement a `Task`-based async/await model because I don't know that the actual implementation _might_ do some DB work to say load the current user information.

 When I come to wire up my services, I want to utilise my `WorkContextFactory` to build my type (seperation of concerns), so I might do something like the following:

```
yield return ServiceDescriptor.Scoped<IWorkContextFactory, WorkContextFactory>();
yield return ServiceDescriptor.Scoped<IWorkContext>(sp => sp.GetService<IWorkContextFactory>().CreateWorkContext().Result);
```

 Obviously at the moment, I'm having to block until I get the result of `Task<IWorkContext>`, but it would be great if I could do something like:

```
yield return ServiceDescriptor.Scoped<IWorkContext>(sp => sp.GetService<IWorkContextFactory>().CreateWorkContext());
```

 And have the DI system understand the `Task` result and await.

 Is this possible?

**Comment by davidfowl** [comment]
Anything is possible but we so far we haven't been adding features that don't exist in other service providers. This looks like Func<T> or Lazy<T> but it's Task<T> being resolved instead of T. Maybe look at how/if other containers solve this and come back with some more data?

**Comment by Antaris** [comment]
I don't think this scenario is currently widely supported, I've not found a good working examples, so this looks to be one for the backlog until other containers implement something similar.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2353
