### ISSUE TITLE
Rename AddInstance to AddSingleton

### ISSUE THREAD

**Issue by Eilon** [aspnet/DependencyInjection#319]
The name `AddInstance` doesn't make it super clear what the lifetime is of the object. (If you stop and think about it, it can only be Singleton, but every time I call that method I have to stop and think about it.)

So, we should rename `AddInstance` to `AddSingleton`, or perhaps `AddSingletonInstance`.

**Comment by Eilon** [comment]
@lodejard @davidfowl @halter73 thoughts on the name?

**Comment by lodejard** [comment]
Is there an overload where the only difference would be between Type and Object? If that's okay any naming works for me

**Comment by pranavkm** [comment]
Makes the 3 scenarios line up:

```C#

AddSingleton<IService, MyService>();

AddSingleton<IService>(serviceProvider => new MyService(serviceProvider));

AddSingleton<IService>(new MyService());

```

**Comment by halter73** [comment]
I'm sold.
