### ISSUE TITLE
Multiple nested scope registrations

### ISSUE THREAD

**Issue by ghost** [aspnet/DependencyInjection#327]
When doing multiple nested scopes through `IServiceScopeFactory.CreateScope()`, you get nested `IServiceProvider`  instances. It doesn't, however, give access to registrations for each scope.

Therefore if you have scopes which are created further down the pipeline (with some service data only accessible from that step in the pipeline, which isn't available at the root), you can't really register services to use in there.

The sought-after structure being:
Scope (root)
     - Register (root)
     - Resolve (root level)
     <- Scope (level 1)
          - Register (level 1)
          - Resolve (root level + level 1)
          <- Scope (level 2)
               - Register (level 2)
               - Resolve (root level + level 1 + level 2)

I don't know if there's an alternative way of achieving this, but so far the documentation is scarce.

**Comment by Eilon** [comment]
Moving this to Backlog as we are not planning to make any changes for this at this time.

**Comment by dazinator** [comment]
I am looking at how to achieve the following

I have an `IServiceProvider` from RequestServices. I'd like to create a separate scope per tenant of my application. Resolving from the tenant scope should fall back to the parent scope. Is this currently how it works or is that not supported?

**Comment by dazinator** [comment]
It would be really good if I could register some sort of generic delegate into one `IServiceProvider` so that if a service is not available, the delegate is asked to resolve that service, and in there, I can chain / attempt to resolve that service from a parent IServiceProvider instead..

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2351
