### ISSUE TITLE
Add tests for ambiguous constructor selection to TestSpecification

### ISSUE THREAD

**Issue by pranavkm** [aspnet/DependencyInjection#328]
We have a bunch of tests around constructor resolution in `ServiceTest`. If the intent is to rely on the resolution behavior in code (https://github.com/aspnet/HttpAbstractions/issues/475), we need to add it as part of the test specification.

**Comment by pranavkm** [comment]
Out of curiosity, what's our feedback mechanism for these specs? Say we add these tests and some DI systems fail. How do we find out and what do we about it?

**Comment by Eilon** [comment]
They file a bug here :smile:

**Comment by khellang** [comment]
Oh, I'd make sure you guys hear it :wink:

**Comment by Eilon** [comment]
@pranavkm , see? :smile:
