### ISSUE TITLE
Best way to resolve during ConfigureServices

### ISSUE THREAD

**Issue by prasannavl** [aspnet/DependencyInjection#329]
I have a `ConfigureServices` similar to this.
```
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.AddSingleton<SomeService>();
            
           // How do I do this?
           // services.AddInstance(ctx => new AnotherService(ctx.Resolve<SomeService>()));
           // This can easily be done when using another container like AutoFac since it provides the
           // context. However when doing `services.Configure` variants its often not intuitive to
           // to use the external container. Is there a way something like this could be done inside 
           // service.Configure? 

            var builder = new ContainerBuilder();

            Temporals.AutofacRegistration.Populate(builder, services);

            builder.RegisterType<MailClient>()
                .SingleInstance();

            builder.Register((context => new HttpClient()))
                .Keyed<HttpClient>("ipApi")
                .As<HttpClient>()
                .SingleInstance();

            var container = builder.Build();



            return container.Resolve<IServiceProvider>();
        }
```

This is especially useful when dealing with Scoped services, which won't be available during the configuration. 

Is there a recommended way to do this?

**Comment by Eilon** [comment]
@prasannavl there should be no need to call the ctor explicitly when you register the second service - the DI system will automatically pass in the right parameters by looking them up in the container as well.

You can call:

```c#
services.AddSingleton<SomeService>();
services.AddSingleton<AnotherService>();
```

And the DI container will see that the constructor for `AnotherService` requires an instance of `SomeService` and it'll look that up in the service container as well.

Can you try that out and see if it works for you?

**Comment by khellang** [comment]
You should be able to do that using [this overload](https://github.com/aspnet/DependencyInjection/blob/e7e187abc46adf5203db6a0c5d3f384280fa2943/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs#L155-L171) of `AddTransient`, `AddScoped` or `AddSingleton`.

**Comment by prasannavl** [comment]
@Eilon, Thanks for the reply, but I think you missed my point. I wasn't talking about those scenarios. :) 
However, @khellang - Thanks! The use case above was just to get the idea. The overload is exactly what I was looking for. Now, I'm just confused how I missed something so blatantly obvious! :)

Thanks!

**Comment by Eilon** [comment]
Yes, indeed there's a factory version that takes in an `IServiceProvider` so you can manually resolve any required services when the service is created.

BTW please note that in RC2 we renamed `AddInstance` to `AddSingleton` for consistency: https://github.com/aspnet/DependencyInjection/issues/319

**Comment by prasannavl** [comment]
Thanks for the heads up. 

I'm still wondering if there's a way to access the services inside the `IServiceCollection.Configure<T>` - but I guess that shouldn't be necessary in most scenarios.

**Comment by Eilon** [comment]
You can't access the services from within there because they don't exist yet :smile:

**Comment by prasannavl** [comment]
Haha. That's a correct. But would be nice to get the singletons to be resolved, instead of having to go through the arduous procedure to create the service manually with all the dependencies as instances, and then use them. :)

**Comment by henkmollema** [comment]
@prasannavl, you could build an 'intermediate' container while configuring the application container:

```csharp
public void ConfigureService(IServiceCollection services)
{
	services.AddMvc();
	services.AddSingleton<SomeService>();

	var sp = services.BuildServiceProvider();

	var anotherService = sp.GetService<SomeService>();

	// ...
}
```
This uses the service provider of the internal dependency injection system. I don't really recommend this pattern, but it might help you out. You could even build an Autfac container and use that as intermediate service provider.

**Comment by prasannavl** [comment]
@henkmollema, does it not end up with 2 different ServiceProviders, each with different set of its Singletons, which wouldn't make much sense?

**Comment by henkmollema** [comment]
It does. That's why I called it an 'intermediate' service provider. I use that pattern to resolve a certain service in the scope of `ConfigureServices`. When you use it in a implementation factory like `services.AddInstance(() => new AnotherService(sp.GetService<SomeService>()));` you 'leak' it outside the scope and that may not make sense, indeed.

**Comment by Jishun** [comment]
I believe this has been addressed for a long time but it seems missing a note here
I my use case, I need to resolve an instance for the DispathProxy so that I created the IServiceProvider from IServiceCollection by `services.BuildServiceProvider();` then it ends up not in control of the same scope, the correct way is to wrap the resolving method call to later when involved by using the IServiceProvider provided by the AddScoped function as 
`serviceCollection.AddScoped((provider) => ServiceDispatcher<YourTypeInterface>.Create<YourType>(provider));`
then inside of the create method it does `YourType instance = provider.GetService<YourType>()`
