### ISSUE TITLE
Add an annoucement about the breaking changes in IServiceCollection in RC 2

### ISSUE THREAD

**Issue by TsengSR** [aspnet/DependencyInjection#331]
After getting the most recent packages from https://www.myget.org/gallery/aspnetvnext, I had some compile errors on missing `.AddInstance` method and the autocomplete wasn't very usefull in suggesting me to add the rc1 version of the library (I'm on RC2). 

Would be helpful to add this breaking changes as an annoucement in the https://github.com/aspnet/Announcements/milestones/1.0.0-rc2 issue tracker, that `.AddInstance` was renamed to `.AddSingleton`.

Took me 3/4 hour to find the commit where this change was mentioned :)

**Comment by pranavkm** [comment]
Sorry about that. I'll add an announcement post.

**Comment by pranavkm** [comment]
Created: https://github.com/aspnet/Announcements/issues/119
