### ISSUE TITLE
How to dispose top-level IServiceProvider

### ISSUE THREAD

**Issue by khellang** [aspnet/DependencyInjection#338]
Since `IServiceProvider` doesn't implement `IDisposable`, and `ServiceProvider` (which _does_ implement it) is internal, how are you supposed to dispose a "top-level service provider", i.e. the result of calling `IServiceCollection.BuildServiceProvider()`?

I could of course do a `(provider as IDisposable)?.Dispose()`, but it would be nicer if the interface implemented `IDisposable`. That way it would work better with generic constraints etc.

I understand that there's little to do with the interface itself, since it's an old interface that's been reused, but would it be possible to add a separate one?

Something along the lines of

``` csharp
namespace Microsoft.Extensions.DependencyInjection
{
    public interface IServiceProvider : System.IServiceProvider, IDisposable { }
}
```

I _think_ I've gotten around the problem by immediately creating a scope, which is disposable, and use its provider, but I don't think it's a good solution.

What was the reasoning for using the existing interface? And why is everything internal? :stuck_out_tongue_closed_eyes:

**Comment by Eilon** [comment]
Moving this to Backlog as we are not planning to make any changes for this at this time.

**Comment by khellang** [comment]
What about an answer and close it instead?

**Comment by davidfowl** [comment]
https://github.com/aspnet/Mvc/issues/3726#issuecomment-163535556

Nope :smile:

**Comment by khellang** [comment]
I don't get it. Is that the answer? How does that relate to this?

I don't really care about the interface, but there has to be some way to get a hold of the concrete type to call dispose on it, without resorting to casting etc.?

**Comment by Eilon** [comment]
Yeah not sure what @davidfowl is talking about there...

But the answer for now is that unfortunately we don't have a good answer on this. I think creating a scope immediately is an acceptable workaround in the meantime. This is certainly something we can reconsider.

**Comment by davidfowl** [comment]
We'd have to expose the concrete type (which we were trying to avoid) from BuildServiceProvider

**Comment by davidfowl** [comment]
@Eilon we *can* consider this for 2.0. Make a breaking change to the return value of BuildServiceProvider and make the internal `ServiceProvider` public.

**Comment by Eilon** [comment]
Let's do another fun DI triage 😄
