### ISSUE TITLE
Service added with AddScoped does not retain values throughout the Request Lifecycle

### ISSUE THREAD

**Issue by AlexChesser** [aspnet/DependencyInjection#342]
While this may very well be a misunderstanding on my part, I'm finding that AddScoped is not behaving as expected.

I've detailed the question over on stackoverflow:  http://stackoverflow.com/questions/34388790/addscoped-service-is-not-retaining-settings-throughout-the-request And created a standalone project on GitHub which should serve as an isolated runable project that deominstrates the issue: https://github.com/AlexChesser/AspnetIdentitySample

The summary is that I add a simple service during startup with `services.AddScoped` and later inject that into first middleware and later controllers. 

Properties set during middleware are null when accessed from the controllers.

**Comment by AlexChesser** [comment]
Per the discussion and accepted answer on StackOverflow there was a PEBKAC issue.

MiddleWare is apparently only instantiated once for the entire lifecycle of the project and as such, scoped services can't be injected. 

Drawing in the `httpContext.RequestServices` (`IserviceProvider`) object will allow you to resolve scoped services during middleware.

**Comment by davidfowl** [comment]
@AlexChesser If you're writing custom middleware, you can also take services in your Invoke method (if you use the middleware template).

**Comment by AlexChesser** [comment]
@davidfowl  wow! that's so much cleaner https://github.com/AlexChesser/AspnetIdentitySample/commit/25b010a5ae45678c137b2ad05c53ccd659a29101 thanks for that.
