### ISSUE TITLE
Enhancement Dependency Inject should support "Pooled" Scope

### ISSUE THREAD

**Issue by matlus** [aspnet/DependencyInjection#343]
This requirement may be unique to ASP.NET applications only and not to general DI frameworks but I feel we should have this feature.

In earlier versions of ASP.NET the HttpApplication was pooled (tied to threads pooled by IIS or W3Wp.exe). I've used this "feature" since ASP.NET 1.1 to pool objects to gain a huge performance edge as well as not having to deal with GC related issues and glitches. This has been confirmed and demonstrated using load and stress tests in pretty much every job I've had.

Essentially (and indirectly) all classes my applications uses (except to transient classes such as models input/output of course) were being pooled (lazy loaded but pooled). Yes, I understand that pool classes      need to be stateless etc. but that's never been an issue for me.

In old ASP.NET I'd simply create an instance of my primary facade class in Global (override the init() method) and define a public property in Global to hold a reference to it. Pages, Controllers and Handlers would simply grab the reference to this class from HttpContext.Current.ApplicationInstance

Since each request came on one of the pooled threads and I always had a valid instance of my "application" tied to this thread, stuff in my Pages, Controllers and Handlers, just worked. Even with Handlers being set to Reuse = true, no issues (since all classes in the main application are stateless).

Now, I've got a similar capability working in ASP.NET 5 but I had to do all of the lifting myself. I'd really love a AddPooled() method that takes a "Factory" method or class as a parameter. That would be awesome!

**Comment by davidfowl** [comment]
I'm not even sure how AddPooled makes sense. Why would that be a part of dependency injection? It sounds like you're looking for some hooks related to the request pipeline (or something else?). We also have other containers that support this abstraction and I dunno how this method could make any sense over there.

File this on something like aspnet/Home with more details about what specifically you are trying to pool. We've added things like this (not built into the framework) via factories (https://github.com/aspnet/HttpAbstractions/blob/lodejard/featurereferences/samples/SampleApp/PooledHttpContextFactory.cs). DI isn't the right place for it.

**Comment by davidfowl** [comment]
FWIW, you can already register a transient delegate that will get resolved every time you access the service you're trying to access. That's a cleaner way to take full control of the lifetime of the types you care about.

**Comment by matlus** [comment]
I'd like the pooled "thing" to be injected to the controllers as a "service" (at the very least). But yes, it doesn't have to be injected of course (nothing really has/needs to be injected). I figured since you have a AddInstance() method an AddPooled() would make sense (the only difference is the lifetime).

Yes, I need to way to associate something of my own to the pooled threads of the web server, just like HttpApplication in old ASP.NET.

I've seen the PooledHttpContext. That's not what I'm asking for, but thanks for the link nonetheless. I'll post a clearer message in aspnet/home.

**Comment by davidfowl** [comment]
You need to use a transient delegate to achieve this custom lifetime. I look forward to a more complete example
