### ISSUE TITLE
Is there a way to check before adding?

### ISSUE THREAD

**Issue by Fosol** [aspnet/DependencyInjection#344]
I'd like to ensure any library or middleware that make has it's own AddServices() extension method.  That way they all initialize the stuff they need to run correctly.  However I don't want to overwrite earlier configuration.

Essentially I need to know if there is a way to check if the interface or object has already been configured in the service collection?

**Comment by pranavkm** [comment]
Use the `TryAdd*` extension methods. They verify that a type of the service isn't already registered. Here's Mvc using it for its services: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L81

**Comment by henkmollema** [comment]
There is: `services.TryAdd()`. It's in the `.Extensions` namespace. It only adds it if it's not already there.

**Comment by henkmollema** [comment]
Oh @pranavkm beat me :grin:

**Comment by Fosol** [comment]
Thanks!
