### ISSUE TITLE
Proposal: Remove the need for the FromServices dependency

### ISSUE THREAD

**Issue by janpieterz** [aspnet/DependencyInjection#345]
I really like how 'clean' Autofac's property injection works. My lower libraries are never depending on any kind of dependency injection framework, they don't even know it exists. This can be done, obviously, through constructor injection but that is not always the clearest solution for all use cases.

I'd propose (pardon me if this has already been talked about) to remove the need for the FromServices attribute in the mvc controllers as well.

Even when not working with Autofac, if provided as an option, I think it would add sustainable value for the other dependency injection frameworks.

From my point of view the below screenshot (showing the three use cases) clearly shows why it would be cleaner to not have the attribute at all (there's some dupes in the screenshot purely for demo purposes).

![image](https://cloud.githubusercontent.com/assets/383634/12087889/eb57f9f2-b2d6-11e5-9769-f931abd9694e.png)

**Comment by pranavkm** [comment]
`FromServices` is an Mvc feature. You should file a bug for it in https://github.com/aspnet/Mvc
