### ISSUE TITLE
Real strange DI RC1 bug

### ISSUE THREAD

**Issue by SharpNoiZy** [aspnet/DependencyInjection#348]
Hi,

I have real strange issue with the DI system.
I use it really heavy and in general I'm very very happy with it.

But now I tried 1 week to fix somehow an issue on my solution, but I loose this fight what brings me to the thought that it have to be an bug on this lib :)

My problem is, there are 3 libs involved, including one unit testing lib, so I can not post here "5" lines of code to explain the issue ;(
It's very complex and 99 times resolving a type is working but one damn type is not resolved.

Is it maybe possible to send someone of your team a zip package with all this projects (in one solution) so that you can find the issue?

Kind regards

**Comment by davidfowl** [comment]
@SharpNoiZy Can you reproduce the bug in a smaller project?

**Comment by SharpNoiZy** [comment]
I could try to copy all source code of the different libs into one project, what would not reduce the source code :)
But the projects (except one) are very small 1-10 files because I just started this solution with .NET core. (For playing around with it)

In general you just have to debug the unit test set an break point to one position and would immediately see the issue.
For sure, I would explain everything in detail to the one that would have a look at it.

**Comment by davidfowl** [comment]
Can you remove all sensitive information from the project and put it on github? Or make a private repository and add me to it?

**Comment by SharpNoiZy** [comment]
I will do that tomorrow.
Thank you very much!

I will invite you then add an ReadMe to the project with additional information.
OK?

**Comment by SharpNoiZy** [comment]
@davidfowl I add you to my repo. Good luck to find this nasty bug.

**Comment by davidfowl** [comment]
@SharpNoiZy You have package sources that don't work. I assume those aren't important.

**Comment by SharpNoiZy** [comment]
Oh sorry, yes nothing should be used from this local sources.
Just removed them and pushed.

**Comment by davidfowl** [comment]
No good:

```
Errors in C:\dev\bugs\DITest\test\Test.MFT.Integration\project.json
    Unable to locate Dependency Common.Cryptography >= 1.0.1
Errors in C:\dev\bugs\DITest\src\MFT.Integration\project.json
    Unable to locate Dependency Common.Cryptography >= 1.0.1
```

**Comment by davidfowl** [comment]
So I can't run this code but I have a few questions:

1. Are you running tests in parallel?
2. Why are you using a static service collection in your fixture?

```
ServiceCollection services = DependencyHelper.Services;
...
DependencyHelper.Provider = services.BuildServiceProvider();
```
That looks like a disaster waiting to happen (and probably already happened).

**Comment by SharpNoiZy** [comment]
Damn it, sorry. ;(
Pushed again, removed this local dependency.

**Comment by SharpNoiZy** [comment]
Because I want to use DI inside the unit test classes and xunit does not support constructor injection on their unit test classes

**Comment by davidfowl** [comment]
@SharpNoiZy I'm like 98% sure that's your problem. Stop using statics in your unit tests. There's a better way to do this.

**Comment by SharpNoiZy** [comment]
It's not like no DI is working, just one particular case, which is the same code like two other classes which work (Like I wrote in the ReadMe).
If there is a better way to achive that I can resolve DI in the unit test classes without constructor injection I would love to learn.

**Comment by davidfowl** [comment]
@SharpNoiZy I get it but using statics like this is a recipe for disaster. Also the nature of the problem points in this direction. Just make `DependencyHelper` instance instead of static and expose that on your base class or fixture, or whatever is instantiated.

**Comment by davidfowl** [comment]
I can run now, so I'll still take a look...

**Comment by SharpNoiZy** [comment]
Thank you, you can ever commit and push what you want, this repo is just for you.

**Comment by davidfowl** [comment]
@SharpNoiZy Can you come into the jabbr room or gitter room? I have some questions.

**Comment by SharpNoiZy** [comment]
I doesn't know them, but I just created me an account on jabbr.
Which chat should I enter?

**Comment by davidfowl** [comment]
https://jabbr.net/#/rooms/AspNetCore

**Comment by SharpNoiZy** [comment]
OK, I'm in

**Comment by davidfowl** [comment]
Solved.. not a DI project :smile:
