### ISSUE TITLE
Improve assertions in Microsoft.Extensions.DependencyInjection.Specification.Tests

### ISSUE THREAD

**Issue by seesharper** [aspnet/DependencyInjection#349]
Hi!

I am in the the process of wrapping up my LightInject implementation and I thought I would mention that the assert messages could use some TLC. There are tests that does multiple asserts and then it is very difficult to determine which assert that failed. Would you be accepting a PR for this?

Basically 

```
Assert.False(someCondition, "Some description here");
```

btw. it would be nice to see this package on Nuget at least as a prerelease.  

Regards 
Bernhard Richter

**Comment by pranavkm** [comment]
We'd love to take a PR that makes the specifications easier to work with.
The package should make it to NuGet as part of the RC2 release. For the time being, you should be able to use `https://www.myget.org/f/aspnetvnext` to get it,

**Comment by Eilon** [comment]
Marking as up-for-grabs and putting in the Backlog. If we get a PR we will take a look, but we are not currently planning on implementing this ourselves.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2349
