### ISSUE TITLE
latest from dev branch does not compile

### ISSUE THREAD

**Issue by seesharper** [aspnet/DependencyInjection#350]
It looks for Microsoft.AspNetCore.Testing while the only package I could find on the aspnetcidev feed was Microsoft.AspNet.Testing. Then I got it to compile. Is this maybe related to the whole asp.net renaming going on these days? :)

**Comment by Eilon** [comment]
Yup, this is due to the renaming. As it's all a work in progress right now, I'm closing this bug because we are still cleaning up leftover bits from the rename. We recommend using the aspnetvnext feed in the meantime, which has a functional build.

**Comment by seesharper** [comment]
Thanks for your swift response :) This might be another issue, but I noticed that the Microsoft.Extensions.DependencyInjection.Specification.Tests package cannot be installed outside an ASP.NET project. Although it is compiled for Net451, there seems to be a problem with the NuGet package complaining it is unable to add a reference to System.Runtime. The reason I like to do my LightInject adapter in a "normal" class library is that there is still some stuff missing from ASP.NET projects such as support for analyzers. Anyhows, since the package is built for Net451 it should also install in a classic class library. If I extract the package and add the dll manually as a reference, it works   just as expected.

**Comment by pranavkm** [comment]
@davidfowl says it is being addressed by https://github.com/dotnet/cli/pull/1012
