### ISSUE TITLE
Question: Dynamic service registration

### ISSUE THREAD

**Issue by SebastianStehle** [aspnet/DependencyInjection#361]
Hi, 
I am playing around with a module system, inspired by https://github.com/ExtCore/ExtCore, you can find it under: https://github.com/SebastianStehle/AspNetModularity

I want to give extensions the opportunity to register custom services, but to register them I need to resolve dependencies. To be more precise I have the following interface:

    public interface IExtensionManager
    {
        IReadOnlyList<ExtensionDescriptor> LoadedExtensions { get; }
    }

To register services for all loaded extensions I have to do the following:

        public static void ConfigureExtensionsServices(this IServiceCollection services)
        {
            IServiceProvider provider = services.BuildServiceProvider();
            
            IExtensionManager extensionManager = provider.GetService<IExtensionManager>();

            foreach (var descriptor in extensionManager.LoadedExtensions)
            {
                descriptor.Extension.ConfigureServices(services, configuration);
            }
        }

This looks very ugly, but I dont know how to solve it in a better way. I also want to register services at runtime, but this does seems to be possible. What is the recommended approach for this scenarios?

**Comment by Eilon** [comment]
@lodejard @sebastienros any thoughts on this?

**Comment by lodejard** [comment]
Nice! That's probably the best way to do that, with a temporary container. The default container is immutable once build though, so you'll probably need to switch to one one that allows services to be added at runtime of you really need that capability.

**Comment by sebastienros** [comment]
In Orchard2 we register the service collection itself before the container is built, then we can resolve it, and build a third level of containers based on dynamic registration from our modules (your extensions). So we have a root container (Application) multiple tenant ones (with all the root services duplicated in them) and a scoped. At runtime we switch the Application container by the tenant one, and create a scope from it. It allows us to have different services for each request (i.e. each tenant). 

But it would be much simpler I assume with another container, like Louis is suggesting.
