### ISSUE TITLE
AddSingleton(Type, object) is missing

### ISSUE THREAD

**Issue by sebastienros** [aspnet/DependencyInjection#366]
There was an `AddInstance` with these parameters, and because I need it, I assume others will. Also confirmed with @halter73 that it should be here (but he was not really focused so it might be an oversight)

**Comment by sebastienros** [comment]
Working on a PR in anticipation it gets approved.

**Comment by sebastienros** [comment]
Well, it seems to be there and my package reference to be too old ...

**Comment by pranavkm** [comment]
This exists - https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs#L599
