### ISSUE TITLE
DI RelfectionTypeLoadException

### ISSUE THREAD

**Issue by Fosol** [aspnet/DependencyInjection#368]
Not sure if you've made this change in RC2 yet, but RC1 doesn't bother including the necessary information to debug most DI issues.  I'd like to know the type name that failed.

Retrieve the LoaderExceptions property for more information doesn't seem to be all that helpful.  I'm using the DeveloperException page too...

**Comment by davidfowl** [comment]
This is super vague. Do you have a stack trace?

**Comment by Fosol** [comment]
That is the way i felt too lol.  I should have included more info when the exception kept occuring.  It was another developers instance, so I'll have to try and reproduce.

**Comment by davidfowl** [comment]
Closing, reopen when you can repro
