### ISSUE TITLE
Codegen dependent types instead of one at a time

### ISSUE THREAD

**Issue by davidfowl** [aspnet/DependencyInjection#372]
Today calls to > 2 GetService(type) triggers compilation of an expression tree that represents the construction of the specified type. None of the related types are compiled at that point but should be. Here's an example:

```C#
public class A
{
    public A(B b)
    {
    
    }
}

public class B
{
    public B(C c)
    {

    }
}

public class C
{
    
}

public class Program
{
    public static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        sc.AddTransient<A>();
        sc.AddScoped<B>();
        sc.AddSingleton<C>();
        var sp = sc.BuildServiceProvider();
        var a = sp.GetService<A>();
    }
}
```

The expression trees look roughly like this:

```
GetService(A) =
    Transient(
      new A(
        Scoped(
            () => new B(
                Singleton(
                    () => new C()
                )
            )
        )
      )
    )

GetService(B) =
    Scoped(
        () => new B(
            Singleton(
                () => new C()
            )
        )
    )
  )

GetService(C) = 
    Singleton(
        () => new C()
    )
```

Notice B and C are contained in A's dependency graph and C is contained in B's dependency graph. Even when that's the case, each of the service lookup trigger compilation independently. It would be great if dependent types were also reference counted and compilation was triggered for the entire tree in a single go.

**Comment by halter73** [comment]
Interesting. This seems easy if we assume (probably inaccurately) that `GetService(A)` is called first or perhaps if we build the entire graph for all of our dependencies at startup. Is there an alternative to these options that I'm unaware of?

I'm a little concerned that greedily building the entire graph could negatively impact startup perf. This might not reduce the total amount of time building spent expression trees if there are enough services you never directly call `GetService` for and/or if there are enough registered services that are never resolved even indirectly. The perf hit would probably be the most pronounced if you greedily compile the expression tree for each service, but that could still be done lazily with this design.

It would be interesting to see how many compiled expression trees actually end up in the `RealizedServices` dictionary after we remove a lot of the unneeded calls to `GetService`.

h Right now our DI project tries to be very much pay-as-you-go, so I'm a little bit worried front-loading too much computation might hurt startup perf even if it's done on a background thread. Obviously, once the app is warm, there is no perf difference at all. There's no substitute to actually measuring.

**Comment by davidfowl** [comment]
> It would be interesting to see how many compiled expression trees actually end up in the RealizedServices dictionary after we remove a lot of the unneeded calls to GetService.

Yea, no action should be taken getting some data.

**Comment by Eilon** [comment]
Parking in backlog because we don't have data at this time.

**Comment by davidfowl** [comment]
@pakrym Closing this out because with the latest changes it seems like we got most of the savings. Not much can be saved by reusing parts of the expression tree (other than a few allocations).
