### ISSUE TITLE
Keep updated wiki

### ISSUE THREAD

**Issue by leolana** [aspnet/DependencyInjection#373]
Keep updated the wiki is essential to solidify the asp net DI, why is being difficult to leave the examples generated in own visual studio scaffolding or yeoman and go to a real project.

**Comment by pranavkm** [comment]
@leolana, docs for Asp.Net Core and it's components are located here - https://docs.asp.net. For instance en/latest/fundamentals/dependency-injection.html.

**Comment by Eilon** [comment]
Indeed, the docs are kept separate from the project repos.

**Comment by leolana** [comment]
Ok, thank you.
