### ISSUE TITLE
Cannot find 'Microsoft.Framework.DependencyInjection.Abstractions'

### ISSUE THREAD

**Issue by willwsharp** [aspnet/DependencyInjection#374]
Hello. I am trying to build just a sample .net 5 web API and I'm attempting to use the built-in DI container. Whenever I try to run my API though, I keep getting the error:

"Could not load file or assembly 'Microsoft.Framework.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."

I've looked through my project.json file and there's no reference to it, and I've done a search through the entire solution to see if there's a reference to it and I can't find it at all. I'm using the new Microsoft.Extensions.DependencyInjection and it seems like something in my project is using the old one even though I can't find any references to it. Could someone please help? More than happy to provide more information if necessary.

Thanks.

**Comment by davidfowl** [comment]
Can you provide a repro project (preferably pushed to github)

**Comment by willwsharp** [comment]
Yup sure will.  Working on that now.

**Comment by willwsharp** [comment]
Here is the link: https://github.com/willwsharp/aspnet-Issue-374

**Comment by davidfowl** [comment]
What version of DNX are you using?

**Comment by willwsharp** [comment]
Apologies ahead of time but I'm fairly new to .net 5; in my project.json it says "DNX451 under "frameworks", is that what you're looking for?

**Comment by davidfowl** [comment]
Here's your problem https://github.com/willwsharp/aspnet-Issue-374/blob/master/CloudBasedAPITest/src/CloudBasedAPITest/project.json#L10, using beta7 mixed with your rc1-final packages. 

If you're upgrading, I'd recommend making a new project and copying over dependencies.

**Comment by pranavkm** [comment]
You'd have to update to using Kestrel \ IISPlatformHandler  - https://github.com/aspnet/ServerTests/blob/dev/test/ServerComparison.TestSites/project.json#L4-L5

**Comment by willwsharp** [comment]
Can you explain in more detail please?  I was using the beta4 I change it to beta7 and I was having the same problem.

**Comment by davidfowl** [comment]
Install the latest tools and runtime from http://get.asp.net. Make a new project, copy your old projects contents over (you need to port a the code because of API changes)

**Comment by willwsharp** [comment]
Okay thanks I will do that.
