### ISSUE TITLE
Should it be possible to add primitive types?

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/DependencyInjection#382]
Hi! [There's a unit test](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs#L504) that adds a primitive type as a singleton to the collection: 
```csharp
collection.AddSingleton("Hello World");
```
Should this really be possible? What would be a usage scenario for this? 

Castle Windsor for example [doesn't support it](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/Core/ComponentModel.cs#L376).

**Comment by davidfowl** [comment]
There's no scenario and I'm not sure why the test has it but we don't go out of our way to make it fail

**Comment by cwe1ss** [comment]
Ok. Could you change this test? Castle Windsor throws an exception and I guess others might do so as well. And since this is not the purpose of that test, other containers shouldn't fail for such a reason IMO.

**Comment by cwe1ss** [comment]
Maybe this line can just be removed? The test has a different purpose anyways.

**Comment by pranavkm** [comment]
I think it's meant for the generic service to close over. We could replace it with a non-primitive type instead.

**Comment by davidfowl** [comment]
Let's do that.
