### ISSUE TITLE
InvalidOperation Exception: A circular dependency was detected for the service of type message is received when injecting class that depends on IAuthorizationService in a AuthorizationHandler

### ISSUE THREAD

**Issue by djjlewis** [aspnet/DependencyInjection#389]
Hi,

I'm not sure of the best place to put this issue i.e. in here or aspnet/security, but the issue is hopefully fairly straightforward to explain:

I have an ASP.NET website using the RC1 bits and I have a service class "ResourceService" that takes an IAuthorizationService as a dependency in the constructor, as one of the methods needs to use AuthorizeAsync on the resource to check if the current user can create the resource.

The ResourceAuthorizationHander class I have created depends on another service, UserService, that does a check to an external DB to check certain permissions for the user. The UserService also takes a dependency on IAuthorizationService as it needs to do its own separate authorization checks in some 
instances.

The services are being registered in ConfigureServices as follows:

```csharp 
services.AddScoped<IUserService, UserService>();
services.AddScoped<IResourceService, ResourceService>();
```
```csharp
services.AddTransient<IAuthorizationHandler, UserAuthorizationHandler>();
services.AddTransient<IAuthorizationHandler, ResourceAuthorizationHandler>();
```

The dependency chain very simply is something like this:

```csharp
public class ResourceService
{
ResourceService(ILogger<ResourceService> logger, IAuthorizationService authService) {}
}

public class UserService
{
UserService(ILogger<UserService> logger, IAuthorizationService authService) {}
}

public class ResourceAuthorizationHandler: AuthorizationHandler<OperationAuthorizationRequirement, Resource>
{
ResourceAuthorizationHandler(ILogger<ResourceAuthorizationHandler> logger, IUserService userService) {}
}
```

When I try to make the call to the AuthorizationService.AuthorizeAsync method in the ResourceService I get the following exception:

System.InvalidOperationException: A circular dependency was detected for the service of type 'Microsoft.AspNet.Authorization.IAuthorizationService'.

I appreciate I could probably refactor the classes so that any services injected into an AuthorizationHandler do not themselves depend on an IAuthorizationService, but in my case I can see that many services will depend on this in the same way you want most classes to take an ILogger for example i.e. checking auth seems like a reasonably common thing to do.

Interestingly, injecting an ILogger seems fine, even though the ILogger is a dependency of both the AuthHandler and the Services, but could this be because it is actually seen as a different dependency due to the ILogger<T> generic parameter?

Is this issue just surfacing out of a fundamentally bad design (as stated above), or is there some way I can tell the DI system about the circular dependency or some other option, or perhaps this behaviour has changed since RC1 (I haven't been able to test unfortunately).

Regards,

Dan.

**Comment by pranavkm** [comment]
The constructor of `DefaultAuthorizationService` lazy loads `IEnumerable<IAuthorizationHandler>` instances from the DI container. In your case, the `ResourceAuthorizationHandler` attempts to transitively DI in the `DefaultAuthorizationService` which is what's causing the cyclic check to kick in. It'd be useful to ask a question in the Security repo to figure out how you could refactor your code where `UserService` \ `ResourceService` don't require it or have some way to flow the `IAuthorizationService` to handlers when `AuthorizeAsync` is invoked.

**Comment by djjlewis** [comment]
Many thanks for the quick response. As suggested I will ask over at /security for further advice...

**Comment by Eilon** [comment]
Closing because it seems this issue isn't a DI issue.

**Comment by guillerglez88** [comment]
As a workaround you can require `IServiceProvider` from constructor instead, and resolve the service just before calling `AuthorizeAsync`, that worked for me.

**Comment by mihirdilip** [comment]
Hi Dan (@djjlewis )

Apologies for replying to an year old thread.

I am have same issue as you were. One service referencing IAuthorizationService call other service referencing IAuthorizationService. 

Did you ever resolved this issue. What was your solution? Any help with this will be highly appreciated.

Thanks,
Mihir
