### ISSUE TITLE
How to export project (asp.net core libray) to UAP10

### ISSUE THREAD

**Issue by endink** [aspnet/DependencyInjection#390]
try to use:

```javascript
 "netstandard1.5": {
   "imports": [
     "dotnet5.6",
     "portable-net45+win8",
     "uap10.0" 
   ],
   "dependencies": {
     "System.Net.Http": "4.0.1-rc2-23826"
   }
 }
 ```

 after built, it cant add to UAP project, how to reuse my code ? Is there a document for "imports" section in project.json, thanks!

**Comment by Eilon** [comment]
@bricelam any chance you know the magical incantation for this to work? Or does it not work right now?

**Comment by bricelam** [comment]
Imports only affect how dependencies are resolved for *this* `project.json`.

To use a `netstandard` package with UWP, you'll need updated UWP tooling. There are currently a few bugs (see aspnet/EntityFramework#4802), but as far as I know, the updated tooling will ship as part of [Visual Studio 2015 Update 2](https://www.visualstudio.com/en-us/downloads/update2-prereleases).

**Comment by davidfowl** [comment]
Is this a dependency injection question?

**Comment by endink** [comment]
@davidfowl i want to use dependency injection to UWP (adapter for Prism Library DI).

**Comment by davidfowl** [comment]
It wasn't clear from the `project.json`. You'll need to wait for the nuget vsix update.

**Comment by emgarten** [comment]
@endink if the project above creates a nupkg it should not use imports. Imports should only be used as a workaround for top level projects (apps) which will not be used to create nupkgs.

To create a nupkg that works for UAP the project framework should be uap10.0.

**Comment by Eilon** [comment]
It seems the question here was answered, so closing. If there is still an issue, please log a new issue with any additional information about the environment, what was tried, updated project.json files, etc. Thanks!
