### ISSUE TITLE
Consider implementing equality on ServiceDescriptor

### ISSUE THREAD

**Issue by javiercn** [aspnet/DependencyInjection#391]
ServiceDescriptor is basically a data object, but it doesn't implement equality. That causes troubles when you are manipulating a service collection, for example, when you want to remove a descriptor. With equality, code like:

```C#
var descriptor = _services
    .FirstOrDefault(f => f.ServiceType == type && f.ImplementationType == implementation &&
    f.Lifetime == ServiceLifetime.Transient);

if (descriptor != null)
{
    _services.Remove(descriptor);
}
```
can simply be written as

``` C#
_services.Remove(ServiceDescriptor.Transient(type, implementation);
```

**Comment by Eilon** [comment]
I doubt this is really doable because service descriptors can include factories - how do you compare the equality of them? (Yes, you *can* compare equality of functions, but that's usually meaningless when there might be two delegates pointing to the same function.)

**Comment by Eilon** [comment]
No plans to implement this because it's unlikely to be possible.
