### ISSUE TITLE
Ability to register required services on ServiceCollections which BuildServiceProvider Validates

### ISSUE THREAD

**Issue by wesleyolis** [aspnet/DependencyInjection#393]
# Issue

When registering a module internal services, one would except, to have the ability to register all external required dependent services that are to be present as well. Upon failing that contract for required services and exception would be thrown when building the container(BuildServiceProvider).

# Suggestions

The ability to register a list of dependent services, upon which a module depends,
when install/registering that modules internal services. Such that when BuildServiceProvider is called
all required service are ensured to be present, otherwise an exception is throw, providing a list of all the required dependencies upfront and not at run time in

# Reproduction

```csharp

//Module A
static class ModuleA
{
 static public InstallModuleA( this IServiceCollection services)
 {
services.AddRequiredSingleton(Settings); // This method doesn't currently exist.
services.AddRequiredSingleton(B); // This method doesn't currently exist.
services.AddSingleton(A);
 }
}

public class A {
  public A(B b) {
  }
}

public class Executor
{
 public Executor(Settings ISettings)
 {

 }
}
interface ISettings
{
}


// Module B
public class B {

}

public class ModuleBSettings : ISettings
{
}
public class Execute
{
 public void Execute()
 {
 var services = new ServiceCollection();

 services.InstallModuleA()
 //services.AddTransient(ModuleBSettings );  // Missing this line should cause exception to be thrown    as indicated below.
 //services.AddTransient(B);  // Missing this line should cause exception to be thrown as indicated below.

 services.BuildServiceProvider(); // Would except that an exception be throw here for the other  required services yet to be registered for moduleA to be executed successfully at run-time.
 }
}

```

/cc @spartan563

**Comment by Eilon** [comment]
Is this different from https://github.com/aspnet/DependencyInjection/issues/392?

**Comment by SPARTAN563** [comment]
I believe the intention with this issue was that you may register a service which depends on you implementing certain interfaces. With the understanding that #392 may not be possible at the moment (since dependencies are only checked when a service is first resolved) @wesleyolis was looking for a way to enforce the requirement that those services be registered with the DI container before it would be permitted to build. 

Overall I think this is primarily a "Nice to have" and only satisfies a limited set of use cases, however it can certainly help in cases where Strategy/Template is applied across a large codebase. We've managed to work around it by emphasising the usage of constructor injection through extensions like #394 and attempting to load all top level services as part of the application bootstrapping process.

**Comment by khellang** [comment]
After reading through this a couple of times, I think I finally understand what you're after here.

You want to somehow tell the service collection that you expect a set of services to be registered, otherwise it should throw when building the provider?

Something like this?

```csharp
public interface ISettings { }

public interface IDatabase { }
public class Database : IDatabase {
    public Database(ISettings settings) { }
}

public interface IUserService { }
public class UserService : IUserService {
    public UserService(IDatabase database) { }
}

public static class ServiceCollectionExtensions {
    public static void AddUserService(this IServiceCollection services) {
        services.RequireScoped<IDatabase>(); // UserService requires IDatabase
        services.AddTransient<IUserService, UserService>();
    }

    public static void AddDatabase(this IServiceCollection services) {
        services.RequireSingleton<ISettings>(); // Database requires ISettings
        services.AddScoped<IDatabase, Database>();
    }
}

public static class Program {
    public static void Main() {
        var services = new ServiceCollection();

        services.AddUserService();
        services.AddDatabase();

        // The following should throw because ISettings hasn't been registered.
        var provider = services.BuildServiceProvider();
    }
}
```

This sounds totally upside down _and_ redundant. You already have the information about required dependencies from the set of registered services. Why not just let the services control which services they require like they do today?

**Comment by SPARTAN563** [comment]
@wesleyolis - would you like to hop in here to motivate why (given the above and the fact that dependency information is, in most cases, available at resolution time for a service) you feel this is necessary?

From what I recall, this was related to the use of `GetRequiredService` and `GetService` within logical scopes - cases where these services wouldn't necessarily be mentioned in a constructor's arguments and therefore the information about those dependencies wouldn't be available to the DI framework. I believe @wesleyolis was looking for a way to avoid dependency resolution failures "late" in the application's lifecycle, pushing them to the setup phase instead.

**Comment by khellang** [comment]
> I believe @wesleyolis was looking for a way to avoid dependency resolution failures "late" in the application's lifecycle, pushing them to the setup phase instead.

This is something you can easily build on top of the provider. You just have to keep a list of services, enumerate through them and call `GetRequiredService`. If you encounter a service that fails to resolve, you have a problem.

Now, of course this is costly, because you're effectively "warming up" the container by creating an instance of every required service, but I believe this is the best way to do it. AFAIK, this is also how containers like StructureMap does it when verifying a container configuration.

There are also other alternatives to this API, which you could layer on top. You could keep the same list of required services and before building the provider, you could enumerate through the set of service descriptors and verify that all services are present. This would be less costly, but wouldn't guarantee that all dependencies are there.

**Comment by wesleyolis** [comment]
@khellang

I agree with you that the post #392 does deal with the issues , regarding upfront
validation of all the services dependencies can be resolved.

My post was clearly not explicit enough, about the issues I was trying to raised.
So let me explain the problem I felt could arise and potential solutions.

# Issues
When registering a service with IServiceCollections, their is no ability to constraint the 
the registered service interface, to a specific service lifetime.

From external perspective, with out domain intrinsic knowledge about implementation details or design decisions, one can register the service with any service lifetime, however, from the internal
perspective having former knowledge, certain assumptions maybe made or arise due framework
upon which one is dependent.

The following example should highlight the issues.

The developer writes a class A that will be registered as a transient, that requires a service B using constructor injection, which is assumed to be registered as a singleton(domain/intrinsic).

What can go wrong:

1.  Assuming the external services B is a very heavy class to instantiate.
-  Registering the service B as transient instead of Singleton, the instantiate of class A will experience degraded performance, with service B having to be re-instantiated with every repetitive instantiate of class A.

2. Parallelization may require certain behavior constraints to be imposed due to factors such as;  non-shared memory support of a class; non-thread safe class/code.
- The program could potentially crash very late in the pipeline stages, by miss match between how the services was used versus intended use. 


3. Async Tasks, may also require certain behavior constraints to be imposed due to factors such as:
- class or library, only supporting a single instance run due to their design limitations and is required the be newed for every run with some form of new context.
- The program could potentially crash very late in the pipeline stages, by miss match between how the services was used versus intended use, or even run with undersized side effects, or produce corrupt output.

# High level cause of the problem:

All of this results from the lack of the ability to communicate clearly with one another the intrinsic of the mechanisms in play. That being the usage limitation between how it was intend to be used versus how it was used in reality.

# Suggestions

Their are a couple of way to address the issues, however, its merely shifting the responsibility
around the application and each come with their pros and cons.

Allow dependence injection to specify the constraints for the lifetimes and registrations options
at a top level. That is where the suggested new members be added RequiredSingleton, RequiredTransient, RequiredScoped, RequiredInstance, come into play.
The Required functions above would the have allow the BuildServiceProvider() to validate the or implicitly correct the service lifetime required.
This comes with the con that all service and modules in different projects which would require different service lifetime, couldn't be met.
Think about this now again, I don't think this is right approach!
It is a blanket solution to the problem, putting everything into a single box.

The other approach is a design guideline, in which one should always assume that all service may be registered with a transient service lifetime, which would provide the worst performance.
Developers should then code with this mind set, shift the responsibility.
The developer would then be responsibility for internal caching the injected service, for performance benefit.

This still doesn't solve the issues for parallelization and async tasks,
in which it is a requirement for the service to be registered as a transient for the above mentioned reasons.
One could adopted the approach as in #394 as illustrated below.

``` csharpe
IThreadTypeFactory<TInstance> : IFactory<TInstance>
where TInstance : IThreadSafe 

// IThreadSafe is an interface in which the developer coded the class with the intention of being thread safe.
// Potentially later csharpe language could explaned on, with the ability of communicate threadsafe classes and methods.
// or class that require a new instance, due to limitation of their classes design.
interface IThreadSafe 
{			
}
```
Which would provide all the granularity and communicate explicitly the intended requires the class was to meet.

Maybe an extensions method could be added to the dependence frame work that 
provides convenient function wrapper for the functionality.

It would also imposed structured and formal convention that everyone across the community could adopted, apposed to it being a weak design guideline.

**Comment by khellang** [comment]
TBH, this sounds like way too much/complex functionality for this simple container implementation to prevent devs from shooting themselves in the foot with captive dependencies etc.

AFAIK, the goal of this lightweight implementation has always been for the framework to be able to utilize simple constructor DI. If you, from a user POV, need heavier and more complex functionality, there are literally _tons_ of other containers to choose from in the .NET space. Many of which implement this, and much more. Writing an adapter isn't that hard. I maintain the StructureMap.Dnx adapter myself, I know.

Let's hear what the MS folks has to say, but for me, this sounds like too much.

**Comment by wesleyolis** [comment]
Basically just a way to prevent those corner cases, that may have been looked over.
Typically using EF and ReactiveX, which makes threading async task really simple for pipeline work,
These would have been the issues that one would run into.

**Comment by wesleyolis** [comment]
Realizing the modularity that one wants dependence injection to meet, by allowing may different projects to be integrated and library instance to be re-used, with different service life times behaviors.

I would look at changing the way in which services life times are interpreted with dependence injection.

# Issue

As discussed in the posts above classes and implementations interfaces are registered
each with a specific service life time behavior, using a top down/blanket approach.
Which prevents any different project; sections of projects; re-use/multiple instance of library/components to have different behavior service life times or finer granularity of control.

# Suggestions

Change the service life time behavioral interpretation into service life time compatibility
level that a class or interfaces meets. 

Define the service life time compatibility level as a numerical value, were a value 0 is the most
restrictive service life time (instance) and a higher value supporting all other modes of specified by lower values.

Envisage service life times level to be as follows for example:

Instance  = 10,
Singleton = 20,
Scoped = 30,
Transient = 50,
ThreadSafe = 60.

Class and interface are then registered potentially in a few ways:

- In the same manor as currently done, AddSingleton, AddTransient.
- Inheritance of an empty interface, DIInstance, DISingleton,
  however,  this approach could become cumbersome for existing library components, which all
  require re-wrapping of classes.
- CustomAttribute for classes and interfaces.
- Since the above defines ServiceLifetime in terms of a numerical level, it would
  probably be better to define a generic interface DIService<ServiceLifeTimeLevelSupported>
  where ServiceLifeTimeLevelSupported : int

A generic AddService would need to be implemented, such that manual instantiation of service could still be realized, which overloads of AddSingleton/AddTransient previously provided.


# Requesting a service with specific life time behavior. 

When requesting services to be injected one would then
using annotations or generic abstract class that would dictate the service life time level
requirement, by vertue implicitly implies the service life behavior wanted.
This would be similar to the IFactory approach in #394.

Implemented with an abstract class of IFactory with implicit conversion operator
that would return the underlying wrap class, call it DIFactory<ServiceLifeTime, OptionalNamedScoped>.


# Optional Named Scope concept

This concept, however, implemented through CustomAttribute or as above,
would allow for specific named scoped instance to be shared instead of a single global scope.
I would envisage different named scope to exist for:
- Different projects
- Multiple Named Instance of components with in the same project or containing component.
- Multiple Named instance of Libary components

The generic AddService that is required for manual instantiation would be required to support
the concept of OptionalNameScoped.

# Validation of the availability of all services

All the services that have been registered with IServiceCollections
should be validated that they can be instantiated upon calling
BuildServiceProvider() as discussed already in post #392

# Conclusion

I hope that his provides an alternative perspective of the envisage different use cases of Dependence Injection, service life time behavior component.

**Comment by davidfowl** [comment]
Just FYI, I'm on the same page as @khellang here. You should use another container that provides these guarantees/features. We have no plans to add it to this container. 

You can easily extend (or fork) the current container implementation to add this if you need it.

**Comment by wesleyolis** [comment]
@davidfowl 

What is the point of Microsoft being a being a massive corporation, implementing their own versions
of DI, if they not going to better or improve on what is current available in the world.

From an outside perspective would you not see this as a waist of man-hours and time,
that could have potentially been spent more wisely on other priorities.
Since we could have just as well used other open source DI frameworks from the start.

**Comment by davidfowl** [comment]
> What is the point of Microsoft being a being a massive corporation, implementing their own versions
of DI, if they not going to better or improve on what is current available in the world.

We actually aimed to solve something very specific with this DI container as @khellang mentioned earlier https://github.com/aspnet/DependencyInjection/issues/393#issuecomment-213371374. This serves as a lowest common denominator style DI container to enable our own ASP.NET libraries the ability to use a DI container while still allowing any 3rd party container to swap out our default implementation.

We want to keep this thing very minimal and low on features (and fast). Being able to swap out this container implementation with another was actually one of the *main* goals of this thing existing.

> From an outside perspective would you not see this as a waist of man-hours and time,
that could have potentially been spent more wisely on other priorities.
Since we could have just as well used other open source DI frameworks from the start.

We'd actually encourage you to use other DI containers because they have more features.

**Comment by Eilon** [comment]
Per the comments from @khellang and @davidfowl , I am closing this. The ideas here are good, we just don't think they fit the model of this container.
