### ISSUE TITLE
An unhandled exception has occurred: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.

### ISSUE THREAD

**Issue by xatabhk** [aspnet/DependencyInjection#395]
"dotnet run" returns error:
![json_err](https://cloud.githubusercontent.com/assets/6814395/14059821/48305c0c-f38a-11e5-92f9-af6572ab080f.png)

while "dnx web" works.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Mvc/issues/4349.
