### ISSUE TITLE
[Dependency Injection] How can I get IServiceProvider outside controller ?

### ISSUE THREAD

**Issue by GregH44** [aspnet/DependencyInjection#396]
Hi everyone,

I try to work with native dependency injection of ASP.NET Core 1.0. I work with rc1 update 1 version.

I have an n-tiers application. I would like to get IServiceProvider into DataLayer to obtain my DbContext by service with AddTransient.

Many examples show how to get my DbContext with my controllers like this :

`public MyController(IDbContext dbContext) { }`

This exemple works very well. But I don't want to use this method because I have to pass my DbContext through my layers.

My question is : How can I get IServiceProvider outside ASP.NET Core scope ?

Thank you for your help.

Greg

**Comment by davidfowl** [comment]
There is no static service provider if that's what you're asking for. I'm not sure what you're asking for actually. Can you clarify with a sample?

**Comment by GregH44** [comment]
Hi David,
Thank you for your answer.

In my Startup.cs, I have this code into ConfigureServices method :
`public void ConfigureServices(IServiceCollection services)
{
  services.AddMvc();
  services.AddInstance<IConfigurationRoot>(Configuration);
  services.AddTransient<IMyDbContext, MyDbContext>();
}`

I add my DbContext with AddTransient because I want one DbContext per request.
But in my code, I don't want to use controllers like this :
`public class MyController : Controller
{
  private IConfigurationRoot configuration;

  public MyController(IConfigurationRoot configuration)
  {
    this.configuration = configuration;
  }
}`

Because my controller create new instance of service and service create new instance of repository which use MyDbContext. With this controller, I have to pass "configuration" through my layers until Repository.
To avoid this case, I would like to get IServiceProvider directly into Repository.

How can I do this ?
Can I use another DI/IoC like Unity, simple injector or autofac ? If yes, do you know a simple implementation ?

Thank you for your help.

Greg

**Comment by davidfowl** [comment]
You should look at options https://docs.asp.net/en/latest/fundamentals/configuration.html?highlight=options#using-options-and-configuration-objects to flow things from configuration into your repository. You don't need the `IServiceProvider` even though it does flow through the container so you can get it in the ctor of your repository. You shouldn't need it in this case though.

**Comment by GregH44** [comment]
I read the options documentation but I'm not sure this is what I want.
I would create my DbContext per request with AddTransient.
My objective is to share my DbContext with several repository without pass the DbContext in parameter of the constructor.

**Comment by seesharper** [comment]
That is what dependency injection is all about. If your repository is dependant upon a DbContext instance,  it should be passed into the constructor of the repository.

**Comment by weitzhandler** [comment]
> I read the options documentation but I'm not sure this is what I want.
> I would create my DbContext per request with AddTransient.
> My objective is to share my DbContext with several repository without pass the DbContext in parameter of the constructor.

You should use `AddScoped` to create your context so it uses the same context within the HttpRequest scope. `AddTransient` creates a different context each time you request it from the service provider.
