### ISSUE TITLE
Base Class Dependency Injection

### ISSUE THREAD

**Issue by eriksendc** [aspnet/DependencyInjection#398]
Hi All,

I've got a controller class that extends Controller that is then the base class for all Web API and MVC controllers in my ASP.NET 5/Core app. Is there a proper pattern of defining a constructor in my base class that then would chain in by base controller's constructor so that DI would occur for my base controller? I guess I was hoping that my derived classes wouldn't have to know they needed to call their base class's constructor and pass in a service. I want the base class to be able to get it's dependencies all by itself.

Right now I'm using `HttpContext.RequestServices.GetService(/*service type*/)` inside of any particular method of the base class that needs a particular service. But I'd rather do this in the constructor of the base class somehow.

Any thoughts?

Thanks,
-Brian Eriksen

**Comment by pranavkm** [comment]
If you use the built in DI system, you'd have to use constructor injection in the derived class and pass it into the base class

```C#
public BaseController(IFirstService service1, ISecondService service2)
{

}

public DerivedController(IFirstService service1, ISecondService service2): base(service1, service2)
```

Alternatively you could use a [third party DI container](https://github.com/aspnet/DependencyInjection#using-other-containers-with-microsoftextensionsdependencyinjection) that supports property injection so your derived controller's constructors wouldn't have to pass the values in. Calling `RequestServices.GetService` is considered a DI anti pattern and I would recommend using one of the alternatives suggested above.

**Comment by eriksendc** [comment]
Ok. Thanks!
