### ISSUE TITLE
Is there any reason not to use an Enum to represent the lifetime of a service?

### ISSUE THREAD

**Issue by lewischeng-ms** [aspnet/DependencyInjection#400]
Hi I am from OData team. We are currently working on integration of the MS DI framework into our library. I've got a naive question here: 

In https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs, you implemented all kinds of overloads for all kinds of different lifetimes (Singleton, Scoped, Transient). Is there any reason not to use an Enum to represent the lifetime of a service? Otherwise the number of overloads would be much smaller.

I am not trying to make any suggestion or proposal here. I am just curious about if there is any special concern for this design. Your explanation would be much appreciated. Thanks!

**Comment by davidfowl** [comment]
There is an enum https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceLifetime.cs. The extension methods are for authoring convenience:

```C#
services.Add(new ServiceDescriptor(typeof(IFoo), typeof(Foo), ServiceLifetime.Scoped));
```

VS

```C#
services.AddScoped<IFoo, Foo>();
```

**Comment by lewischeng-ms** [comment]
@davidfowl Got it. Thanks very much!
