### ISSUE TITLE
AddSingleton is swallowing exceptions silently

### ISSUE THREAD

**Issue by colemickens** [aspnet/DependencyInjection#401]
```
services.AddSingleton<IDatabase>((IServiceCollection) => configureRedis());
```

configureRedis() is throwing an exception. I know because I catch it, print the exception and then rethrow it. It seems that AddSingleton or something down the stack is swallowing the exception. As a user, I didn't know until I was informed that `Could not resolve a service of type 'StackExchange.Redis.IDatabase' for the parameter....`.

Not sure if this is standard for DI or a bug or something else?

**Comment by nil4** [comment]
Could be related to aspnet/Hosting#695

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Tooling/issues/363.

**Comment by colemickens** [comment]
@pranavkm Can you give more details? That bug was labeled "fixed" nearly two months ago yet I'm experiencing this will the latest dotnet builds.

**Comment by davidfowl** [comment]
@colemickens repro?

**Comment by colemickens** [comment]
This commit shows what I'm seeing at least, on top of the `cli-samples` repo:

https://github.com/colemickens/cli-samples/commit/cd7152784ab98645b7ce76ff8e9fa9ca364f7281

```
Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:06.1246725
 

Unhandled Exception: System.Exception: Could not resolve a service of type 'HelloMvcApi.IFoo' for the parameter 'foo' of method 'Configure' on type 'HelloMvcApi.Startup'.
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at HelloMvcApi.Program.Main(String[] args)
```

So, it gets to ConfigureServices and complains there's no `IFoo`, but it didn't complain about the uncaught exception in `makeFoo`. But maybe I'm misunderstanding the expected behavior...

**Comment by colemickens** [comment]
David got me sorted out in Jabbr. I'm still seeing this because I'm using the ci release nuget feed. Thanks all.

**Comment by colemickens** [comment]
AFAICT this is still happening...
