### ISSUE TITLE
DI of Collection of Services 

### ISSUE THREAD

**Issue by drobertson123** [aspnet/DependencyInjection#404]
I am not sure if this is a request or a how-to question.

My issue is that several of my services require a collection of sub-services to be injected. This collection of services represents standardized interfaces to different data stores. Each would conform to a standard interface, but would also have their own concrete implementation and if needed specific interface.

At the point of configuration, I need to be able to define what specific implementations get added to the collection or Configuration object that will be passed to the Service ctor. I can set these in the configuration easily enough, but I can't seem to figure out a way to get the DI system to add them to the specific service. 

At this point, I have been exploring registering each specific sub service and then retrieving them based on a list of types sent through the Service ctor. This requires me to pass in the HttpContextAccessor and use RequestServices.GetService() internal to my Service class. I understand this is considered a bad practice and would like a better alternative.

My next step was to attempt to localize the RequestServices.GetService() request to inside the configuration object. Effectively I would turn the configuration object intoan object factory that would hand the service the apropriate sub services,  but I can't see how to get access to the current HttpContextAccessor from that location.

This is extremely critical to my project. Is this in any way possible and if so what am I missing? If it isn't currently possible could this be a feature of the DI system? If it is never going to be possible within the DI system do you have a suggestion for how to make this happen with outside tools?

**Comment by pranavkm** [comment]
> At the point of configuration, I need to be able to define what specific implementations get added to the collection or Configuration object that will be passed to the Service ctor. I can set these in the configuration easily enough, but I can't seem to figure out a way to get the DI system to add them to the specific service.

Could you elaborate on this, perhaps with an example?

> but I can't see how to get access to the current HttpContextAccessor from that location.
`IServiceProvider` will get injected into services by default. You don't have to pass around the `HttpContextAccessor` to get to it.

> If it is never going to be possible within the DI system do you have a suggestion for how to make this happen with outside tools?
Our DI registration is compatible with partner service provider. See https://github.com/aspnet/DependencyInjection#using-other-containers-with-microsoftextensionsdependencyinjection. If you've used one of these in the past, you could continue using this with AspNetCore.

**Comment by drobertson123** [comment]
> At the point of configuration, I need to be able to define what specific implementations get added to the collection or Configuration object that will be passed to the Service ctor. I can set these in the configuration easily enough, but I can't seem to figure out a way to get the DI system to add them to the specific service.
Could you elaborate on this, perhaps with an example?

I have a Service that provides consolidated data to be serialized and used on web pages. Requests for multiple data items come in at once as a collection of IRequests. These IRequests are all similar but have disparate sources. I pass the collection of IRequests to the GetData(IRequests requests) method of the DataService. Internal to the DataService is a collection of more specialized DataAdapters. Each adapter retrieves data for a specific subset of Requests and returns that data to the DataService to be consolidated into a Repository that gets returned and then serialized.

Each DataAdapter can change periodically. They can also be fickle and the requests may need to be routed to a different data adapter. We also have Mock data adapters for testing. The number of DataAdapters that we configure for use in the DataServer can vary periodically.

Recompiling and redeploying needs to be minimized, but changing a config file and bumping the server would be acceptable. Note, the system would have alternative DataAdapters ready for use in case we did need to reconfigure.

I need to be able to inject a collection of DataAdapters into the DataService as it is being injected into the Controler.  Here is a simplified example of the service.

Original ctor;

```
public DataService(IEnumerable<IDataAdapters> adapters)
{
    _adapters = adapters;
}
```

Modified ctor using IOptions;

```
public class DataServiceOptions
{
    public IEnumerable<IDataAdapters> adapters { get; set; }
}

public DataService(IOptions<DataServiceOptions> optionsAccessor)
{
    _adapters = optionsAccessor.value.adapters;
}
```

> IServiceProvider will get injected into services by default. You don't have to pass around the HttpContextAccessor to get to it.

I have worked with grabbing the HttpContextAccessor at the point of injection and that does work, but it forces me to have a specific dependency on the HttpContextAccessor and it makes me use;

`RequestServices.GetService(Type.GetType(dataAdapterType)) `

Inside my DataService which I would like to avoid if possible. In this solution I pass a list of specific DataAdapterTypes into the object and get them internally. In many ways I am not really comfortable with this. This service gets used in other ways and minimizing the dependencies is importiant.

If it is possible to access `RequestServices.GetService()` from inside the `DataServiceOptions` object I could turn that into an object factory and hand the apropriate DataAdapters in from the configuration object. That would replace the need to inject HttpContextAccessor in the ctor of the DataService and at least reduce the issues. If it was used outside of ASP.NET I could do an alternative implementation of the `DataServiceOptions` and it would never know the difference.

I am open to using a different DI container if I absolutely have to, but I would really prefer to not have another dependency to manage and system to learn.

Thanks for responding to this. I apreciate the attention.

**Comment by drobertson123** [comment]
Just an update. After lots of effort and research, I did figure out ways to do what I wanted. 

In every case, I ended up nearly writing a full DI system from scratch as an extension for the ASP.NET core DI system. This wasn't my goal. Instead, I was hoping to just leverage the core DI system that was in place. I didn't expect a collection of classes to be so hard, but it seems my needs go beyond what the DI system can do.

At this point, I am shifting to autofac. It is frustrating to have to add even more dependencies to my project, but unless I am willing to commit to maintaining my own self-developed DI system I don't see any other way.

I do understand your focus on just providing a basic infrastructure, but please understand that by making your system too simplistic it is forcing us to add more and more dependencies to our projects. Each added dependency adds overhead and maintenance complexity. We are already overwhelmed by dependencies and it is just getting worse.

Having a system that allows for an ecosystem of alternatives is wonderful. Building a system that is so simplistic that anything beyond the simplest needs forces you to use outside tools is not so good. Please consider expanding the scope of this DI system at least a little bit.

I really do love the work the ASP.NET team is doing and I appreciate what you are creating, but in so many places it feels like we are being forced to rely on outside dependencies far more than we should have to.

**Comment by Eilon** [comment]
@drobertson123 I'm glad you got it working. It is indeed a delicate balance to decide which features we provide as built-in, and which features require another component.

One thing to keep in mind with all of ASP.NET Core (and was already true with previous project, such as ASP.NET Web API), is that nearly every app is already using 3rd party components. In particular, Json.NET. My point is that ultimately using 3rd party components is unavoidable, it's just a question of how many and which. It's a big giant ecosystem and I think that most "real" apps will end up needing a pretty wide variety of components from multiple vendors.
