### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by seesharper** [aspnet/DependencyInjection#405]
Hi. 

I'm trying to build the whole solution (DependencyInjection.sln) in Visual Studio assuming that you guys are actually using VIsual Studio when developing this. A whopping 640 errors comes to show, most of them from the actual test project. Removing the test project got me down to just a few that relates to an usupported framework (netstandard1.0) which from what I have understood is still not a valid TFM in VIsual Studio. What is it that I am missing here? Building using the build script works though.

**Comment by khellang** [comment]
Visual Studio tooling still relies on the DNX infrastructure, which is incompatible with the new dotnet toolchain. That's the reason you can run the build script (it uses dotnet), while Visual Studio struggles.

I think you have to wait for the RC2 tooling before you're able to build the solution in Visual Studio, or simply just use the dotnet CLI.

**Comment by seesharper** [comment]
That makes sense although it makes me wonder how this library is being developed since VS 2015 does not support the TFM's, but still there are xproj files that indicates Visual Studio being used. You've contributed to this library too. Didn't you use Visual Studio or was it maybe before all hell broke loose with regards to changing TFM's :) I assume that even the smartest of contributors to this library needs to set a breakpoint once in a while and unless they are using @code for this (which is truly bleeding edge), I figure they are using Visual Studio.

**Comment by khellang** [comment]
> it makes me wonder how this library is being developed since VS 2015 does not support the TFM's

It does. Just not the bits that have been released to the public :wink:

> You've contributed to this library too. Didn't you use Visual Studio or was it maybe before all hell broke loose with regards to changing TFM's

Most was before everything fell apart. It's fairly recently that things stopped working on my part. Now I just get by with the dotnet CLI.

**Comment by seesharper** [comment]
Thanks @khellang . Building with the CLI works just fine. Closing this

**Comment by seesharper** [comment]
FYI, I managed to load the solution in VS Code and then created a wrapper console app to launch the tests. That in turn made it possible to debug a xunit test in VS Code.
