### ISSUE TITLE
Net45 and Net46 targets

### ISSUE THREAD

**Issue by seesharper** [aspnet/DependencyInjection#407]
The Nuget package should explicitly have a net45 and net46 target. 

Create a new plain old net46 (or net45) class library.

Add the Microsoft.Extensions.DependencyInjection package.

Even though we are now on full .Net it tries to install all the net standard dependencies even though they are really not needed. The actual assemblies does not even get downloaded with these packages. Each lib folder just contains a file named "underscore dot underscore" (Markdown did not like it :))

**Comment by Eilon** [comment]
@davidfowl / @ericstj thoughts on this? Any particular recommendations on specifically targeting net45x instead of netstandard + NuGet dependencies?

**Comment by Eilon** [comment]
I chatted with @danroth27 @anurse @pakrym @muratg .

We don't think that adding `net45` (etc.) to the packages is the right approach. If anything, we would look at improving the experience of `netstandard` and the standard library.

@richlander we should talk about this more to see what are some rough edges that could benefit from some polishing.
