### ISSUE TITLE
Unique-ify the names of the various ServiceCollectionExtensions types

### ISSUE THREAD

**Issue by Eilon** [aspnet/DependencyInjection#408]
Currently they conflict with type names in other assemblies and/or have super generic names (thus making the names somewhat useless). We should always give these types reasonably unique names describing not only what they extend, but what type of functionality they add.

Proposal:
* Rename [this](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection/ServiceCollectionExtensions.cs) to `ServiceCollectionContainerBuilderExtensions`
* Rename [this](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs) to `ServiceCollectionServiceExtensions`
* Rename [this](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/Extensions/ServiceCollectionExtensions.cs) to `ServiceCollectionDescriptorExtensions`
* Rename [this](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceProviderExtensions.cs) to `ServiceProviderServiceExtensions`

**Comment by Eilon** [comment]
@danroth27 FYI

**Comment by NTaylorMullen** [comment]
60ca512beec3fefb4cd377ede009ff96b4848456
