### ISSUE TITLE
OpenID and some other injections stopped working yesterday

### ISSUE THREAD

**Issue by byatis** [aspnet/DependencyInjection#411]
I had to move to RC3 branch, since RC2 had too many problems. It worked for a while, but now I can't start my application at all. I got an error:

```
{System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.UseOpenIdConnectServer(IApplicationBuilder app, Action`1 configuration)
   at MyBeta.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, RoleManager`1 roleManager) in C:\Startup.cs:line 171}
```

Here is the code that fails:
```
    app.UseOpenIdConnectServer(options =>
            {
                // Disable the HTTPS requirement.
                options.AllowInsecureHttp = true;

                // Disable the authorization endpoint as it's not used in this scenario.
                options.AuthorizationEndpointPath = PathString.Empty;

                options.Provider = new AuthorizationProvider();

                // Force the OpenID Connect server middleware to use JWT tokens
                // instead of the default opaque/encrypted format.
                options.UseJwtTokens();
            });

```

If I remove this, the application goes a bit further but then it fails with ApplicationInsights Telemetry.

Everything worked fine until I hit the build button yesterday, and packages got restored. After that I've tried for several hours to get this back working.

Here's my  current project.json:

```
{
  "userSecretsId": "aspnet-WebApplication1-724fa028-01e3-41c4-a61e-928af5ebb7f2",
  "dependencies": {
    "AspNet.Security.OpenIdConnect.Server": "1.0.0-beta5-final",
    "dnx-coreclr-win-x64": "1.0.0-*",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Cors": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Hosting.Abstractions": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc3-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc3-*",

    "Microsoft.EntityFrameworkCore": "1.0.0-rc3-*",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.0-rc3-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc3-*",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-21006",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8+wp8",
        "portable-net45+win8",
        "dnxcore50",
        "netcore50",
        "netcoreapp-1.0"
      ]
    },
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-rc3-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc3-*",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc3-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc3-*",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc3-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc3-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc3-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc3-*",
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc3-004312",
      "type": "platform"
    },
    //"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
    //  "version": "1.0.0-preview1-final",
    //  "type": "build"
    //},
    //"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
    //  "version": "1.0.0-preview1-final",
    //  "type": "build"
    //},
    "System.IdentityModel.Tokens": "5.0.0-rc1-*",
    "System.IO.FileSystem": "4.0.1-rc3-*",
    "System.Runtime": "4.1.0-rc3-*"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50",
      "version": "1.0.0-*"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-21006",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8",
        "portable-net45+win8+wp8",
        "dnxcore50",
        "netcore50",
        "netcoreapp-1.0"
      ]
    },
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    //"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
    //  "version": "1.0.0-preview1-final",
    //  "imports": [
    //    "portable-net45+win8+dnxcore50",
    //    "portable-net45+win8"
    //  ]
    //}
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "netcore50",
        "portable-net45+win8",
        "portable-net45+win8+wp8",

        "portable-net45+win8+wp8+wpa81"

      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": false,
    "gcConcurrent": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]

  }

}

```

**Comment by pranavkm** [comment]
@NTaylorMullen \ @Eilon - this seems related to the renames we did yesterday - https://github.com/aspnet/DependencyInjection/commit/60ca512beec3fefb4cd377ede009ff96b4848456.

**Comment by Eilon** [comment]
Yeah it seems that `AspNet.Security.OpenIdConnect.Server` needs to be recompiled against the latest rc3 build and then it'll work.

@PinpointTownes FYI. We renamed the type that an extension method is on, so the code just needs to be recompiled.

**Comment by pranavkm** [comment]
@NTaylorMullen could you write an announcement for this since it's breaking rc2 compiled code?

**Comment by Eilon** [comment]
Ah yeah I suppose we could announce this. Definitely an inadvertent consequence.

**Comment by NTaylorMullen** [comment]
WIll do.

**Comment by PinpointTownes** [comment]
Ah, thanks for the info. I'll trigger a new build of the dev branch (ASOS beta6 nightly, for ASP.NET Core RC3).

**Comment by PinpointTownes** [comment]
Hum, looks like the build failed due to some obscure changes in Sake/KoreBuild. I'll investigate when I'm back home.

**Comment by Eilon** [comment]
@PinpointTownes thanks! Let us know if we can help.

**Comment by NTaylorMullen** [comment]
Announcement filed: https://github.com/aspnet/Announcements/issues/187

**Comment by PinpointTownes** [comment]
@Eilon thanks for the offer :smile: 

Do you know if the Sake/KoreBuild changes are documented somewhere? The makefile.shade file we're using no longer compiles: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/makefile.shade :cry:

**Comment by Eilon** [comment]
Hmm, well, KoreBuild is just an internal tool that we use so it's not really documented anywhere.

Can you use some older build of KoreBuild instead? E.g. grab the RC1 build from https://www.myget.org/gallery/aspnetmaster ? One thing we changed was to not have a NuGet package for it and instead download the ZIP straight from GitHub, e.g. look at https://github.com/aspnet/Security/blob/dev/build.ps1#L36 . So if you need some particular build of KoreBuild, you could just sync to a particular commit SHA and use that as a snapshot.

**Comment by PinpointTownes** [comment]
Thanks for the tip, but it was actually much easier to fix than I had expected (well... it is... when you find the breaking change in the git history :sweat_smile:): https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/280/files

That said, the build is now blocked by a really weird error:

```
Errors in C:\projects\aspnet-security-openidconnect-server\samples\Mvc\Mvc.Client\project.json
    Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002886 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002886 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

    Package Microsoft.AspNetCore.Mvc 1.0.0-rc3-21101 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc 1.0.0-rc3-21101 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
 
Errors in C:\projects\aspnet-security-openidconnect-server\samples\Mvc\Mvc.Server\project.json
    Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002886 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002886 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

    Package Microsoft.AspNetCore.Mvc 1.0.0-rc3-21101 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc 1.0.0-rc3-21101 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

Isn't `netcoreapp1.0` supposed to work with `netstandard1.6`? :scream:

**Comment by Eilon** [comment]
Hmm, @pranavkm might know more about this. He made this change to MVC yesterday: https://github.com/aspnet/Mvc/pull/4755

**Comment by pranavkm** [comment]
`netstandard1.6` was newly introduced, so I think you need a new-ish CLI to work with it.

**Comment by PinpointTownes** [comment]
> netstandard1.6 was newly introduced, so I think you need a new-ish CLI to work with it.

The error is seen on the CI server. Does KoreBuild uses a compatible CLI/NuGet version?

**Comment by pranavkm** [comment]
KoreBuild is on a pretty recent build. I did see this on one of the dev boxes where an RC2 build (a build before CLI was changed to preview) was installed under `%ProgramFiles%\dotnet`. Could you check what `dotnet --version` prints out?

**Comment by PinpointTownes** [comment]
Sure: [`1.0.0-preview2-002886`](https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openidconnect-server/build/1.0.0-beta6-835#L11). I'll trigger a new build, just in case :smile:

**Comment by PinpointTownes** [comment]
Looks like the issue was specific to AppVeyor. Changing the default build environment to "Previous Visual Studio 2015" fixed this issue.

@byatis FYI, the updated package is now online (`1.0.0-beta6-0839`).

@pranavkm @Eilon thanks for your assistance :smile:

**Comment by tuespetre** [comment]
Thanks for the trail of crumbs ;)

Had to delete `%USERPROFILE%\AppData\Local\dotnet` to resolve the same issue as @PinpointTownes

**Comment by jjennings** [comment]
I believe I'm having the same issue migrating from RC2 to RTM.  Naming issues between AspNet.Security.OpenIdConnect.Server, AspNet.Security.OpenIdConnect.Extensions, Microsoft.Extensions.DependencyInjection.  Currently, I'm getting this error:

> {System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.0.0.669, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.IdentityModel.Tokens, Version=5.0.0.669, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerOptions..ctor()
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.UseOpenIdConnectServer(IApplicationBuilder app, Action`1 configuration)
   at HVMPortal.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, UserManager`1 userManager) in C:\Src\HVMPortal\src\HVMPortal\Startup.cs:line 138}

**Comment by PinpointTownes** [comment]
@jjennings make sure you're using the `1.0.0-beta6-final` package from the MyGet feed (it will be pushed to NuGet in the next few days).

**Comment by PinpointTownes** [comment]
@jjennings FYI, it was pushed to NuGet.org a few minutes ago.
