### ISSUE TITLE
Discussion: DependencyInjection service collection/provider extension classes have been renamed to avoid ambiguity

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/DependencyInjection#412]
Format: _Microsoft.Extensions.DependencyInjection.*_  

| Package | Old Type Name | New Type Name |
| --- | --- | --- |
| Abstractions | Extensions.ServiceCollectionExtensions | ServiceCollectionDescriptorExtensions |
| Abstractions | ServiceCollectionExtensions | ServiceCollectionServiceExtensions |
| Abstractions | ServiceProviderExtensions | ServiceProviderServiceExtensions |
| Primary Package | ServiceCollectionExtensions | ServiceCollectionContainerBuilderExtensions |

Associated announcement: https://github.com/aspnet/Announcements/issues/187

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
