### ISSUE TITLE
Register derived interface, request base interface results in Exception

### ISSUE THREAD

**Issue by Villason** [aspnet/DependencyInjection#414]
```
serviceBuilder.Services.AddScoped<IModelRepository<User>, UserRepository>();
```

Then in a Controller I I request a IReadOnlyModelRepository<User>. IModelRepository<T> derives from IReadOnlyModelRepository<T>.

Should I get the exception?

```
InvalidOperationException: Unable to resolve service for type 'IReadOnlyModelRepository`1[User]' while attempting to activate 'Controller'.
```

The workaround of course consists in registering IReadOnlyModelRepository<User> as well.

**Comment by davidfowl** [comment]
This is by design. You don't get inherited interfaces for free, you need to register them.

**Comment by Eilon** [comment]
Correct, registrations have to be of the exact type that will be requested.
