### ISSUE TITLE
Question about Creating Scopes

### ISSUE THREAD

**Issue by rposener** [aspnet/DependencyInjection#415]
If I resolve an IServiceScopeFactory, then create a scope, is there any facility to modify a Registration in that new scope to provide a different lifetime?  I'm wanting to resolve something from first scope, then change it's lifetime in the second scope.

The use-case is that I'm developing a WebSocket middleware which needs to have a class which has a lifetime which is a singleton to the path mapped which registers the sockets, while creating another class on demand when socket messages are processed, so that EF and other tools can have a proper scope for processing those inbound messages.  Or optionally maybe a custom Activator method which resolves all but the type I want to provide from the first scope.

This might help:

Top Scope
- /path (Middleware)
- - Create Scope1
- - - Create Scoped Registrations List
- - - Web Socket Message Received
- - - - Create Scope2
- - - - - Invoke Handler to process message (with injected Scoped Registrations List)
- - - - Dispose Scope2
.... some point later ...
- - Connections all drop, and my Scope1 is disposed

The goal here is that each path has it's own list of Scoped Registrations.

**Comment by sebastienros** [comment]
What we do in https://github.com/OrchardCMS/Orchard2 is that at startup we create as many containers as we have tenants (one per url prefix), with unique and also common services, and we have a middleware that will detect which one to use, then resolve `IServiceScopeFactory` from it to create a Scope that will be used during the request.

c.f. https://github.com/OrchardCMS/Orchard2/blob/12c028e0b7a479e3ebae3fd2065ff1bad695368b/src/Orchard.Hosting.Web/OrchardContainerMiddleware.cs

**Comment by rposener** [comment]
Thanks for that info - I will take a look at what you have going on there.  I might have a few more questions once I get my head around what you are doing and how it best applies to my case.

**Comment by rposener** [comment]
I looked at what you guys were doing - made sense.  I took a similar but simpler approach for my need.  Basically ended up with a singleton "manager" that handles the creation/disposal of scopes.  After doing this, I realized I was already doing the same within my socket manager class, per a "logical" request.

Thanks for the input.
