### ISSUE TITLE
Update Abstractions project.json description

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/DependencyInjection#420]
The project.json for the DI abstractions [references](https://github.com/aspnet/DependencyInjection/blob/caa3f4ec3f0b7e92a0a0210795303b28c09ecbba/src/Microsoft.Extensions.DependencyInjection.Abstractions/project.json#L3) an old `ServiceCollectionExtensions` type.

This was renamed to `ServiceCollectionServiceExtensions`.

**Comment by Eilon** [comment]
The fix is to remove that line entirely from the project.json file, because it's not a type that's commonly referenced from source code.

**Comment by ajaybhargavb** [comment]
213a055708ea4b0031beb6a84334cbb2497e2496
