### ISSUE TITLE
Dependency Injection Extensions has 2 AddCors methods with exact same signature

### ISSUE THREAD

**Issue by vandensd** [aspnet/DependencyInjection#421]
When using Cors there are multiple overloads available when calling services.AddCors() in Startup.cs.

Both are referenced from the exact same IServiceCollection extension for DependencyInjection.  Compilation cannot occur because the call becomes ambiguous.

**Comment by rynowak** [comment]
Look at your package references, you very likely are referencing both rc1 and rc2 packages in the same application.

**Comment by Eilon** [comment]
Yep, almost certainly what @rynowak said. Check that everything is all RC2 packages.

**Comment by Eilon** [comment]
Or if you can't get it to work, please share your project.json file.

**Comment by vandensd** [comment]
Sorry I didn't see these responses sooner.  I can certainly look into that.  Please hold off on any suggestions until I do so which should be later this evening.  And thank you both for responding so quick.

**Comment by vandensd** [comment]
Ok, you both are on to something...

The ASP.Cors reference, mind you as advised by the .NET Documentation website which has been updated for RC2...

ASP.Cors I have referenced as "rc1", probably because I used intellisense and didn't see rc2 is available or it is and I missed it.

I will close this issue and thanks again.

**Comment by Eilon** [comment]
@vandensd glad you got it working!

**Comment by StephenPaul** [comment]
Hi. I'm having the identical issue, except it's after creating a **1.0.0** .net Core app. I've added no other dependencies besides `"Microsoft.AspNet.Cors": "6.0.0-rc1-final"` as indicated in [this ](https://docs.asp.net/en/latest/security/cors.html) resource. Can anyone point out to me where I'm going wrong?

**Comment by moozzyk** [comment]
If you look at the page you provided the link to you will see: _This page documents version 1.0.0-rc1 and has not yet been updated for version 1.0.0_

You can't mix package versions. Try using 1.0.0 of the Cors package: https://www.nuget.org/packages/Microsoft.AspNetCore.Cors/

**Comment by StephenPaul** [comment]
@moozzyk, much appreciated. Awesome, that fixes it.
