### ISSUE TITLE
Ambiguous call

### ISSUE THREAD

**Issue by dvdobrovolskiy** [aspnet/DependencyInjection#423]
>Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.Configure<TOptions>(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action<TOptions>)' and 'Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.Configure<TOptions>(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action<TOptions>)'	SwiftCourier.Web..NETCoreApp,Version=v1.0	C:\..............\Startup.cs	68	Active

in startup.cs I have 

```c#
services.Configure<RequestLocalizationOptions>(
                options =>
                {
                    var supportedCultures = new List<CultureInfo>
                        {
                            new CultureInfo("ru-RU"),
                        };

                    options.DefaultRequestCulture = new RequestCulture(culture: "ru-RU", uiCulture: "ru-RU");
                    options.SupportedCultures = supportedCultures;
                    options.SupportedUICultures = supportedCultures;
                });
```

**Comment by Eilon** [comment]
@dvdobrovolskiy do you perhaps have a mix of RC1 and RC2 packages? Check your project.json and make sure everything is using rc2-final packages. If you can't find it, please share your project.json file and we can take a look.

**Comment by dvdobrovolskiy** [comment]
nope, rc2-*

**Comment by dvdobrovolskiy** [comment]
hm
rc2-3002702 instead of rc2-* helped. Issue resolved

**Comment by Eilon** [comment]
@dvdobrovolskiy ah ok, so we can close this issue?

**Comment by dvdobrovolskiy** [comment]
I think so. Just strange why it appeared any way

**Comment by letrape** [comment]
I am having the same issue  :'(   there is no documentation about it

**Comment by dvdobrovolskiy** [comment]
Seemed like outdated code example.

this works (in Configure)
var supportedCultures = new[]
            {
                  new CultureInfo("ru-RU"),
            };

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("ru-RU"),
                // Formatting numbers, dates, etc.
                SupportedCultures = supportedCultures,
                // UI strings that we have localized.
                SupportedUICultures = supportedCultures
            });
