### ISSUE TITLE
Could not load type ServiceCollectionExtensions

### ISSUE THREAD

**Issue by allangomessl** [aspnet/DependencyInjection#424]
This error occurred after update to asp.net RTM

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.NpgsqlEntityFrameworkServicesBuilderExtensions.AddEntityFrameworkNpgsql(IServiceCollection services)

**Comment by davidfowl** [comment]
Unlikely that this is a problem with the Dependency injection library. It's likely a problem with Npgsql.

**Comment by allangomessl** [comment]
I believe that this error is caused because versions are incompatible.

`Ngpsql.EntityFrameworkCore.PostgreSQL`
   Dependencies - `Microsoft.Extensions.DependencyInjection` `1.0.0-*` instead of `1.0.0`


Can I to use app.config for fix this problem while a new version of ngpsql not released?
```xml
<configuration>
 <runtime>
   <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
     <dependentAssembly>
       <assemblyIdentity name="Microsoft.Extensions.DependencyInjection"
                         publicKeyToken="b03f5f7f11d50a3a"
                         culture="neutral" />
       <bindingRedirect oldVersion="1.0.0-*"
                        newVersion="1.0.0"/>
     </dependentAssembly>
   </assemblyBinding>
 </runtime>
</configuration>
```

**Comment by davidfowl** [comment]
> I believe that this error is caused because versions are incompatible.

Yes, that sounds accurate. You probably just need to wait until Npgsql is updated.

> Can I to use app.config for fix this problem while a new version of ngpsql not released?

A binding redirect won't help you here. The libraries are incompatible.

**Comment by allangomessl** [comment]
Thank you.
