### ISSUE TITLE
Avoid lambda expression compilation for Singleton scoped services

### ISSUE THREAD

**Issue by mnltejaswini** [aspnet/DependencyInjection#425]
The motivation for this issue is customer issue https://github.com/aspnet/Hosting/issues/781 
Customer reported that for his app on Desktop CLR (net 46) , there is an increase in the memory foot print from RC1 to RC2. But as of now we care about RTM. So I collected some numbers to compare memory between RC2 to RTM for the same app that customer shared with us. Here are the numbers after the first request and doing a full GC sweep.

| Metric   |      RC2      |  RTM |
|----------|:-------------:|------:|
| Total Private Bytes |  250 MB | 315 MB |
| Total Managed Heap Private Bytes |    123 MB   |   180 MB |

From the numbers,  there is an increase in the memory from RC2 to RTM during start up of the app. The increase comes from managed heap only.  Although there isn't increase in the retained memory in GC , there is an increase of 100MB of memory allocations during start up of the app. The dotMemory profile for the allocations is pasted below

RC2 memory allocations during start up

![image](https://cloud.githubusercontent.com/assets/8011073/16424696/18ad3a06-3d16-11e6-92f2-79ac39e33b4e.png)

RTM memory allocations during start up 
![image](https://cloud.githubusercontent.com/assets/8011073/16424750/50d0a56c-3d16-11e6-95f8-81bb98841dd2.png)

As seen, the major memory allocations come from Code Access Security checks that are executed during compilation of lambda expression when a service is resolved more than 2 times. (https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection/ServiceProvider.cs#L86 )  With the increase in the number of services resolved, these allocations increase.
However Net core apps doesn't have these checks as they are removed for Core CLR.
Note that these CAS objects also appear in the top list for RC2. Although these allocations happens one time, the problem is that the GC managed heap shoots high triggering GC cycles. Also, this increases the memory foot print for the process. This issue is logged to reduce these memory allocations during start up.  
Singleton services once created are always available in the lookup dictionary. So it is cheap to  directly call the Invoke method that does a simple lookup rather than building expression trees to do the same. I prototyped this change and measured the memory.  In the customer app, there are about 903 Singleton services, 38 scoped services and 463 transient services. As there are more Singleton services, the change has very good impact. Below are the numbers

| Metric   |      Before       |  After |
|----------|:-------------:|------:|
| Total Private Bytes |  315MB | 223MB |
| Total Managed Heap Private Bytes |    180MB   |   92MB |

and the dotMemory profile after the change.

![image](https://cloud.githubusercontent.com/assets/8011073/16424973/2ee9318e-3d17-11e6-8158-a2d910cc5bad.png)

Will send a PR for the change

**Comment by rynowak** [comment]
> In the customer app, there are about 903 Singleton services, 38 scoped services and 463 transient services

This seems really really high. Is this the number of service definitions? Or the number of service resolutions?

Can you provide more of a breakdown?

**Comment by mnltejaswini** [comment]
![image](https://cloud.githubusercontent.com/assets/8011073/16427656/28876eda-3d23-11e6-8b73-3b352982449a.png)

They are the total SingletonCallSite instances

**Comment by mnltejaswini** [comment]
I searched for SingletonServiceCallSites

**Comment by muratg** [comment]
:eyes:
