### ISSUE TITLE
Will there be Documentation and/or Guide?

### ISSUE THREAD

**Issue by Abdullah2993** [aspnet/DependencyInjection#431]
As of right now only API reference is available in docs. 
Will there be proper Documentation and Guides for using `Microsoft.Extension.*` so that they can be use separately for `AspNetCore`

Especially for `Microsoft.Extensions.DependencyInjection`,  `Microsoft.Extensions.Configuration`, `Microsoft.Extensions.Logging` and `Microsoft.Extensions.Options`

**Comment by davidfowl** [comment]
You should file this bug on the docs repository.
