### ISSUE TITLE
Interception Support

### ISSUE THREAD

**Issue by Talento90** [aspnet/DependencyInjection#434]
There are any plans to support Interception like [Unity (Microsoft IOC)](https://msdn.microsoft.com/en-us/library/dn178466(v=pandp.30).aspx)?

Thanks,
Talento90

**Comment by davidfowl** [comment]
No plans

**Comment by Talento90** [comment]
Thanks for the fast answer,
Interception is a powerful concept, it's a pity that is not in the roadmap. :-1: 
 
Keep doing a great job, dotnet core is the future :+1:  :+1: 

Thanks,
Talento90
