### ISSUE TITLE
Testing DI out of TestServer

### ISSUE THREAD

**Issue by DovydasNavickas** [aspnet/DependencyInjection#445]
I have a web application that polls service bus topic and processes received messages. For that, I have created handler mechanism for their registration and deciding which handler to use for particular message.
For every message processing, I am injecting a new instance of handler (`GetRequiredService`) and it works awesomely.

Now I started writing tests for the application after it was implemented and I can't seem to find a way to use DI out of web application.

I have my test project and I know that there is `TestServer` which does simulate everything that a real server does with `Startup` class that has `ConfigureServices` and `Configure` methods.

But if didn't miss anything, it is really convenient for HTTP requests/response testing as you simulate requests to the server and analyze the results.

As my application uses HTTP requests only to control the polling and processing mechanisms and report current status, if requested, polling happens in the background.

I wanted to test my service bus message processing mechanism separately from the whole HTTP and middleware pipeline, but as I need `IServiceProvider` and `IServiceScopeFactory` (to create separate DI scope for every message handler) in my mechanism, I need to:
a) use the `ServiceProvider` implementation that comes from this repo
b) implement my own `IServiceProvider` and `IServiceScopeFactory`, which is quite some work to do and would not be the same

Am I doing something fundamentally wrong here, missing something obvious or is it not possible to use `IServiceProvider` and `IServiceScopeFactory` implementations out of web application as this PR was closed and not merged https://github.com/aspnet/DependencyInjection/pull/321?

**Comment by pranavkm** [comment]
@DovydasNavickas you can use the `ServiceProvider` by adding a reference to `Microsoft.Extensions.DependencyInjection` and invoking `IServiceCollection.BuildServiceProvider()`. 

```C#
var serviceCollection = new ServiceCollection();
serviceCollection.AddTransient<...>();

var serviceProvider = serviceCollection.BuildServiceProvider();
```

Does that work?

**Comment by davidfowl** [comment]
> Am I doing something fundamentally wrong here, missing something obvious or is it not possible to use IServiceProvider and IServiceScopeFactory implementations out of web application as this PR was closed and not merged #321?

You can just new up a `ServiceCollection` and call `BuildServiceProvider()` on it to get an `IServiceProvider` instance (the default implementation)

**Comment by davidfowl** [comment]
Damn @pranavkm is too fast 😄

**Comment by DovydasNavickas** [comment]
@davidfowl, @pranavkm yep. The only thing is that I didn't find documentation on this :crying_cat_face: 
https://www.google.lt/#q=BuildServiceProvider+site:docs.asp.net
https://docs.asp.net/en/latest/search.html?q=BuildServiceProvider&check_keywords=yes&area=default

Thanks, it really does work :+1: :smile:

**Comment by DovydasNavickas** [comment]
The only problem now is documentation for other people. Maybe we could ping someone about that?

**Comment by Eilon** [comment]
Closing because there are no plans to do more work in this area.
