### ISSUE TITLE
[Improvement] on ServiceDescriptor

### ISSUE THREAD

**Issue by soeron** [aspnet/DependencyInjection#452]
ServiceDescriptor should throw exception in the constructor if the implementation type/object doesn't inherit from the provided service type.

**Comment by davidfowl** [comment]
Sounds like a good check, though I'd like to see the effect on startup performance (if any) as we register > 100 descriptors.

/cc @pakrym

**Comment by viniciusmelquiades** [comment]
The check could be optional, disabled by default, and passed to the `ServiceCollectionContainerBuilderExtensions.BuildServiceProvider`, so we could enable it during development and catch errors during the startup if our projects.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2345
