### ISSUE TITLE
Unable to resolve service for type Microsoft.AspNetCore.Identity.IRoleStore while attempting to activate

### ISSUE THREAD

**Issue by phanikvr** [aspnet/DependencyInjection#460]
I'm trying to override the default asp.net identity with my own ( a DB already exist or authentication N authorization)
said that, i've created my own userstore and rolestore.  the startup.cs file  is:

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Routing;
using CustomAuth.Models;
using Microsoft.AspNetCore.Http;

namespace CustomAuth
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsEnvironment("Development"))
            {
                // This will push telemetry data through Application Insights pipeline faster, allowing you to view results immediately.
                builder.AddApplicationInsightsSettings(developerMode: true);
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);

            services.AddIdentity<AMEUser, AMEUserRole>()
            .AddUserStore<AMEUserStore>()
            .AddUserManager<AMEUserManager>()
            .AddDefaultTokenProviders();

            services.AddScoped<Microsoft.AspNetCore.Identity.SignInManager<AMEUser>, ChiaouSingnInManager>();

            services.AddMvc();

            //services.Configure<CookieAuthenticationOptions>(options =>
            //{
            //    options.LoginPath = new PathString("/Account/Login");
            //});



        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            //app.UseCookieAuthentication();

            app.UseApplicationInsightsRequestTelemetry();

            app.UseApplicationInsightsExceptionTelemetry();

            app.UseMvc(routes =>
           {
               routes.MapRoute(
                      name: "default",
                      template: "{controller=Account}/{action=Login}/{id?}");
           });

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                LoginPath = new PathString("/Account/Login")
            });
        }
    }
}
```

and  project.json file is 

``` js
{
  "dependencies": {
    "EntityFramework": "6.1.3",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNet.Identity.Core": "2.2.1",
    "Microsoft.AspNetCore.Identity": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net452": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

and my user and role store 👍 

``` C#
public class AMEUserStore : Microsoft.AspNetCore.Identity.IUserStore<AMEUser>, Microsoft.AspNetCore.Identity.IRoleStore<AMEUserRole>
    {
        private AMEDbContext database;

        public AMEUserStore()
        {
            database = new AMEDbContext();
        }

        public void Dispose()
        {
            database.Dispose();
        }

        #region userstore
        public Task CreateAsync(AMEUser user)
        {
            throw new NotImplementedException();
        }

        public Task<Microsoft.AspNetCore.Identity.IdentityResult> CreateAsync(AMEUser user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task DeleteAsync(AMEUser user)
        {
            throw new NotImplementedException();
        }

        public Task<Microsoft.AspNetCore.Identity.IdentityResult> DeleteAsync(AMEUser user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public async Task<AMEUser> FindByIdAsync(string userId)
        {
            var user = await database.Users.Where(c => c.Id == userId).FirstOrDefaultAsync();
            return user;
        }

         Task<AMEUser> Microsoft.AspNetCore.Identity.IUserStore<AMEUser>.FindByIdAsync(string userId, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public async Task<AMEUser> FindByNameAsync(string userName)
        {
            var user = await database.Users.Where(c => c.UserName == userName).FirstOrDefaultAsync();
            return user;
        }

        async Task<AMEUser> Microsoft.AspNetCore.Identity.IUserStore<AMEUser>.FindByNameAsync(string userName, CancellationToken cancellationToken)
        {
            var user = await database.Users.Where(c => c.UserName == userName).FirstOrDefaultAsync();
            return user;
        }

        public async Task<string> GetNormalizedUserNameAsync(AMEUser user, CancellationToken cancellationToken)
        {
            var user1 = await database.Users.Where(c => c.UserName == user.UserName).FirstOrDefaultAsync();
            return user1.UserName;
        }

        public async Task<string> GetUserIdAsync(AMEUser user, CancellationToken cancellationToken)
        {
            var user1 = await database.Users.Where(c => c.Id == user.Id).FirstOrDefaultAsync();
            return user1.Id;
        }

        public async Task<string> GetUserNameAsync(AMEUser user, CancellationToken cancellationToken)
        {
            var user1 = await database.Users.Where(c => c.UserName == user.UserName).FirstOrDefaultAsync();
            return user1.UserName;
        }

        public Task SetNormalizedUserNameAsync(AMEUser user, string normalizedName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task SetUserNameAsync(AMEUser user, string userName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task UpdateAsync(AMEUser user)
        {
            throw new NotImplementedException();
        }

        public Task<Microsoft.AspNetCore.Identity.IdentityResult> UpdateAsync(AMEUser user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }
        #endregion

        #region RoleStore
        public Task<Microsoft.AspNetCore.Identity.IdentityResult> CreateAsync(AMEUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }
        public Task<Microsoft.AspNetCore.Identity.IdentityResult> DeleteAsync(AMEUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }
        public async Task<AMEUserRole> FindByIdAsync(string roleId, CancellationToken cancellationToken)
        {
            var user = await database.Roles.Where(c => c.Id == roleId).FirstOrDefaultAsync();
            return await Task.FromResult(user);
        }
        public Task<AMEUserRole> FindByNameAsync(string normalizedRoleName, CancellationToken cancellationToken) {
            throw new NotImplementedException();
        }
        public Task<string> GetNormalizedRoleNameAsync(AMEUserRole role, CancellationToken cancellationToken) {
            throw new NotImplementedException();
        }
        public async Task<string> GetRoleIdAsync(AMEUserRole role, CancellationToken cancellationToken) {
            var user1 = await database.Roles.Where(c => c.Id == role.Id).FirstOrDefaultAsync();
            return user1.Id;
        }
        public async Task<string> GetRoleNameAsync(AMEUserRole role, CancellationToken cancellationToken) {
            var user1 = await database.Roles.Where(c => c.Name == role.Name).FirstOrDefaultAsync();
            return user1.Name;
        }
        public Task SetNormalizedRoleNameAsync(AMEUserRole role, string normalizedName, CancellationToken cancellationToken) {
            throw new NotImplementedException();
        }
        public Task SetRoleNameAsync(AMEUserRole role, string roleName, CancellationToken cancellationToken) {
            throw new NotImplementedException();
        }
        public Task<Microsoft.AspNetCore.Identity.IdentityResult> UpdateAsync(AMEUserRole role, CancellationToken cancellationToken) {
            throw new NotImplementedException();
        }
        #endregion
    }
```

can anyone suggest me where it went wrong and how to fix this?

**Comment by pranavkm** [comment]
Could you include the exception stack trace?

**Comment by myError404** [comment]
Did you fixed? How?

**Comment by Eilon** [comment]
Unfortunately there is not enough information here to reproduce the error.

Please include a more complete repro app, e.g. by uploading your app to GitHub so we can take a look. Also please provide the full exception details and stack trace so we can investigate. Thanks!

**Comment by phanikvr** [comment]
Ok, let me put this way: can we have our own DB schema for roles and identity and can use the existing asp.net IDENTITY framework, provided, we have to override the features. is it possible?

**Comment by davidfowl** [comment]
Sounds like a specific Identity question. You'd be better off filing a new issue on aspnet/Identity.

**Comment by phanikvr** [comment]
got it. i've created (implemented)  IUser<> and UserStore<IUser<>>. and that is all we can use the identity model of own own DB schema.

**Comment by Moses-Bassey** [comment]
Please phanikvr how do you achive that

**Comment by phanikvr** [comment]
Hope you have restored the packages using package manager for all packages available in the solution. If it doesn't work, plz let explain me what and how are u trying to DI.

Thank you,
Venkat

**Comment by Moses-Bassey** [comment]
Yes all microsoft identity packages has been resolve.

Here is my code snippet for DI
services.AddIdentity<Account, AccountUserRole>()
                    .AddUserStore<AccountUserStore>();

Where Account is my user properties information

public class AccountUserStore : Microsoft.AspNetCore.Identity.IUserStore<Account>, Microsoft.AspNetCore.Identity.IRoleStore<AccountUserRole>
    {
        public Task<IdentityResult> CreateAsync(Account user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<IdentityResult> CreateAsync(AccountUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<IdentityResult> DeleteAsync(Account user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<IdentityResult> DeleteAsync(AccountUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public Task<Account> FindByIdAsync(string userId, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<Account> FindByNameAsync(string normalizedUserName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetNormalizedRoleNameAsync(AccountUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetNormalizedUserNameAsync(Account user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetRoleIdAsync(AccountUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetRoleNameAsync(AccountUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetUserIdAsync(Account user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<string> GetUserNameAsync(Account user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task SetNormalizedRoleNameAsync(AccountUserRole role, string normalizedName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task SetNormalizedUserNameAsync(Account user, string normalizedName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task SetRoleNameAsync(AccountUserRole role, string roleName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task SetUserNameAsync(Account user, string userName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<IdentityResult> UpdateAsync(Account user, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public Task<IdentityResult> UpdateAsync(AccountUserRole role, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        Task<AccountUserRole> IRoleStore<AccountUserRole>.FindByIdAsync(string roleId, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        Task<AccountUserRole> IRoleStore<AccountUserRole>.FindByNameAsync(string normalizedRoleName, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }
    }

**Comment by phanikvr** [comment]
ive added the solution https://github.com/phanikvr/Custom_Identity_Core, plz look here and let me know whether it answers your questions/queries

**Comment by jbnewlin** [comment]
@phanikvr That link leads to an empty repo with a readme. Do you have a solution you meant to push?

**Comment by stupidong** [comment]
First, why not separate new store to 2 classes;
Secondly,  my issue is in constructor. UserStore<T> is not inherited from IUserStore<T> while RoleStore<T> is not inherited from IRoleStore<T>.
It's wired, the 2 class should have other names to reduce confusion.

![resolveissue](https://user-images.githubusercontent.com/25354610/34662134-6a9d3b5e-f41c-11e7-9f2c-21cd94a355e5.png)
