### ISSUE TITLE
ServiceProvider with lambda should not always dispose singleton instances

### ISSUE THREAD

**Issue by sebastienros** [aspnet/DependencyInjection#465]
Mostly the same as https://github.com/aspnet/DependencyInjection/issues/459 but in the case of lambda initialization.

The first idea of lambda initialization of services is to create custom instances that _might_ use the current service provider:

```
services.AddSingleton(sp => { var s = sp.GetService<Foo>(); s.Bar = "baz"; return s; });
```

The current behavior is that the returned service will be disposed automatically. Now let's say I want to provide my own instance, shared across scopes, I don't want the container to dispose it for me. I could use the lambda to resolve other services (that would correctly be disposed by the container) but return my own instance using these external services.

The current implementation _assumes_ it has to dispose it, but in some cases the assumption is wrong. I'd suggest we add an option to let users decide that the instance should not be disposed. It would not be a breaking change, but still a conformance issue. Autofac allows to set how the disposable behaves for each registration. I don't know for the other libraries.

**Comment by fangqifan** [comment]
I agree!

**Comment by Eilon** [comment]
We'll look at adding this to 2.0.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2344
