### ISSUE TITLE
Accessing child scope?

### ISSUE THREAD

**Issue by andrasg** [aspnet/DependencyInjection#466]
I am using ApplicationInsights and a job framework (Hangfire) in AspnetCore. Application Insights registers its components as singletons.
My job receives a new scope from DI to run in. I have my components registered in DI as scoped lifetime:
```services.AddScoped(typeof(IMyJobContext), typeof(MyJobContext))```.
I am creating an object through ```IServiceProvider.GetService(typeof(IMyJobContext))``` in the job's scope.

Appinsights uses a concept of a ```TelemetryInitializer``` to process the created telemetry. I am not able to acquire the same ```IMyJobContext``` object in the ```TelemetryInitializer```, as it is a singleton and therefore lives in a different (parent) scope.

I am looking for something similar to aspnet's ```IHttpContextAccessor.HttpContext.RequestServices.GetService(typeof(IMyRequestContext))```. Is there anything in DI that would allow access from a singleton's scope to the more specific (child) scope?

**Comment by khellang** [comment]
A singleton is a singleton no matter which scope you resolve it from. You will always get the same instance :smile:

**Comment by andrasg** [comment]
@khellang, I'm well aware of that... :) I am trying to access a scoped object (IMyJobContext) from the singleton (TelemetryInitializer).

**Comment by khellang** [comment]
You really don't want to do that. Having a service with a longer lifetime depend on a service with a shorter lifetime is bad news. The only way I can see you pulling that off would be to pass the actual `IMyJobContext` to a method on `TelemetryInitializer` and make sure the method returns before the scope is destroyed.

**Comment by andrasg** [comment]
It's actually not that simple. I'll try to explain.
A method (run by Hangfire as a "job") sitting in a class with scoped lifetime calls ILogger.Log. Hangfire manages the scope for the job instance's lifetime. ApplicationInsights has a logprovider (wired to ILogger.Log) that calls TelemetryClient.TrackTrace (TelemetryClient is registered as a singleton) that in turn creates a new TraceTelemetry object and calls a method (InitializeTelemetry) on all registered TelemetryInitializers on the newly created telemetry item. TelemetryInitializers are object instances sitting in the TelemetryClient (so are in the root, singleton scope).
Now, in the TelemetryInitializer.InitializeTelemetry is where I have the first extension point. Here, I would need to read some object (correlationid) that was created in the job's scope. This is where I have found no way to do it, because:
- I cannot modify how the job (Hangfire) creates the scope
- I cannot modify the signature of ApplicationInsights' methods and constructors
- I have found no way to obtain the serviceprovider for the current run instance (scope) of the job

Something very parallel to what I am trying to do happening with Aspnet requests:
A request scope is created for each request. The serviceprovider for the current request is accessible through IHttpContextAccessor.HttpContext.RequestServices. This serviceprovider can be used in a singleton's method to obtain a request scoped object and work with it.

Later I'll put together a small project to demonstrate the issue.

**Comment by davidfowl** [comment]
Are you trying to get access to the request scope or just an arbitrary scope?

**Comment by andrasg** [comment]
The scope Hangfire created (so arbitary). The request scope is easily accessible through IHttpContextAccessor.HttpContext.RequestServices.

**Comment by khellang** [comment]
Quick question; do you have control over the job class? I'm thinking it's time to whip out some code soon, cause explaining what's happening isn't exactly easy. If this job is something that you implement, but Hangfire activates (through the container), can't you just inject `IServiceProvider` to get the provider of the current scope, i.e. the scope that Hangfire created?
