### ISSUE TITLE
Feature request: Add a Properties dictionary to IServiceCollection

### ISSUE THREAD

**Issue by hikalkan** [aspnet/DependencyInjection#468]
Add a ``Dictionary<string, object>`` as ``IServiceCollection.Properties``.
It would be useful to get and set custom objects to be used during service registration process.

I need this since I'm creating a conventional registration system for types in given assembly, and I want to allow to add custom conventions. I will use ``Properties`` to store a list of conventions.

**Comment by cwe1ss** [comment]
You could wrap `IServiceCollection` in a `IMyLibraryBuilder` and add the Properties dictionary there.

MVC does something similar in their [IMvcBuilder](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/IMvcBuilder.cs).

Usage would be e.g.
```csharp
services.AddMyLibary()
  .AddCustomConvention1();
```

**Comment by hikalkan** [comment]
Thank you for the suggestion, I will check it. But what I want is a bit different. Example:

//Add conventions
services.AddConvention(new MyConvention());

//Register types in an assembly by added conventions
services.RegisterByConvention(MyAssembly);

But these two code will be in different modules which does not depend on each other. Say that I have 10 modules, which they all will add their own conventions first. Then all modules will call RegisterByConvention to register their assemblies (applied all conventions of all modules).

I have 2 solutions actually, as a workaround:

1. Created a static Dictionary<IServiceCollection, List<IConvention>> and added extension methods to IServiceCollection to manage it. But I don't like it since it's stored in a static, independent, concurrent dictionary (and I can not remove the list of conventions if the servicecollection is not used anymore)

2. Added a singleton instance of List<IConvention> to service collection and find it from the collection when I need. But this is not also good, since there maybe too many services and this makes a performance overhead.

Anyway, I think such a Properties would be useful for others too. Thanks.

**Comment by cwe1ss** [comment]
How do you pass IServiceCollection to these modules? 

How about something like this:
```csharp
// In "MyFramework.Abstractions"
public interface IModule {
  void ConfigureServices(IServiceCollection services);
}

// In "MyApp.MySampleModule"
public class MySampleModule : IModule {
  public void ConfigureServices(IServiceCollection services) {
    services.AddSomething();
  }
}

// In "MyApp"->Startup.cs
public void ConfigureServices(IServiceCollection services) {
  services.AddMyFramework();
}

// In "MyFramework"
public static void AddMyFramework(this IServiceCollection services) {
  // Use Reflection to go through all assemblies and look for all implementations of "IModule".
  var modules = ...;
  foreach (var module in modules) {
    module.Configure(services);
  }
}
```

**Comment by hikalkan** [comment]
Sure, my code is already almost like that. But I have more requirement.

First, this is a sample module class:

````C#
public class MyModule : IModule
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAssemblyOf<MyModule>();
    }
}
````

services.AddAssembly... is my extension method. Which finds some specific classes in given assembly and adds to the collection. Say that I have an ITransientDependency interface and I'm finding classes which implement this interface and register them as transient. This is a pre-defined convention. But what I want to allow modules to add other conventions, like

````C#
public class MyModule : IModule
{
    public void PreConfigureServices(IServiceCollection services)
    {
        services.AddConvention(new MyCustomConvention());
    }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAssemblyOf<MyModule>();
    }
}
````

Then AddAssemblyOf method will automatically use all conventions added by all modules. As you see, there is no simple way of transferring conventions on IServiceCollection, without such a Properties dictionary.

This is simplified scenario. Anyway, I know can find some other ways, but I believe to add a Properties to IServiceCollection is a good way of sharing objects during service registration.

**Comment by Eilon** [comment]
Closing because there are no plans to build this. This would be a breaking change and we don't think the cost of the breaking change is worth the value, considering that there are some workarounds for this scenario.

**Comment by hikalkan** [comment]
I could not understand why adding a new property is a breaking change. But OK, it was just a suggestion anyway.

**Comment by Eilon** [comment]
It's on an interface, and all interface changes (add/remove/change) are breaking changes.

But beyond that, there are workarounds for this (though they are admittedly a bit ugly), and from what we've seen it's not a very common scenario, either. Even ASP.NET itself uses a workaround for this, but it's in very limited places.
