### ISSUE TITLE
Resolving array of registered services in constructor

### ISSUE THREAD

**Issue by serber** [aspnet/DependencyInjection#478]
Hi

I register few services with same interface
```
services.AddTransient<ISyncService, SyncService1>();
services.AddTransient<ISyncService, SyncService2>();
services.AddTransient<ISyncService, SyncService3>();
services.AddTransient<ISyncService, SyncService4>();
```
and when i try resolve array of instances i've got exception

```
public class MyController : Controller
{
	private readonly ISyncService[] _syncServices;

	public MyController (ISyncService[] syncServices)
	{
		_syncServices= syncServices;
	}
}
```
Exception:

> InvalidOperationException: Unable to resolve service for type 'TestProject.ISyncService[]' while attempting to activate 'TestProject.Controllers.MyController'.

**Comment by davidfowl** [comment]
Arrays don't work, you need to use `IEnumerable<ISyncService>`

**Comment by serber** [comment]
Thanks
