### ISSUE TITLE
Turn on scope validation by default

### ISSUE THREAD

**Issue by danroth27** [aspnet/DependencyInjection#481]
For 2.0 we should consider turning on scope validation by default.

**Comment by davidfowl** [comment]
@pakrym before we turn this on by default need to look at the performance impact.

**Comment by davidfowl** [comment]
Here's results from a benchmark I've added. 

```
                       Method |        Mean |    StdErr |     StdDev |        Op/s | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
----------------------------- |------------ |---------- |----------- |------------ |------- |-------------- |------- |---------- |
                    Transient |  43.5473 ns | 0.4130 ns |  2.2620 ns | 22963524.25 |   1.00 |          0.00 | 0.0095 |      24 B |
 TransientWithScopeValidation |  68.7545 ns | 1.3960 ns |  7.6460 ns | 14544498.22 |   1.58 |          0.19 | 0.0076 |      24 B |

```

**Comment by muratg** [comment]
@danroth27 @DamianEdwards @Eilon do we want this on by default?  Currently they can turn this on with a single line in program main. 

If we want to turn this on by default, we'll need to do it across our tests firsts. 

We were looking at this in DI triage with @davidfowl and @pakrym and we're not sure if this should be done.

**Comment by danroth27** [comment]
It would be really nice if this was on by default, but we would need to test the perf impact.

**Comment by DamianEdwards** [comment]
Perhaps we should just update the templates to have it on by default for Development only?

**Comment by muratg** [comment]
@DamianEdwards that sounds reasonable to me. And we would also enable it at least for a portion of the tests, right?

**Comment by davidfowl** [comment]
That requires use to expose a callback here https://github.com/aspnet/Hosting/blob/51f77ea7f3b4a704691d0def9dd746fe0e32d5dc/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L91 that exposes the `HostingContext`.
