### ISSUE TITLE
Get better on this benchmark

### ISSUE THREAD

**Issue by davidfowl** [aspnet/DependencyInjection#490]
There's a nice DI container comparison here:

https://github.com/danielpalme/IocPerformance

We should get higher on this list 😄

**Comment by benaadams** [comment]
Would IL.Emit be too far? (may or may not be relevant: https://blogs.msdn.microsoft.com/seteplia/2017/02/01/dissecting-the-new-constraint-in-c-a-perfect-example-of-a-leaky-abstraction/)

**Comment by seesharper** [comment]
Optimizing service lookup is probably one area to look into. It's not necessarily a problem with the generated code, but how the factory delegates are looked up during service resolution. The Dictionary and/or ConcurrentDictionary are good all-purpose structures, but there are faster alternatives such as AVL trees.

**Comment by dadhi** [comment]
@benaadams,

IL.Emit is not too far, here is [FastExpressionCompiler](https://github.com/dadhi/FastExpressionCompiler) which I use in DryIoc, which is higher in this benchmark.

@seesharper, and faster lookup AVL trees - yes. [Here](https://github.com/dadhi/ImTools) we go :-)

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2343
