### ISSUE TITLE
Include scopeValidation race condition fix into a patch release

### ISSUE THREAD

**Issue by pakrym** [aspnet/DependencyInjection#493]
https://github.com/aspnet/DependencyInjection/pull/470#issuecomment-281744594

/cc @Eilon @davidfowl @DamianEdwards

**Comment by Eilon** [comment]
Would this be for 1.0.x, 1.1.x, or both?

**Comment by henkmollema** [comment]
@Eilon this feature was added in 1.1 so no need for a patch in 1.0, I guess.

Personally I would like a patch release for this. We used this feature and hit the error (as mentioned [here](https://github.com/aspnet/DependencyInjection/issues/467#issuecomment-281365192)) so we had to disable it.

**Comment by Eilon** [comment]
Thanks, we'll evaluate this for the next patch release.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by pakrym** [comment]
Fixed in https://github.com/aspnet/DependencyInjection/pull/513

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!

**Comment by henkmollema** [comment]
Awesome @Eilon, thanks! I'll try them out tomorrow.

**Comment by henkmollema** [comment]
@Eilon is it correct that there are no patch packages for `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation`?

**Comment by Eilon** [comment]
@henkmollema there will be an update to that package, but I think only due to its dependencies (e.g. MVC) being updated. I don't think there are any actual functional fixes in that package.

**Comment by henkmollema** [comment]
@Eilon @pakrym  I still hit some kind of race condition when enabling scope validation. I've created a repro here: https://github.com/henkmollema/DiConcurrencyBug.

/cc @davidfowl

**Comment by pakrym** [comment]
@henkmollema can you file a separate bug please, I'll investigate it today.

**Comment by henkmollema** [comment]
@pakrym done: #518.

**Comment by pakrym** [comment]
@henkmollema @Eilon This was caused by my mistake, fix was backported to a wrong branch and is not included in the build on the patch feed.

**Comment by pakrym** [comment]
I merged it to the right branch and verified that package built from it fixes the issue.

**Comment by henkmollema** [comment]
I see, thanks!

**Comment by henkmollema** [comment]
When can I expect these packages to show up at https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public?

**Comment by Eilon** [comment]
@henkmollema the builds happen automatically, and I see the last build was pushed about 3 hours ago. Can you try updating to see if you get the new packages?

**Comment by henkmollema** [comment]
@Eilon a bit late, but it works. Thanks!

**Comment by Eilon** [comment]
@henkmollema good to know, thanks!
