### ISSUE TITLE
adding more than one generic services

### ISSUE THREAD

**Issue by rm2k** [aspnet/DependencyInjection#494]
I have 2 generic services defined as:

    HandlerA<TQuery,TResult> : IHandler<TQueryOfTypeA, TResultOfTypeA>
    HandlerB<TQuery,TResult> : IHandler<TQueryOfTypeB, TResultOfTypeB>

and I add them as:

    services.AddScoped(typeof(IHandler<,>),typeof(HandlerA<,>));
    services.AddScoped(typeof(IHandler<,>),typeof(HandlerA<,>));

Doing the above, I get an exception that

`HandlerB<TQueryOfTypeA, TResultOfTypeA>` can not be convrted to type `IHandler<TQueryOfTypeA, TResultOfTypeA>`

**Comment by Eilon** [comment]
@rm2k we're a bit confused about some of the code you showed.

In this code:

```c#
HandlerA<TQuery,TResult> : IHandler<TQueryOfTypeA, TResultOfTypeA>
```

What are `TQueryOfTypeA` and `TResultOfTypeA`? Are they generic args? Or actual concrete types?

And, in the second code snippet:

```c#
services.AddScoped(typeof(IHandler<,>),typeof(HandlerA<,>));
services.AddScoped(typeof(IHandler<,>),typeof(HandlerA<,>));
```

Is the second line supposed to use `HandlerB<,>`?

It would also be help for us to understand more about the specific scenario you have. That is, what services are you trying to resolve, etc.?
