### ISSUE TITLE
Investigate lock on thread executing  System.Linq.Expressions code during first request

### ISSUE THREAD

**Issue by pakrym** [aspnet/DependencyInjection#501]
@DamianEdwards was observing his web application thread waiting on thread pool thread that was executing `System.Linq.Expressions` code during first request. We should never block on expression trees compilation. 

Environment:
AppServices + live.asp.net with views precompiled

**Comment by davidfowl** [comment]
Are you sure that wasn't read incorrectly? Was it actually CPU Blocked time?

**Comment by DamianEdwards** [comment]
The request thread was "BLOCKED" (that's what the profile called it) at the call to DI, and the thread doing the expression compilation was the only thread active during the blocked time.

**Comment by davidfowl** [comment]
My only guess here would be that the `Task.Run` we use is being inlined.

**Comment by davidfowl** [comment]
Or we have code doing compilation elsewhere... Do you still have the trace or a picture or anything?

**Comment by pakrym** [comment]
I wasn't able to repro this with live.asp.net dev branch. Please reopen if happens again.
