### ISSUE TITLE
[Question] Guidance on providing a general DI capability in package

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/DependencyInjection#528]
I was contributing to a package that used AutoFac for DI, but it seems like we should be providing a general way to add our package into the DI container without being specific on the container the user should be using.

In this effort, should we just be providing `IServiceCollection` extension methods? such as aspnet uses, e.g. `UseMvc`. And then just have a dependency on Microsoft.Extensions.DependencyInjection.Abstractions.

And then in our code use constructor DI or the `IServiceProvider` container if really needed.

I can't seem to find good documentation for library authors to provide a good DI interface to allow the user the flexibility to choose their DI framework of choice.

**Comment by davidfowl** [comment]
Yes that's the general pattern that we follow:
- Extension methods on `IServiceCollection` called `AddXX()`
- Use `IServiceProvider` in the [composition root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/)

 Depending on what your library does, you should only use the `IServiceProvider` in the [composition root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/). If you're plugging into an existing composition root (if the framework is going to be activating your classes) then you don't need to directly use `IServiceProvider`. Most of your classes should just be vanilla and should be using constructor injection where possible.

**Comment by damienpontifex** [comment]
Thank you. About what I expected. But seeing a lot still 'picking' a DI container to use/provide :(
