### ISSUE TITLE
there is not a bug,but is a question

### ISSUE THREAD

**Issue by davytitan** [aspnet/DependencyInjection#529]
class ServiceProvider  constructure was defined by  internal, but   Microsoft.Extensions.DependencyInjection.Tests project  callsitetest.cs  can  new ServiceProvider (***) ,Why?
i think they r not  the same application assembly.

**Comment by mstum** [comment]
InternalsVisibleTo is set in the [AssemblyInfo.cs](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection/Properties/AssemblyInfo.cs)

**Comment by davytitan** [comment]
OK~~~ i got it ~~~,thank a  lot ~~~~~ @mstum
