### ISSUE TITLE
How can I get the previous dependency instance of the same type?

### ISSUE THREAD

**Issue by infinnie** [aspnet/DependencyInjection#540]
For example, when I wanted to inject a dependency that is my implementation of the type `IMyInterface`, I wanted my dependency to have access to the previously injected `IMyInterface` dependency instance. How could I achieve that?

**Comment by davidfowl** [comment]
It's not supported in this container implementation.

**Comment by infinnie** [comment]
Whoops. Any plans for shimming that?

**Comment by davidfowl** [comment]
Not in the short term, it's been discussed in the past, see https://github.com/aspnet/DependencyInjection/issues/340

**Comment by rayao** [comment]
I dealt with this with a generic interface like
`    public interface IChainComposed<TService>
    {
        TService Service { get; }
    }
`
And make the implementation class constructor has an IEnumerable<TService> parameter, and then chain all service instances there.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
