### ISSUE TITLE
Provide a way to pass in context from hosting to the ServiceCollection being used when configuring services

### ISSUE THREAD

**Issue by javiercn** [aspnet/DependencyInjection#549]
This can be done through an additional interface implemented by service collection (IServiceConfigurationContext) that just defines an IDictionary<object,object>.

Libraries can downcast IServiceCollection to that interface and get or set context from hosting or from other libraries that have been configured before.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2340
