### ISSUE TITLE
ServiceProvider is null for getting required services

### ISSUE THREAD

**Issue by fir3pho3nixx** [aspnet/DependencyInjection#552]
Hi 

I was wondering if you guys could help me understand why Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider) is null when ILoggerFactory is requested as a service from Microsoft.AspNetCore.Routing.RouteBase.EnsureLoggers(HttpContext context). 

```
ArgumentNullException: Value cannot be null.
 Parameter name: provider
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
Microsoft.AspNetCore.Routing.RouteBase.EnsureLoggers(HttpContext context)
Microsoft.AspNetCore.Routing.RouteBase.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Routing.RouteCollection+<RouteAsync>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

I have a very badly named example project with a ServiceProvider implementation over [here](https://github.com/fir3pho3nixx/castle-windsor-owin-deps/blob/fuk-c/OwinAspNetCore.IoC/WindsorServiceProvider.cs#L9) which also implements [ISupportRequiredService](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ISupportRequiredService.cs). It is injected into my core app over [here](https://github.com/fir3pho3nixx/castle-windsor-owin-deps/blob/fuk-c/OwinAspNetCore/Startup.cs#L34). I am not clear on why [this line](https://github.com/aspnet/Routing/blob/a23f1601fd4f838d4c055d609c4c638044df3230/src/Microsoft.AspNetCore.Routing/RouteBase.cs#L254) of code is failing. It appears that `RequestServices` on the `context` is null. 

I have also tried building the projects locally so I can debug this, but they keep failing with all sorts of errors. Can you guys point me in the right direction for getting this going? 

Any help much appreciated.

**Comment by davidfowl** [comment]
@fir3pho3nixx if you're implementing a custom IServiceProvider then I recommend you run the test suite https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Specification.Tests/. It's likely that you're not properly supporting all of the required semantics.

**Comment by fir3pho3nixx** [comment]
@davidfowl - Nice one, will give it a go. Thanks.

**Comment by fir3pho3nixx** [comment]
>From the looks of it, you're not implementing scopes in your container.

Interesting observation, I am registering these [implementations](https://github.com/fir3pho3nixx/castle-windsor-owin-deps/blob/fuk-c/OwinAspNetCore.IoC/WindsorServiceScopeFactory.cs) [here](https://github.com/fir3pho3nixx/castle-windsor-owin-deps/blob/fuk-c/OwinAspNetCore.IoC/ServiceCollectionExtensions.cs#L18).

**Comment by fir3pho3nixx** [comment]
Good stuff! Heaps of failing tests ...

**Comment by fir3pho3nixx** [comment]
![image](https://user-images.githubusercontent.com/607402/28539035-2dfa0b20-70a8-11e7-9a01-eca29aa4513a.png)
