### ISSUE TITLE
Microsoft.Extensions.DependencyInjection.Specification.Tests nuget does not have correct dependencies

### ISSUE THREAD

**Issue by fir3pho3nixx** [aspnet/DependencyInjection#560]
Hi 

I installed this to get some tests going for my implementation of IServiceProvider using Castle Windsor as advised [here](https://github.com/aspnet/DependencyInjection/issues/552#issuecomment-317274810). 

The trouble is that it does not work in visual studio out of the box because it is missing some dependencies.

Can you please add the following so it works `out of the box` with resharper:

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
<PackageReference Include="xunit" Version="2.2.0" />
<PackageReference Include="xunit.runner.console" Version="2.2.0" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
``` 

Thanks

**Comment by davidfowl** [comment]
I'm not sure those should be added by default. Your trat project should pull in the things required to make it function (AKA the host). What if you wanted to use the UWP test runner? Shouldn't that be included too?

**Comment by fir3pho3nixx** [comment]
> `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />`

Without this you get weird errors anyway. And I would expect most people use the console on both windows and linux via `dotnet test`. Otherwise this is just a package with broken depedencies that creates bad UX for people who are new to the technology. 

In the majority of the cases I would have thought Visual Studio was a thing. So perhaps we could create a new package for Visual Studio? Your UWP argument is a little contrived but not altogether off track. People might want to test new container implementations there too. Also given this is test project does it really matter? You have already imposed xunit, why not go all the way!

**Comment by fir3pho3nixx** [comment]
I know what is going on here, was just thinking of everyone else. Happy to close if there is no agreed action.
