### ISSUE TITLE
Implicit IDisposable implementation requirement for IServiceProvider

### ISSUE THREAD

**Issue by hikalkan** [aspnet/DependencyInjection#566]
``DisposesInReverseOrderOfCreation`` unit test (https://github.com/aspnet/DependencyInjection/blob/dev/src/DI.Specification.Tests/DependencyInjectionSpecificationTests.cs#L661) seems added in v2.0 which makes IServiceProvider implementation to be IDisposable.

This unit test is disposing the root service provider. Do you expect that it disposes the root scope (DI container in most cases)?

**Comment by hikalkan** [comment]
In addition, same (``DisposesInReverseOrderOfCreation``) unit test says that DI framework should dispose objects in reverse order it creates. However Castle Windsor does not behaive like that. Is that fundamenatal feature or just testing behaviour of default implementation.

I'm asking it because I'm maintaining Castle Windsor adapter for this framework (https://github.com/volosoft/castle-windsor-ms-adapter)

**Comment by davidfowl** [comment]
> This unit test is disposing the root service provider. Do you expect that it disposes the root scope (DI container in most cases)?

Yes.

> This unit test is disposing the root service provider. Do you expect that it disposes the root scope (DI container in most cases)?

I think it's pretty fundamental. The issue is that trying to access services that you depend on in dispose used to fail. I don't think we have anything in the framework that used that relies on this but I think orchard does.

**Comment by hikalkan** [comment]
Thank you @davidfowl for your explanation.
