### ISSUE TITLE
Refactor ServiceCollectionServiceExtensionsTest

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DependencyInjection#570]
https://github.com/aspnet/DependencyInjection/pull/569#discussion_r133778668

There is a member data collection that has data not required by all test methods. Xunit 2.3.0 requires us to use all theory parameters or remove them. We can factor the memberdata into collections to that each test only gets data it uses. 

cc @pakrym

**Comment by pakrym** [comment]
Doesn't need to be refactored, suppressing false positive warning is fine in this case: https://github.com/aspnet/DependencyInjection/pull/571
