### ISSUE TITLE
Cannot consume scoped service from singleton

### ISSUE THREAD

**Issue by sharok** [aspnet/DependencyInjection#572]
Today, I updated my project to ASP.NET Core 2 and now, I get the following error:
> Cannot consume scoped service IMongoDbContext from singleton IActiveUsersService

All works fine for ASP.NET Core 1.1
I have the following code:
```
services.AddSingleton<IActiveUsersService, ActiveUsersService>();
services.AddScoped<IMongoDbContext, MongoDbContext>();
services.AddSingleton(option =>
{
   var client = new MongoClient(MongoConnectionString.Settings);
   return client.GetDatabase(MongoConnectionString.Database);
})



public class MongoDbContext : IMongoDbContext
{
   private readonly IMongoDatabase _database;

   public MongoDbContext(IMongoDatabase database)
   {
      _database = database;
   }

   public IMongoCollection<T> GetCollection<T>() where T : Entity, new()
   {
      return _database.GetCollection<T>(new T().CollectionName);
   }
}

public class IActiveUsersService: ActiveUsersService
{

   public IActiveUsersService(IMongoDbContext mongoDbContext)
   {
      ...
   }
}
```

**Comment by davidfowl** [comment]
> All works fine for ASP.NET Core 1.1

Yes, it's likely that you had a bug in your 1.1 application. This is now disallowed by default. When you consume a scoped service from a singleton you're forcing the scoped service to be a singleton. Why is your services scoped in the first place? Who is supposed to dispose this scoped object?

**Comment by sharok** [comment]
Yeah, I have realized it... Need to check all my services. Thanks.
