### ISSUE TITLE
"Cannot Resove Symbol ‘XXX’" in test libraries.

### ISSUE THREAD

**Issue by wddpct** [aspnet/DependencyInjection#576]
Actually, I don't know if it's a good idea to ask this question here. I downloaded the last release version in my disk **C**. Then I restored the nuget package by runing the 'build.cmd' file. After open the .sln, I can rebuild the whole project well, howerver, why my code still show wrong highlight? Only for tow test projects.

![image](https://user-images.githubusercontent.com/8480318/29766375-20e2eafe-8c11-11e7-8d66-dd547c7f6178.png)

Thanks for anyway!

**Comment by khellang** [comment]
That looks like a R# issue. If you try suspending it, you'll see that everything is really OK. Try installing [version 2017.2](https://blog.jetbrains.com/dotnet/2017/08/24/resharper-ultimate-2017-2-released/).

Anyway, there's little to be done about it in this repo 😛

**Comment by wddpct** [comment]
@khellang Thanks a lot! Now I am going to enjoy my Chinese Valentine's Day 😛

**Comment by Eilon** [comment]
I guess I'll close this then. Enjoy the holiday!
