### ISSUE TITLE
Improve searchability on nuget.org

### ISSUE THREAD

**Issue by ChristopherHaws** [aspnet/DependencyInjection#582]
Hello,

I find myself using this library a lot, especially in linqpad scripts when I am testing something out. Currently, pretty much the only way to get this library to return in the nuget search results is by typing the exact name of the entire package `Microsoft.Extensions.DependencyInjection`. It would be nice to have a few more tags added to the packages to improve searchability a bit. Some suggestions I would have are:

- microsoft
- ms
- ioc

Ideally I would like to be able to type `ms ioc` or `ms di` and have it come back as the first result.

Thanks and keep up the great work! 👍

**Comment by Eilon** [comment]
This issue was moved to NuGet/NuGetGallery#4687
