### ISSUE TITLE
Improve the circular dependency exception message

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/DependencyInjection#586]
Currently it says `A circular dependency was detected for the service of type 'MyType'`.

It should provide all types in the cycle.

**Comment by Eilon** [comment]
You mean like this?

`A circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency was detected for the service of type that has a circular dependency.`?

**Comment by AndriySvyryd** [comment]
@Eilon Sounds perfect, as I always say - redundancy leads to clarity.

**Comment by Eilon** [comment]
@pakrym I'm assigning to you to resolve when https://github.com/aspnet/DependencyInjection/pull/592 is merged.
