### ISSUE TITLE
AddSingleton breaks in 2.0?

### ISSUE THREAD

**Issue by Eilon** [aspnet/DependencyInjection#595]
_From @HarelM on October 7, 2017 22:20_

I'm in the middle of migrating my project from netcoreapp1.1 to netcoreapp2.0.
My code it at the following repository:
https://github.com/IsraelHikingMap/Site
There is a branch called NetStandard2.0 there where I updated the code in order to move from 1.1 to 2.0.
Most of the code stayed the same but a new bug started to appear after the migration:
I have a class there called LRUCache which caches the recently logged users - it is registered in the following class as **singleton**:
https://github.com/IsraelHikingMap/Site/blob/8d70dab7c0ea8fe63993d78fd1c30e8e7ca97fa4/IsraelHiking.API/RegisterApi.cs#L34
When running the project I see two instances with different hash code:
The first is here:
https://github.com/IsraelHikingMap/Site/blob/8d70dab7c0ea8fe63993d78fd1c30e8e7ca97fa4/IsraelHiking.Web/OsmAccessTokenValidator.cs#L17
and the second is here:
https://github.com/IsraelHikingMap/Site/blob/8d70dab7c0ea8fe63993d78fd1c30e8e7ca97fa4/IsraelHiking.API/Controllers/OsmController.cs#L39

When using the immediate window for those different flows I get those hash codes:
_cache.GetHashCode()
37382511
_cache.GetHashCode()
44927025

Am I crazy? Did I miss-configured something? Am I the only one who is reporting this?
Thanks ahead! 

_Copied from original issue: aspnet/Mvc#6924_

**Comment by Eilon** [comment]
`GetHashCode()` is not necessarily the best way to determine if two objects are the same because the type could have a buggy implementation of it... but in the case of this app that doesn't appear to be a problem.

Nevertheless, are you able to confirm whether they're actually the same instance or not? In VS you can "tag" an item in the watch window (right-click it and "add object tag") and see if they're truly the same, as opposed to just odd behavior with the hash code? Or set a breakpoint in the LRUCache constructor?

Also adding @pakrym in case he has thoughts on this.

This is definitely super weird, and does not appear to be expected...

**Comment by Eilon** [comment]
_From @HarelM on October 10, 2017 7:55_

I know for sure that this is not the same instance as this class has a dictionary and one instance has it empty while the other has it with one item.
GetHashCode was just to illustrate that it's not the same one.

**Comment by Eilon** [comment]
_From @pakrym on October 10, 2017 15:13_

@HarelM can you provide smaller repro or give instructions on how to run your site and reproduce the bug. I tried running it yesterday but got

```
D:\temp\Site\IsraelHiking.Web [NetStansards2.0 +0 ~1 -0]> dotnet run
Using launch settings from D:\temp\Site\IsraelHiking.Web\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\pakrymet\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.

Unhandled Exception: System.ArgumentException: The directory name C:\Users\osmhike\Documents\GitHub\IsraelHiking\Map\English\ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at IsraelHiking.Web.Startup.SetupStaticFiles(IApplicationBuilder app)
   at IsraelHiking.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at IsraelHiking.Web.Program.Main(String[] args)
```

**Comment by Eilon** [comment]
_From @HarelM on October 10, 2017 15:41_

I'll see if I can create a smaller reproduction.
Meanwhile you can run it from visual studio in debug mode or edit the appsettings.production.json file to point to an existing folder in your file system - this is a static files location the site is using, if the folder does not exists it throws.
you can also copy the appsetting.json and override appsettings.production.json.
The instructions on how to debug and run the site can be found here:
https://github.com/IsraelHikingMap/Site#setting-up-the-project-for-development

**Comment by Eilon** [comment]
@pakrym can you try the suggestions above on how to run the repro app?

**Comment by pakrym** [comment]
@Eilon I tried but wasn't able to run it far enough to reproduce the issue.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.

**Comment by HarelM** [comment]
Can you please reopen the issue?
I have made an effort to reduce the solution as much as possible.
Please run the attached solution.
It should open at the following address:
`http://localhost:58231/api/osm/`
I'm using firefox to edit the GET request and add the following header:
`Authorization: Bearer 123;456`
but you can use any HTTP client you want.
Place a breakpoint in the following places:
OsmAccessTokenValidator, L41
and 
OsmController, L49
Different instances of `LruCache`.

[netstd2.0-bugSingleton.zip](https://github.com/aspnet/DependencyInjection/files/1400202/netstd2.0-bugSingleton.zip)

It might be related to the usage of `services.BuildServiceProvider()` in `Setup.cs` but it used to work in 1.1...

**Comment by pakrym** [comment]
Yes, calling `BuildServiceProvider` creates a new `ServiceProvider` every time, singletons are scoped to service provider. This wouln't have worked in 1.1 either.

**Comment by HarelM** [comment]
Thanks for the quick response.
The problem is that in 1.1 I wrote the following code in `Configure` meethod:
```C#
            var jwtBearerOptions = new JwtBearerOptions();
            jwtBearerOptions.SecurityTokenValidators.Clear();
            jwtBearerOptions.SecurityTokenValidators.Add(app.ApplicationServices.GetRequiredService<ISecurityTokenValidator>());
            app.UseJwtBearerAuthentication(jwtBearerOptions);
```

But in 2.0 as far as I understand I need to write it in the `ConfigureServices` method where I can't use `app.ApplicationServices` so I need to build my service provider.

Am I missing something?

**Comment by pakrym** [comment]
You can write `IConfigureOptions<JwtBearerOptions>` that would inject `ISecurityTokenValidator` and add it to `JwtBearerOptions` object.

``` C#

    public class JwtBearerOptionsValidatorConfigureOptions : ConfigureOptions<JwtBearerOptions>
    {
        public JwtBearerOptionsValidatorConfigureOptions(ISecurityTokenValidator securityTokenValidator)
            : base(options => options.SecurityTokenValidators.Add(securityTokenValidator))
        {
        }

    }

        public void ConfigureServices(IServiceCollection services)
        {

            services.AddSingleton<IConfigureOptions<JwtBearerOptions>, JwtBearerOptionsValidatorConfigureOptions>();
```

**Comment by HarelM** [comment]
Is this the best approach? seems way too complicated for what I want to achieve...

**Comment by pakrym** [comment]
That's the way to do it if your `ISecurityTokenValidator` needs dependencies from DI.

**Comment by HarelM** [comment]
Sounds like a design problem with either the dependency injection or JWT - I have worked with many DI frameworks and the fact that I need to write a class in order to inject something to somewhere is what I define as "design smell"...
The problem as I see it is the fact that I need to initialize some things in the `ConfigureServices` method where I don't have my DI container ready yet - I think you guys should revisit the decision made there...

**Comment by pranavkm** [comment]
@HarelM the plan is to make writing this easier in 2.1.0. See https://github.com/aspnet/Options/issues/236. For the time being, writing a `IConfigureOptions` instance would the recommended solution.

**Comment by HarelM** [comment]
Will you be able to post the full code of how should one use the above code with JWT? I took the above code and updated mine but the token validator is never called.

**Comment by HarelM** [comment]
I found this to work:
```C#
    public class JwtBearerOptionsValidatorConfigureOptions : PostConfigureOptions<JwtBearerOptions>
    {
        public JwtBearerOptionsValidatorConfigureOptions(ISecurityTokenValidator securityTokenValidator) : base(
            JwtBearerDefaults.AuthenticationScheme,
            options =>
            {
                options.SecurityTokenValidators.Clear();
                options.SecurityTokenValidators.Add(securityTokenValidator);
            })
        {
            
        }
    }
```
And later adding:
```
        public void ConfigureServices(IServiceCollection services)
        {
        ...
            services.AddSingleton<IPostConfigureOptions<JwtBearerOptions>, JwtBearerOptionsValidatorConfigureOptions>();
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();
```
