### ISSUE TITLE
Feature request: AutoRegistration for ISomeObject and SomeObject implementation

### ISSUE THREAD

**Issue by davidrevoledo** [aspnet/DependencyInjection#604]
Is there any plan to add Auto-registration for interfaces, for instance I use a lot autofac wich has AsImplementedInterfaces method, Currently for new projects we're using the built-in DI for asp.net core but we need to use in whole project a manual auto registration for common scenarios like ISomeRepository as SomeRepository.

I read in other issues that asp.net team wants to keep simple this repo and no add a lot of features, what about a simple registration by naming convention ?

Thanks so much. :) 

Kind Regards.

David.

**Comment by khellang** [comment]
See [Scrutor](https://github.com/khellang/Scrutor) for a thin layer on top of MS.Ext.DI :wink:

**Comment by davidrevoledo** [comment]
@khellang awesome, I think it does make sense if you want to keep simple Ms.Ext.DI, so this library it's really great ! :) I'd love to contribute there.. I've using a lot of Enterprise.Library Unity DI / autofac 

great thanks.

**Comment by Eilon** [comment]
No current plans to add the functionality of [Scrutor](https://github.com/khellang/Scrutor) as a built-in feature. Scrutor already looks pretty cool so if it does what you need, I recommend using it.

**Comment by davidrevoledo** [comment]
@Eilon sure It's working for me ! thanks a lot.
