### ISSUE TITLE
THIS ISSUE TRACKER IS CLOSED - use the Extensions repo issue tracker

### ISSUE THREAD

**Issue by Eilon** [aspnet/DependencyInjection#621]
Hello, this issue tracker is no longer used. Please log new issues here: https://github.com/aspnet/Extensions/issues

For information about this change, see https://github.com/aspnet/Announcements/issues/283

**Comment by natemcmaster** [comment]
Closing because this repo is being archived. See https://github.com/aspnet/DependencyInjection/pull/662
