### ISSUE TITLE
Resolve a service with multiple implementations based on consumer metadata

### ISSUE THREAD

**Issue by broomandan** [aspnet/DependencyInjection#660]
Hi,
Is there a simple way (like Simple Injector) to register multiple implementations for an interface and inject an specific implementation into a consumer?

For instance: 
I have two components (A and B) that are consuming two different implementations (ServiceA, ServiceB) of an interface (IService) factories. I want to be able to instruct the DI resolver, when component A is asking for IService inject implementation ServiceA  and when component B is asking for IService, inject ServiceB implementation.
Simple injector is solving this by providing consumers metadata at resolution time.
 
![image](https://user-images.githubusercontent.com/1119974/46979963-f850b000-d087-11e8-977d-969fc94adf84.png)

Is this feature on the road-map? I would be more than happy to contribute.

Best,
Robert Broomandan

**Comment by natemcmaster** [comment]
@broomandan we don't use the issue tracker on this repo. We're going to merge this repo into https://github.com/aspnet/Extensions in the next few days and deprecate this repo. Can you re-open your issue there?

Thanks,
Nate
