### ISSUE TITLE
Ambiguous constructor matching is not working well

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/DependencyInjection#69]
This is a multi-issue bug but since the issues are extermly related, I'll open only one. 

This bug is the result of an investigation around bug  https://github.com/aspnet/Identity/issues/50 . The RoleManager<T> class has two constructors both with parameters.

~~~C#
public class RoleManager<TRole> : IDisposable where TRole : class
{
    public RoleManager(IRoleStore<TRole> store);
    public RoleManager(IServiceProvider services);
~~~

When one tries to resolve an instance, an exception saying that there is no parameter less constructor is thrown.

The out-of-the-box container has a few issues resolving objects with multiple constructors.

First, there is no way to specify which constructor should be used when injecting. Most DI framework allow you to mark a constructor with an attribute so that no ambiguity exists.

Second, the logic that we have today to resolve multi-constructor object instances seems incorrect. See the comments that I made on code.

From ActivatorUtilities.cs

~~~C#
public static Func<IServiceProvider, object> CreateFactory(Type type)
{
    if (type == null)
    {
        throw new ArgumentNullException("type");
    }

    // Why injectable constructors are only those that are public with parameters?
    // A parameter less constructor is injectable too.
    ConstructorInfo[] constructors = type.GetTypeInfo()
        .DeclaredConstructors
        .Where(IsInjectable)
        .ToArray();

    // If there are two constructors, one with params
    // and one without, why do we default to the one
    // with parameters?
    if (constructors.Length == 1)
    {
        ParameterInfo[] parameters = constructors[0].GetParameters();
        return services =>
        {
            var args = new object[parameters.Length];
            for (int index = 0; index != parameters.Length; ++index)
            {
                args[index] = services.GetService(parameters[index].ParameterType);
            }
            return Activator.CreateInstance(type, args);
        };
    }

    // We only use the default constructor if there is no other constructor
    // with parameters or more than one with parameters. Why?
    return _ => Activator.CreateInstance(type);
}

private static bool IsInjectable(ConstructorInfo constructor)
{
    return constructor.IsPublic && constructor.GetParameters().Length != 0;
}

~~~

My 2c on how I would expect this to work:
1. If there is only one public constructor => use that one and resolve any parameters
2. If there are more than one public constructors => throw an ambiguous match exception
3. If there are more than one public constructors but one of them is marked somehow as injectable (attribute?) => use that one

Another idea that I don't like too much but might work:
See that RoleManager<T> has a constructor that takes an IServiceProvider. Maybe we should default to that in case of ambiguities?

**Comment by HaoK** [comment]
cc @davidfowl @lodejard can we do this?  Add some attribute to say use this ctor for DI?  I'll pony up the time to do this, especially if this lets me add back the simple non DI ctors for identity again... @divega

**Comment by Eilon** [comment]
The new behavior should be:

1. Eliminate all ctors that have non-injectable parameters
2. Eliminate ctors that have parameter sets that are subsets of other ctors (based strictly on sets of types, not name or order)
3. Hope you just have 1 ctor left; otherwise throw an exception
