### ISSUE TITLE
Resolving IEnumerable<T> should return an empty list if nothing is registered

### ISSUE THREAD

**Issue by sebastienros** [aspnet/DependencyInjection#71]
Repro:
- Resolve `IEnumerable<INotRegistered>` where nothing is registered

Result 
- The AspNet seems to return `null`

Expected
- Return `Enumerable.Empty<INotRegistered>()` or anything not `null`

It seems all other implementations work fine with this expectation.

**Comment by jgauffin** [comment]
+1

**Comment by pranavkm** [comment]
Calling `GetServices` does this. Covered by https://github.com/aspnet/DependencyInjection/blob/dev/test/Microsoft.Framework.DependencyInjection.Tests/ServiceProviderExtensionsTest.cs#L138-L150
