### ISSUE TITLE
Discuss third party DI containers API

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/DependencyInjection#89]
Currently it requires a ton of "boiler plate" code to utilize other DI containers such as Autofac.

We should discuss a more streamlined approach to DI than how we do it in the current world.

Autofac for example currently looks like:
```C#
var services = new ServiceCollection();
// Add Mvc here etc.
var builder = new ContainerBuilder();
AutofacRegistration.Populate(builder, services);
var container = builder.Build();
app.UseServices(container.Resolve<IServiceProvider>());
```

Lets figure out what we "want" it to look like going forward.

**Comment by davidfowl** [comment]
Feels like this can be closed:

```C#
var services = new ServiceCollection();
services.AddMvc();
var builder = new ContainerBuilder();
builder.Populate(services);
var container = builder.Build();
return container.Resolve<IServiceProvider>();
```

How much boiler plate do you want to remove

**Comment by davidfowl** [comment]
One thing we *could* do, is have another interface to get the IServiceProvider from whatever you return from ConfigureServices. Lets call this `IServiceProviderProvider` because why not. The code would look like this:

```C#
public IServiceProviderProvider ConfigureServices(IServiceCollection services)
{
    services.AddMvc();
    var provider = new AutofacServiceProviderProvider();
    provider.Builder.Populate(services);
    return provider;
}
```

In theory though, if we treated our DI container as a 3rd party DI container instead of being baked into Hosting, it might be easier to come up with something more universal and clean /cc @lodejard

**Comment by jeremydmiller** [comment]
@davidfowl Just a quick comment on your code up above, maybe add an extension method where you just pass in a pre-built StructureMap/Ninject/Autofac container to make it declarative. The equivalent in FubuMVC was something like:

```FubuApplication.DefaultPolicies.StructureMap(IContainer container)``` that would take in a Container then add in all the FubuMVC specific services and set up our service locator where necessary. I thought that worked out decently for us.

So yours would be something like:

```
services.StructureMap(container);
```

**Comment by Eilon** [comment]
Not planning on doing this at this time.

**Comment by khellang** [comment]
I think the Populate extension method approach that multiple containers have adopted now works OK.

**Comment by pranavkm** [comment]
Could we close this?

**Comment by jeremydmiller** [comment]
@khellang You can push in an existing container, right? My only reservation was that users *can* use any IoC tool's native registration facilities and still let vNext be able to add its required registrations to the app container.

**Comment by davidfowl** [comment]
Yap
