### ISSUE TITLE
Use custom interface instead of IServiceProvider

### ISSUE THREAD

**Issue by halter73** [aspnet/DependencyInjection#90]
Existing `IServiceProvider`s  typically do not follow the behaviors we expect. When an `IServiceProvider` fails to follow our implicit contract by, for example, returning null instead of returning an empty or populated `IEnumberable<IService>`, our chaining logic breaks down since our assumptions are violated.

**Comment by davidfowl** [comment]
Should we close this?

**Comment by GrabYourPitchforks** [comment]
Yup - this is no longer necessary.
