### ISSUE TITLE
ServiceProviderExtensions GetServiceOrNull does not check if serviceType is null

### ISSUE THREAD

**Issue by gideonkorir** [aspnet/DependencyInjection#97]
Method checks if the provider is null twice line 56 and 61

**Comment by davidfowl** [comment]
@gideonkorir Do you want to send a PR for this?

**Comment by gideonkorir** [comment]
@davidfowl the method has been removed from development branch can't find it. Also getting same error as this guy: http://stackoverflow.com/questions/29075247/open-xproj-in-visual-studio-2015-ctp-6

**Comment by muratg** [comment]
The method was removed. Closing this bug.
