### ISSUE TITLE
Need support Lazy<T>

### ISSUE THREAD

**Issue by nidilong** [aspnet/DependencyInjection#98]
DI should support Lazy<T>.
We don't want to instantiate immediately sometime.

**Comment by RehanSaeed** [comment]
It's possible to sprinkle a few extension methods over `IServiceCollection` to add Lazy support with very little effort, without requiring all IoC containers to support this feature. Thoughts?

```
public static IServiceCollection AddScopedLazy<TService, TImplementation>(this IServiceCollection services)
            where TService : class
            where TImplementation : class, TService
{
    return services
        .AddScoped<TService, TImplementation>()
        .AddScoped(x => new Lazy<TService>(() => x.GetRequiredService<TService>()));
}
```

**Comment by AceHack** [comment]
@RehanSaeed these extensions do not work when trying to register multiple implementations of the same interface and use GetServices
