### ISSUE TITLE
Allow use outside of ASP.NET

### ISSUE THREAD

**Issue by erlimar** [aspnet/DependencyInjection#99]
Add support for using Microsoft.Framework.DependencyInjection in non ASP.NET applications, console applications eg.

```csharp
public class Program
{
    public static void Main(string[] args)
    {
          var services = new ServiceCollection();
          services.AddTransient<ISampleType, SampleType>();
          var provider = new DefaultServiceProvider(services);
          var myType = provider.GetService<ISampleType>();
    }
}
```

**Comment by wwwlicious** [comment]
@davidfowl for r4mvc we want to extend/register types in a ICompileModule, you don't really have access to the external container to modify it so you have to create you own afaik

**Comment by davidfowl** [comment]
Sounds like the wrong approach to extend the container. ICompileModule is about compiler extensibility.

**Comment by wwwlicious** [comment]
ah, would welcome [some feedback[(https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/R4MVCCompilerModule.cs#L38) then if you have the time. I tried a few things but so far I came up with [this](https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/Ioc/IocConfig.cs), is that a horrible thing to do?

**Comment by davidfowl** [comment]
@wwwlicious I wouldn't add anything to this issue as it has nothing to do with what you're trying to do (and I'm not even sure what that is).
